/*
// Generated by PCHRefactor.rb v1.0 for target <Core.Application>
//------------------------------------------------------------------------------
// Date : 2017-09-26 00:42:09 UTC
*/

// Processed dependencies for Core.Application-Win32-Debug : 45 std, 0 sdk, 1 prj, 12 src
// Processed dependencies for Core.Application-Win32-FastDebug : 45 std, 0 sdk, 1 prj, 12 src
// Processed dependencies for Core.Application-Win32-Release : 45 std, 0 sdk, 1 prj, 12 src
// Processed dependencies for Core.Application-Win32-Profiling : 45 std, 0 sdk, 1 prj, 12 src
// Processed dependencies for Core.Application-Win32-Final : 45 std, 0 sdk, 1 prj, 12 src
// Processed dependencies for Core.Application-Win64-Debug : 45 std, 0 sdk, 1 prj, 12 src
// Processed dependencies for Core.Application-Win64-FastDebug : 45 std, 0 sdk, 1 prj, 12 src
// Processed dependencies for Core.Application-Win64-Release : 45 std, 0 sdk, 1 prj, 12 src
// Processed dependencies for Core.Application-Win64-Profiling : 45 std, 0 sdk, 1 prj, 12 src
// Processed dependencies for Core.Application-Win64-Final : 45 std, 0 sdk, 1 prj, 12 src

/*
// Standard headers
//------------------------------------------------------------------------------
*/
#include <algorithm>
#include <cstdint>
#include <cstdlib>
#include <limits>
#include <cfloat>
#include <climits>
#include <cmath>
#include <cwchar>
#include <cstddef>
#include <initializer_list>
#include <new>
#include <exception>
#include <type_traits>
#include <utility>
#include <cstdio>
#include <cstring>
#include <atomic>
#include <memory>
#include <typeinfo>
#include <functional>
#include <tuple>
#include <stdexcept>
#include <ios>
#include <streambuf>
#include <system_error>
#include <cerrno>
#include <ctime>
#include <iterator>
#include <mutex>
#include <chrono>
#include <ratio>
#include <thread>
#include <iostream>
#include <sstream>
#include <string>
#include <cctype>
#include <cwctype>
#include <locale>
#include <shared_mutex>
#include <condition_variable>
#include <fstream>

/*
// SDK headers
//------------------------------------------------------------------------------
*/

/*
// Project headers
//------------------------------------------------------------------------------
*/
#include "Core.Application/Application.h"

