/*
// Generated by PCHRefactor.rb v1.1 for target <Runtime/Core>
//------------------------------------------------------------------------------
// Date : 2018-09-05 21:21:52 UTC
*/

//                                           Target | STD | SDK | PRJ | SRC
// ------------------------------------------------------------------------
//                         Runtime/Core-Win32-Debug |  50 |  32 |   0 | 115
//                     Runtime/Core-Win32-FastDebug |  50 |  32 |   0 | 115
//                       Runtime/Core-Win32-Release |  50 |  32 |   0 | 115
//                     Runtime/Core-Win32-Profiling |  50 |  32 |   0 | 115
//                         Runtime/Core-Win32-Final |  49 |  32 |   0 | 115
//                         Runtime/Core-Win64-Debug |  50 |  32 |   0 | 115
//                     Runtime/Core-Win64-FastDebug |  50 |  32 |   0 | 115
//                       Runtime/Core-Win64-Release |  50 |  32 |   0 | 115
//                     Runtime/Core-Win64-Profiling |  50 |  32 |   0 | 115
//                         Runtime/Core-Win64-Final |  49 |  32 |   0 | 115

/*
// Standard headers
//------------------------------------------------------------------------------
*/
#if 0 // dummy
#elif defined(BUILDCONFIG_Win32_Debug) || defined(BUILDCONFIG_Win32_FastDebug) || defined(BUILDCONFIG_Win32_Release) || defined(BUILDCONFIG_Win32_Profiling) || defined(BUILDCONFIG_Win64_Debug) || defined(BUILDCONFIG_Win64_FastDebug) || defined(BUILDCONFIG_Win64_Release) || defined(BUILDCONFIG_Win64_Profiling)
#    include <algorithm>
#    include <cstdint>
#    include <cstdlib>
#    include <limits>
#    include <cfloat>
#    include <climits>
#    include <cmath>
#    include <cwchar>
#    include <cstddef>
#    include <initializer_list>
#    include <new>
#    include <exception>
#    include <type_traits>
#    include <utility>
#    include <iosfwd>
#    include <cstdio>
#    include <cstring>
#    include <atomic>
#    include <memory>
#    include <typeinfo>
#    include <functional>
#    include <tuple>
#    include <unordered_map>
#    include <list>
#    include <stdexcept>
#    include <vector>
#    include <iterator>
#    include <istream>
#    include <ostream>
#    include <ios>
#    include <streambuf>
#    include <system_error>
#    include <cerrno>
#    include <mutex>
#    include <chrono>
#    include <ratio>
#    include <thread>
#    include <cctype>
#    include <cwctype>
#    include <locale>
#    include <string>
#    include <ctime>
#    include <optional>
#    include <iostream>
#    include <clocale>
#    include <cassert>
#    include <regex>
#    include <condition_variable>
#    include <queue>
#    include <deque>
#elif defined(BUILDCONFIG_Win32_Final) || defined(BUILDCONFIG_Win64_Final)
#    include <algorithm>
#    include <cstdint>
#    include <cstdlib>
#    include <limits>
#    include <cfloat>
#    include <climits>
#    include <cmath>
#    include <cwchar>
#    include <cstddef>
#    include <initializer_list>
#    include <new>
#    include <exception>
#    include <type_traits>
#    include <utility>
#    include <iosfwd>
#    include <cstdio>
#    include <cstring>
#    include <atomic>
#    include <memory>
#    include <typeinfo>
#    include <functional>
#    include <tuple>
#    include <unordered_map>
#    include <list>
#    include <stdexcept>
#    include <vector>
#    include <iterator>
#    include <istream>
#    include <ostream>
#    include <ios>
#    include <streambuf>
#    include <system_error>
#    include <cerrno>
#    include <mutex>
#    include <chrono>
#    include <ratio>
#    include <thread>
#    include <cctype>
#    include <cwctype>
#    include <locale>
#    include <string>
#    include <ctime>
#    include <iostream>
#    include <clocale>
#    include <cassert>
#    include <regex>
#    include <condition_variable>
#    include <queue>
#    include <deque>
#else
#     error "unknown build config"
#endif

/*
// SDK headers
//------------------------------------------------------------------------------
*/
#include <SDKDDKVer.h>
#include <stdio.h>
#include <tchar.h>
#include <wchar.h>
#include <stdint.h>
#include <string.h>
#include <locale.h>
#include <time.h>
#include <comdef.h>
#include <windows.h>
#include <winnt.h>
#include <comutil.h>
#include <malloc.h>
#include <memory.h>
#include <emmintrin.h>
#include <xmmintrin.h>
#include <intrin.h>
#include <immintrin.h>
#include <DbgHelp.h>
#include <TlHelp32.h>
#include <windowsx.h>
#include <initguid.h>
#include <KnownFolders.h>
#include <shellapi.h>
#include <Shlwapi.h>
#include <ShlObj.h>
#include <fcntl.h>
#include <io.h>
#include <Psapi.h>
#include <Lmcons.h>
#include <mbctype.h>
#include <VersionHelpers.h>

/*
// Project headers
//------------------------------------------------------------------------------
*/

