/*
// Generated by PCHRefactor.rb v1.1 for target <Tools/UnitTest>
//------------------------------------------------------------------------------
// Date : 2019-12-24 02:40:46 UTC
*/

//                                           Target | STD | SDK | PRJ | SRC
// ------------------------------------------------------------------------
//                       Tools/UnitTest-Win32-Debug |  54 |   0 |  39 |  13
//                   Tools/UnitTest-Win32-FastDebug |  54 |   0 |  39 |  13
//                     Tools/UnitTest-Win32-Release |  54 |   0 |  39 |  13
//                   Tools/UnitTest-Win32-Profiling |  54 |   0 |  39 |  13
//                       Tools/UnitTest-Win32-Final |  54 |   0 |  37 |  13
//                       Tools/UnitTest-Win64-Debug |  54 |   0 |  39 |  13
//                   Tools/UnitTest-Win64-FastDebug |  54 |   0 |  39 |  13
//                     Tools/UnitTest-Win64-Release |  54 |   0 |  39 |  13
//                   Tools/UnitTest-Win64-Profiling |  54 |   0 |  39 |  13
//                       Tools/UnitTest-Win64-Final |  54 |   0 |  37 |  13

/*
// Standard headers
//------------------------------------------------------------------------------
*/
#if 0 // dummy
#elif defined(BUILD_Win32_Debug) || defined(BUILD_Win32_FastDebug) || defined(BUILD_Win32_Release) || defined(BUILD_Win32_Profiling) || defined(BUILD_Win64_Debug) || defined(BUILD_Win64_FastDebug) || defined(BUILD_Win64_Release) || defined(BUILD_Win64_Profiling)
#    include <algorithm>
#    include <cstdint>
#    include <cstdlib>
#    include <limits>
#    include <cfloat>
#    include <climits>
#    include <cwchar>
#    include <cstdio>
#    include <cstddef>
#    include <initializer_list>
#    include <new>
#    include <exception>
#    include <type_traits>
#    include <cstring>
#    include <utility>
#    include <atomic>
#    include <memory>
#    include <iosfwd>
#    include <typeinfo>
#    include <functional>
#    include <tuple>
#    include <unordered_map>
#    include <cmath>
#    include <list>
#    include <vector>
#    include <stdexcept>
#    include <iterator>
#    include <istream>
#    include <ostream>
#    include <ios>
#    include <streambuf>
#    include <system_error>
#    include <cerrno>
#    include <mutex>
#    include <chrono>
#    include <ratio>
#    include <thread>
#    include <locale>
#    include <ctime>
#    include <regex>
#    include <cctype>
#    include <string>
#    include <cwctype>
#    include <random>
#    include <unordered_set>
#    include <bitset>
#    include <iostream>
#    include <deque>
#    include <cassert>
#    include <cstdarg>
#    include <optional>
#    include <clocale>
#    include <condition_variable>
#    include <memory_resource>
#elif defined(BUILD_Win32_Final) || defined(BUILD_Win64_Final)
#    include <algorithm>
#    include <cstdint>
#    include <cstdlib>
#    include <limits>
#    include <cfloat>
#    include <climits>
#    include <cwchar>
#    include <cstdio>
#    include <cstddef>
#    include <initializer_list>
#    include <new>
#    include <exception>
#    include <type_traits>
#    include <cstring>
#    include <utility>
#    include <atomic>
#    include <memory>
#    include <iosfwd>
#    include <typeinfo>
#    include <functional>
#    include <tuple>
#    include <unordered_map>
#    include <cmath>
#    include <list>
#    include <vector>
#    include <stdexcept>
#    include <iterator>
#    include <istream>
#    include <ostream>
#    include <ios>
#    include <streambuf>
#    include <system_error>
#    include <cerrno>
#    include <mutex>
#    include <chrono>
#    include <ratio>
#    include <thread>
#    include <locale>
#    include <ctime>
#    include <regex>
#    include <cctype>
#    include <string>
#    include <cwctype>
#    include <random>
#    include <unordered_set>
#    include <bitset>
#    include <iostream>
#    include <deque>
#    include <cassert>
#    include <cstdarg>
#    include <clocale>
#    include <condition_variable>
#    include <memory_resource>
#    include <optional>
#else
#     error "unknown build config"
#endif

/*
// SDK headers
//------------------------------------------------------------------------------
*/

/*
// Project headers
//------------------------------------------------------------------------------
*/
#if 0 // dummy
#elif defined(BUILD_Win32_Debug) || defined(BUILD_Win32_FastDebug) || defined(BUILD_Win32_Release) || defined(BUILD_Win32_Profiling) || defined(BUILD_Win64_Debug) || defined(BUILD_Win64_FastDebug) || defined(BUILD_Win64_Release) || defined(BUILD_Win64_Profiling)
#    include "Runtime/Core/Public/Meta/Iterator.h"
#    include "Runtime/Core/Public/Allocator/Allocation.h"
#    include "Runtime/Core/Public/Allocator/Alloca.h"
#    include "Runtime/Core/Public/Memory/MemoryView.h"
#    include "Runtime/Core/Public/Memory/RefPtr.h"
#    include "Runtime/Core/Public/Memory/MemoryDomain.h"
#    include "Runtime/Core/Public/HAL/PlatformMemory.h"
#    include "Runtime/Core/Public/Container/BitMask.h"
#    include "Runtime/Core/Public/HAL/PlatformMaths.h"
#    include "Runtime/Core/Public/Meta/AlignedStorage.h"
#    include "Runtime/Core/Public/Allocator/Mallocator.h"
#    include "Runtime/Core/Public/Memory/MemoryTracking.h"
#    include "Runtime/Core/Public/IO/StreamProvider.h"
#    include "Runtime/Core/Public/IO/StringView.h"
#    include "Runtime/Core/Public/IO/String.h"
#    include "Runtime/Core/Public/Container/Pair.h"
#    include "Runtime/Core/Public/Container/Vector.h"
#    include "Runtime/Core/Public/Diagnostic/Logger.h"
#    include "Runtime/Core/Public/Time/Timestamp.h"
#    include "Runtime/Core/Public/IO/Format.h"
#    include "Runtime/Core/Public/IO/TextWriter.h"
#    include "Runtime/Core/Public/Misc/Function.h"
#    include "Runtime/Core/Public/Container/Tuple.h"
#    include "Runtime/Core/Public/Thread/ReadWriteLock.h"
#    include "Runtime/Core/Public/HAL/PlatformProcess.h"
#    include "Runtime/Core/Public/Memory/UniqueView.h"
#    include "Runtime/Core/Public/Container/Stack.h"
#    include "Runtime/Core/Public/IO/FormatHelpers.h"
#    include "Runtime/Core/Public/Allocator/LinearHeap.h"
#    include "Runtime/Core/Public/Meta/PointerWFlags.h"
#    include "Runtime/Core/Public/Container/AssociativeVector.h"
#    include "Runtime/Core/Public/Container/HashTable.h"
#    include "Runtime/Core/Public/IO/StringBuilder.h"
#    include "Runtime/Core/Public/Memory/MemoryStream.h"
#    include "Runtime/Core/Public/Container/RawStorage.h"
#    include "Runtime/Core/Public/Maths/ScalarVector.h"
#    include "Runtime/Core/Public/IO/Filename.h"
#    include "Runtime/Core/Public/IO/Dirpath.h"
#    include "Runtime/Core/Public/Maths/PrimeNumbers.h"
#elif defined(BUILD_Win32_Final) || defined(BUILD_Win64_Final)
#    include "Runtime/Core/Public/Meta/Iterator.h"
#    include "Runtime/Core/Public/Allocator/Allocation.h"
#    include "Runtime/Core/Public/Allocator/Alloca.h"
#    include "Runtime/Core/Public/Memory/MemoryView.h"
#    include "Runtime/Core/Public/Memory/RefPtr.h"
#    include "Runtime/Core/Public/Memory/MemoryDomain.h"
#    include "Runtime/Core/Public/HAL/PlatformMemory.h"
#    include "Runtime/Core/Public/Container/BitMask.h"
#    include "Runtime/Core/Public/HAL/PlatformMaths.h"
#    include "Runtime/Core/Public/Meta/AlignedStorage.h"
#    include "Runtime/Core/Public/Allocator/Mallocator.h"
#    include "Runtime/Core/Public/Memory/MemoryTracking.h"
#    include "Runtime/Core/Public/IO/StreamProvider.h"
#    include "Runtime/Core/Public/IO/StringView.h"
#    include "Runtime/Core/Public/IO/String.h"
#    include "Runtime/Core/Public/Container/Pair.h"
#    include "Runtime/Core/Public/Container/Vector.h"
#    include "Runtime/Core/Public/Diagnostic/Logger.h"
#    include "Runtime/Core/Public/Time/Timestamp.h"
#    include "Runtime/Core/Public/Thread/ReadWriteLock.h"
#    include "Runtime/Core/Public/HAL/PlatformProcess.h"
#    include "Runtime/Core/Public/Memory/UniqueView.h"
#    include "Runtime/Core/Public/IO/FormatHelpers.h"
#    include "Runtime/Core/Public/IO/TextWriter.h"
#    include "Runtime/Core/Public/Misc/Function.h"
#    include "Runtime/Core/Public/Container/Tuple.h"
#    include "Runtime/Core/Public/Allocator/LinearHeap.h"
#    include "Runtime/Core/Public/Meta/PointerWFlags.h"
#    include "Runtime/Core/Public/Container/AssociativeVector.h"
#    include "Runtime/Core/Public/Container/HashTable.h"
#    include "Runtime/Core/Public/IO/Filename.h"
#    include "Runtime/Core/Public/IO/Dirpath.h"
#    include "Runtime/Core/Public/IO/StringBuilder.h"
#    include "Runtime/Core/Public/Memory/MemoryStream.h"
#    include "Runtime/Core/Public/Container/RawStorage.h"
#    include "Runtime/Core/Public/Maths/PrimeNumbers.h"
#    include "Runtime/Core/Public/IO/Format.h"
#else
#     error "unknown build config"
#endif

