/*
// Generated by PCHRefactor.rb v1.1 for target <Tools/UnitTest>
//------------------------------------------------------------------------------
// Date : 2018-09-05 21:24:41 UTC
*/

//                                           Target | STD | SDK | PRJ | SRC
// ------------------------------------------------------------------------
//                       Tools/UnitTest-Win32-Debug |  54 |   3 |  28 |  12
//                   Tools/UnitTest-Win32-FastDebug |  54 |   3 |  28 |  12
//                     Tools/UnitTest-Win32-Release |  54 |   3 |  28 |  12
//                   Tools/UnitTest-Win32-Profiling |  54 |   3 |  28 |  12
//                       Tools/UnitTest-Win32-Final |  54 |   3 |  24 |  12
//                       Tools/UnitTest-Win64-Debug |  54 |   3 |  28 |  12
//                   Tools/UnitTest-Win64-FastDebug |  54 |   3 |  28 |  12
//                     Tools/UnitTest-Win64-Release |  54 |   3 |  28 |  12
//                   Tools/UnitTest-Win64-Profiling |  54 |   3 |  28 |  12
//                       Tools/UnitTest-Win64-Final |  54 |   3 |  24 |  12

/*
// Standard headers
//------------------------------------------------------------------------------
*/
#if 0 // dummy
#elif defined(BUILDCONFIG_Win32_Debug) || defined(BUILDCONFIG_Win32_FastDebug) || defined(BUILDCONFIG_Win32_Release) || defined(BUILDCONFIG_Win32_Profiling) || defined(BUILDCONFIG_Win64_Debug) || defined(BUILDCONFIG_Win64_FastDebug) || defined(BUILDCONFIG_Win64_Release) || defined(BUILDCONFIG_Win64_Profiling)
#    include <algorithm>
#    include <cstdint>
#    include <cstdlib>
#    include <limits>
#    include <cfloat>
#    include <climits>
#    include <cmath>
#    include <cwchar>
#    include <cstddef>
#    include <initializer_list>
#    include <new>
#    include <exception>
#    include <type_traits>
#    include <utility>
#    include <iosfwd>
#    include <cstdio>
#    include <cstring>
#    include <atomic>
#    include <memory>
#    include <typeinfo>
#    include <functional>
#    include <tuple>
#    include <unordered_map>
#    include <list>
#    include <stdexcept>
#    include <vector>
#    include <iterator>
#    include <istream>
#    include <ostream>
#    include <ios>
#    include <streambuf>
#    include <system_error>
#    include <cerrno>
#    include <mutex>
#    include <chrono>
#    include <ratio>
#    include <thread>
#    include <cctype>
#    include <cwctype>
#    include <locale>
#    include <string>
#    include <ctime>
#    include <optional>
#    include <iostream>
#    include <clocale>
#    include <cassert>
#    include <regex>
#    include <condition_variable>
#    include <queue>
#    include <deque>
#    include <cstdarg>
#    include <bitset>
#    include <random>
#    include <unordered_set>
#elif defined(BUILDCONFIG_Win32_Final) || defined(BUILDCONFIG_Win64_Final)
#    include <algorithm>
#    include <cstdint>
#    include <cstdlib>
#    include <limits>
#    include <cfloat>
#    include <climits>
#    include <cmath>
#    include <cwchar>
#    include <cstddef>
#    include <initializer_list>
#    include <new>
#    include <exception>
#    include <type_traits>
#    include <utility>
#    include <iosfwd>
#    include <cstdio>
#    include <cstring>
#    include <atomic>
#    include <memory>
#    include <typeinfo>
#    include <functional>
#    include <tuple>
#    include <unordered_map>
#    include <list>
#    include <stdexcept>
#    include <vector>
#    include <iterator>
#    include <istream>
#    include <ostream>
#    include <ios>
#    include <streambuf>
#    include <system_error>
#    include <cerrno>
#    include <mutex>
#    include <chrono>
#    include <ratio>
#    include <thread>
#    include <cctype>
#    include <cwctype>
#    include <locale>
#    include <string>
#    include <ctime>
#    include <iostream>
#    include <clocale>
#    include <cassert>
#    include <regex>
#    include <condition_variable>
#    include <queue>
#    include <deque>
#    include <optional>
#    include <cstdarg>
#    include <bitset>
#    include <random>
#    include <unordered_set>
#else
#     error "unknown build config"
#endif

/*
// SDK headers
//------------------------------------------------------------------------------
*/
#include <SDKDDKVer.h>
#include <tchar.h>
#include <shellapi.h>

/*
// Project headers
//------------------------------------------------------------------------------
*/
#if 0 // dummy
#elif defined(BUILDCONFIG_Win32_Debug) || defined(BUILDCONFIG_Win32_FastDebug) || defined(BUILDCONFIG_Win32_Release) || defined(BUILDCONFIG_Win32_Profiling) || defined(BUILDCONFIG_Win64_Debug) || defined(BUILDCONFIG_Win64_FastDebug) || defined(BUILDCONFIG_Win64_Release) || defined(BUILDCONFIG_Win64_Profiling)
#    include "Runtime/Core/Public/HAL/PlatformIncludes.h"
#    include "Runtime/Core/Public/Core.h"
#    include "Runtime/Core/Public/Memory/MemoryView.h"
#    include "Runtime/Core/Public/Allocator/Alloca.h"
#    include "Runtime/Core/Public/Memory/RefPtr.h"
#    include "Runtime/Core/Public/Memory/MemoryDomain.h"
#    include "Runtime/Core/Public/Memory/MemoryTracking.h"
#    include "Runtime/Core/Public/HAL/PlatformMemory.h"
#    include "Runtime/Core/Public/Thread/ThreadContext.h"
#    include "Runtime/Core/Public/Diagnostic/Logger.h"
#    include "Runtime/Core/Public/IO/Format.h"
#    include "Runtime/Core/Public/IO/TextWriter.h"
#    include "Runtime/Core/Public/IO/StringView.h"
#    include "Runtime/Core/Public/IO/StreamProvider.h"
#    include "Runtime/Core/Public/Misc/Function.h"
#    include "Runtime/Core/Public/IO/FormatHelpers.h"
#    include "Runtime/Core/Public/HAL/PlatformMaths.h"
#    include "Runtime/Core/Public/Allocator/Mallocator.h"
#    include "Runtime/Core/Public/Container/Pair.h"
#    include "Runtime/Core/Public/IO/String.h"
#    include "Runtime/Core/Public/Container/Vector.h"
#    include "Runtime/Core/Public/IO/Dirpath.h"
#    include "Runtime/Core/Public/IO/Filename.h"
#    include "Runtime/Core/Public/IO/StringBuilder.h"
#    include "Runtime/Core/Public/Memory/MemoryStream.h"
#    include "Runtime/Core/Public/Container/RawStorage.h"
#    include "Runtime/Core/Public/Container/Stack.h"
#    include "Runtime/Core/Public/Container/AssociativeVector.h"
#elif defined(BUILDCONFIG_Win32_Final) || defined(BUILDCONFIG_Win64_Final)
#    include "Runtime/Core/Public/HAL/PlatformIncludes.h"
#    include "Runtime/Core/Public/Core.h"
#    include "Runtime/Core/Public/Memory/MemoryView.h"
#    include "Runtime/Core/Public/Allocator/Alloca.h"
#    include "Runtime/Core/Public/Memory/RefPtr.h"
#    include "Runtime/Core/Public/Memory/MemoryDomain.h"
#    include "Runtime/Core/Public/Memory/MemoryTracking.h"
#    include "Runtime/Core/Public/HAL/PlatformMemory.h"
#    include "Runtime/Core/Public/Thread/ThreadContext.h"
#    include "Runtime/Core/Public/Diagnostic/Logger.h"
#    include "Runtime/Core/Public/HAL/PlatformMaths.h"
#    include "Runtime/Core/Public/IO/TextWriter.h"
#    include "Runtime/Core/Public/IO/StringView.h"
#    include "Runtime/Core/Public/IO/StreamProvider.h"
#    include "Runtime/Core/Public/Misc/Function.h"
#    include "Runtime/Core/Public/Allocator/Mallocator.h"
#    include "Runtime/Core/Public/Container/Pair.h"
#    include "Runtime/Core/Public/IO/String.h"
#    include "Runtime/Core/Public/IO/Format.h"
#    include "Runtime/Core/Public/IO/StringBuilder.h"
#    include "Runtime/Core/Public/Memory/MemoryStream.h"
#    include "Runtime/Core/Public/Container/RawStorage.h"
#    include "Runtime/Core/Public/Container/Vector.h"
#    include "Runtime/Core/Public/Container/Stack.h"
#else
#     error "unknown build config"
#endif

