/*
** Generated by ppe v1.1
*/
#ifdef PLATFORM_WINDOWS
// Global system includes
#include <algorithm>
#include <stdint.h>
#include <limits.h>
#include <limits>
#include <initializer_list>
#include <new>
#include <exception>
#include <type_traits>
#include <utility>
#include <atomic>
#include <memory>
#include <functional>
#include <tuple>
#include <cmath>
#include <list>
#include <stdexcept>
#include <iterator>
#include <mutex>
#include <chrono>
#include <cctype>
#include <clocale>
#include <thread>
#include <array>
#include <comdef.h>
#include <comutil.h>
#include <emmintrin.h>
#include <xmmintrin.h>
#include <intrin.h>
#include <immintrin.h>
#include <smmintrin.h>
#include <tmmintrin.h>
#include <pmmintrin.h>
#include <cwctype>
#include <locale>
#include <variant>
#include <optional>
// Global project includes
#ifdef BUILD_Win32_FastDebug
// system includes
#include <iostream>
#include <regex>
#include <condition_variable>
// project includes
#include "winnt_version.h"
#include "Runtime/Core/Public/Meta/Aliases.h"
#include "Runtime/Core/Public/HAL/PlatformMacros.h"
#endif // BUILD_Win32_FastDebug
#ifdef BUILD_Win64_FastDebug
// system includes
#include <iostream>
#include <regex>
#include <condition_variable>
// project includes
#include "winnt_version.h"
#include "Runtime/Core/Public/Meta/Aliases.h"
#include "Runtime/Core/Public/HAL/PlatformMacros.h"
#endif // BUILD_Win64_FastDebug
#endif //! PLATFORM_WINDOWS
