/*
// Generated by PCHRefactor.rb v1.0 for target <Core.ContentPipeline>
//------------------------------------------------------------------------------
// Date : 2017-08-21 12:33:32 UTC
*/

// Processed dependencies for Core.ContentPipeline-Win32-Debug : 44 std, 39 sdk, 123 prj, 9 src
// Processed dependencies for Core.ContentPipeline-Win32-FastDebug : 44 std, 39 sdk, 123 prj, 9 src
// Processed dependencies for Core.ContentPipeline-Win32-Release : 44 std, 39 sdk, 122 prj, 9 src
// Processed dependencies for Core.ContentPipeline-Win32-Profiling : 44 std, 39 sdk, 122 prj, 9 src
// Processed dependencies for Core.ContentPipeline-Win32-Final : 44 std, 39 sdk, 122 prj, 9 src
// Processed dependencies for Core.ContentPipeline-Win64-Debug : 44 std, 38 sdk, 123 prj, 9 src
// Processed dependencies for Core.ContentPipeline-Win64-FastDebug : 44 std, 38 sdk, 123 prj, 9 src
// Processed dependencies for Core.ContentPipeline-Win64-Release : 44 std, 38 sdk, 122 prj, 9 src
// Processed dependencies for Core.ContentPipeline-Win64-Profiling : 44 std, 38 sdk, 122 prj, 9 src
// Processed dependencies for Core.ContentPipeline-Win64-Final : 44 std, 38 sdk, 122 prj, 9 src

/*
// Standard headers
//------------------------------------------------------------------------------
*/
#include <algorithm>
#include <cstdint>
#include <cstdlib>
#include <limits>
#include <cfloat>
#include <climits>
#include <cmath>
#include <cwchar>
#include <cstddef>
#include <initializer_list>
#include <new>
#include <exception>
#include <type_traits>
#include <utility>
#include <iosfwd>
#include <cstdio>
#include <cstring>
#include <atomic>
#include <memory>
#include <typeinfo>
#include <functional>
#include <tuple>
#include <stdexcept>
#include <iomanip>
#include <istream>
#include <ostream>
#include <ios>
#include <streambuf>
#include <system_error>
#include <cerrno>
#include <ctime>
#include <iterator>
#include <mutex>
#include <chrono>
#include <ratio>
#include <thread>
#include <cctype>
#include <cwctype>
#include <locale>
#include <string>
#include <iostream>
#include <sstream>
#include <regex>
#include <vector>

/*
// SDK headers
//------------------------------------------------------------------------------
*/
#if 0 // dummy
#elif defined(BUILDCONFIG_Win32_Debug) || defined(BUILDCONFIG_Win32_FastDebug) || defined(BUILDCONFIG_Win32_Release) || defined(BUILDCONFIG_Win32_Profiling) || defined(BUILDCONFIG_Win32_Final)
#    include "excpt.h"
#    include "vcruntime.h"
#    include "sal.h"
#    include "ConcurrencySal.h"
#    include "vadefs.h"
#    include "stdarg.h"
#    include "vcruntime_string.h"
#    include "yvals.h"
#    include "xkeycheck.h"
#    include "crtdefs.h"
#    include "use_ansi.h"
#    include "stdint.h"
#    include "limits.h"
#    include "ymath.h"
#    include "xtgmath.h"
#    include "vcruntime_new.h"
#    include "vcruntime_new_debug.h"
#    include "xatomic0.h"
#    include "intrin0.h"
#    include "xatomic.h"
#    include "vcruntime_typeinfo.h"
#    include "vcruntime_exception.h"
#    include "eh.h"
#    include "intrin.h"
#    include "setjmp.h"
#    include "immintrin.h"
#    include "wmmintrin.h"
#    include "nmmintrin.h"
#    include "smmintrin.h"
#    include "tmmintrin.h"
#    include "pmmintrin.h"
#    include "emmintrin.h"
#    include "xmmintrin.h"
#    include "mmintrin.h"
#    include "zmmintrin.h"
#    include "ammintrin.h"
#    include "mm3dnow.h"
#    include "xlocinfo.h"
#    include "xstring_insert.h"
#elif defined(BUILDCONFIG_Win64_Debug) || defined(BUILDCONFIG_Win64_FastDebug) || defined(BUILDCONFIG_Win64_Release) || defined(BUILDCONFIG_Win64_Profiling) || defined(BUILDCONFIG_Win64_Final)
#    include "excpt.h"
#    include "vcruntime.h"
#    include "sal.h"
#    include "ConcurrencySal.h"
#    include "vadefs.h"
#    include "stdarg.h"
#    include "vcruntime_string.h"
#    include "yvals.h"
#    include "xkeycheck.h"
#    include "crtdefs.h"
#    include "use_ansi.h"
#    include "stdint.h"
#    include "limits.h"
#    include "ymath.h"
#    include "xtgmath.h"
#    include "vcruntime_new.h"
#    include "vcruntime_new_debug.h"
#    include "xatomic0.h"
#    include "intrin0.h"
#    include "xatomic.h"
#    include "vcruntime_typeinfo.h"
#    include "vcruntime_exception.h"
#    include "eh.h"
#    include "intrin.h"
#    include "setjmp.h"
#    include "immintrin.h"
#    include "wmmintrin.h"
#    include "nmmintrin.h"
#    include "smmintrin.h"
#    include "tmmintrin.h"
#    include "pmmintrin.h"
#    include "emmintrin.h"
#    include "xmmintrin.h"
#    include "mmintrin.h"
#    include "zmmintrin.h"
#    include "ammintrin.h"
#    include "xlocinfo.h"
#    include "xstring_insert.h"
#else
#     error "unknown build config"
#endif

/*
// Project headers
//------------------------------------------------------------------------------
*/
#if 0 // dummy
#elif defined(BUILDCONFIG_Win32_Debug) || defined(BUILDCONFIG_Win32_FastDebug) || defined(BUILDCONFIG_Win64_Debug) || defined(BUILDCONFIG_Win64_FastDebug)
#    include "Core/Misc/Platform_Windows.h"
#    include "Core.ContentPipeline/ContentPipeline.h"
#    include "Core/Core.h"
#    include "Core/Meta/Aliases.h"
#    include "Core/Meta/Alignment.h"
#    include "Core/Meta/TypeTraits.h"
#    include "Core/Meta/Assert.h"
#    include "Core/Diagnostic/Exception.h"
#    include "Core/Meta/BitCount.h"
#    include "Core/Meta/Cast.h"
#    include "Core/Meta/TypeHash.h"
#    include "Core/Meta/Hash_fwd.h"
#    include "Core/Meta/Delete.h"
#    include "Core/Meta/Enum.h"
#    include "Core/Meta/ForRange.h"
#    include "Core/Meta/Iterator.h"
#    include "Core/Meta/Warnings.h"
#    include "Core/Meta/NumericLimits.h"
#    include "Core/Meta/OneTimeInitialize.h"
#    include "Core/Meta/StronglyTyped.h"
#    include "Core/Meta/ThreadResource.h"
#    include "Core/Allocator/PoolAllocatorTag.h"
#    include "Core/Memory/MemoryDomain.h"
#    include "Core/IO/FileSystem_fwd.h"
#    include "Core/IO/FS/FileSystemToken_fwd.h"
#    include "Core/IO/FS/FileSystemProperties.h"
#    include "Core/Allocator/Allocation.h"
#    include "Core/Allocator/Alloca.h"
#    include "Core/Memory/MemoryView.h"
#    include "Core/Memory/UniquePtr.h"
#    include "Core/Memory/RefPtr.h"
#    include "Core/Allocator/BuddyAllocator.h"
#    include "Core/Allocator/AllocatorBase.h"
#    include "Core/Allocator/BuddyHeap.h"
#    include "Core/Allocator/HeapAllocator.h"
#    include "Core/Allocator/Heap.h"
#    include "Core/Memory/AlignedStorage.h"
#    include "Core/Memory/MemoryTracking.h"
#    include "Core/IO/FormatHelpers.h"
#    include "Core/IO/StringView.h"
#    include "Core/Container/Hash.h"
#    include "Core/Memory/HashFunctions.h"
#    include "Core/Meta/Singleton.h"
#    include "Core/Allocator/Mallocator.h"
#    include "Core/Allocator/Malloc.h"
#    include "Core/Allocator/New.h"
#    include "Core/Allocator/PoolAllocator.h"
#    include "Core/Allocator/ThreadLocalAllocator.h"
#    include "Core/Allocator/TrackingAllocator.h"
#    include "Core/IO/FS/Filename.h"
#    include "Core/IO/FS/Basename.h"
#    include "Core/IO/FS/BasenameNoExt.h"
#    include "Core/IO/FS/FileSystemToken.h"
#    include "Core/Container/Token.h"
#    include "Core/Container/HashSet.h"
#    include "Core/Container/HashTable.h"
#    include "Core/Container/Pair.h"
#    include "Core/Container/Stack.h"
#    include "Core/IO/FS/Extname.h"
#    include "Core/IO/String.h"
#    include "Core/IO/Stream.h"
#    include "Core/Memory/UniqueView.h"
#    include "Core/IO/FS/Dirpath.h"
#    include "Core/IO/FS/Dirname.h"
#    include "Core/IO/FS/MountingPoint.h"
#    include "Core.RTTI/RTTI_Namespace.h"
#    include "Core.RTTI/RTTI.h"
#    include "Core.RTTI/RTTI_fwd.h"
#    include "Core.RTTI/MetaObjectHelpers.h"
#    include "Core.RTTI/RTTI_Macros.h"
#    include "Core.RTTI/MetaClass.h"
#    include "Core.RTTI/Typedefs.h"
#    include "Core/Container/AssociativeVector.h"
#    include "Core/Container/Vector.h"
#    include "Core/Allocator/InSituAllocator.h"
#    include "Core/Container/RawStorage.h"
#    include "Core/Maths/ScalarVector_fwd.h"
#    include "Core/Maths/ScalarMatrix_fwd.h"
#    include "Core.RTTI/MetaNamespace.h"
#    include "Core/Container/HashMap.h"
#    include "Core/Container/IntrusiveList.h"
#    include "Core/Thread/AtomicSpinLock.h"
#    include "Core.RTTI/MetaObject.h"
#    include "Core.RTTI/MetaType.h"
#    include "Core/IO/Format.h"
#    include "Core.RTTI/MetaTypeVirtualTraits.h"
#    include "Core.RTTI/RTTI_Macros-impl.h"
#    include "Core.RTTI/MetaTypePromote.h"
#    include "Core.RTTI/MetaTypeTraits.h"
#    include "Core/Color/Color.h"
#    include "Core/Color/Color_fwd.h"
#    include "Core/Container/Token_fwd.h"
#    include "Core/Maths/ScalarBoundingBox_fwd.h"
#    include "Core/Maths/PackedVectors.h"
#    include "Core/Maths/Packing_fwd.h"
#    include "Core/Maths/PackingHelpers.h"
#    include "Core/Maths/MathHelpers.h"
#    include "Core/Maths/ScalarVector.h"
#    include "Core/Maths/ScalarVectorHelpers.h"
#    include "Core/Misc/Endianness.h"
#    include "Core/Misc/TargetPlatform.h"
#    include "Core/Time/DateTime.h"
#    include "Core/Time/Timestamp.h"
#    include "Core.RTTI/MetaAtom.h"
#    include "Core.RTTI/MetaAtomVisitor.h"
#    include "Core/Maths/ScalarMatrix.h"
#    include "Core/Allocator/PoolAllocator-impl.h"
#    include "Core/Memory/SegregatedMemoryPool.h"
#    include "Core/Memory/MemoryPool.h"
#    include "Core/Meta/AutoSingleton.h"
#    include "Core/Diagnostic/Logger.h"
#    include "Core.RTTI/MetaFunction.h"
#    include "Core/Container/BitSet.h"
#    include "Core/Meta/BitField.h"
#    include "Core/Container/Tuple.h"
#    include "Core.RTTI/MetaProperty.h"
#    include "Core.RTTI/MetaPropertyAccessor.h"
#    include "Core.RTTI/Exceptions.h"
#    include "Core/Meta/Delegate.h"
#    include "Core/Meta/PointerWFlags.h"
#    include "Core.RTTI/RTTI_extern.h"
#    include "Core.ContentPipeline/ContentIdentity.h"
#    include "Core.ContentPipeline/ContentPipelineNode.h"
#elif defined(BUILDCONFIG_Win32_Release) || defined(BUILDCONFIG_Win32_Profiling) || defined(BUILDCONFIG_Win32_Final) || defined(BUILDCONFIG_Win64_Release) || defined(BUILDCONFIG_Win64_Profiling) || defined(BUILDCONFIG_Win64_Final)
#    include "Core/Misc/Platform_Windows.h"
#    include "Core.ContentPipeline/ContentPipeline.h"
#    include "Core/Core.h"
#    include "Core/Meta/Aliases.h"
#    include "Core/Meta/Alignment.h"
#    include "Core/Meta/TypeTraits.h"
#    include "Core/Meta/Assert.h"
#    include "Core/Diagnostic/Exception.h"
#    include "Core/Meta/BitCount.h"
#    include "Core/Meta/Cast.h"
#    include "Core/Meta/TypeHash.h"
#    include "Core/Meta/Hash_fwd.h"
#    include "Core/Meta/Delete.h"
#    include "Core/Meta/Enum.h"
#    include "Core/Meta/ForRange.h"
#    include "Core/Meta/Iterator.h"
#    include "Core/Meta/Warnings.h"
#    include "Core/Meta/NumericLimits.h"
#    include "Core/Meta/OneTimeInitialize.h"
#    include "Core/Meta/StronglyTyped.h"
#    include "Core/Meta/ThreadResource.h"
#    include "Core/Allocator/PoolAllocatorTag.h"
#    include "Core/Memory/MemoryDomain.h"
#    include "Core/IO/FileSystem_fwd.h"
#    include "Core/IO/FS/FileSystemToken_fwd.h"
#    include "Core/IO/FS/FileSystemProperties.h"
#    include "Core/Allocator/Allocation.h"
#    include "Core/Allocator/Alloca.h"
#    include "Core/Memory/MemoryView.h"
#    include "Core/Memory/UniquePtr.h"
#    include "Core/Memory/RefPtr.h"
#    include "Core/Allocator/BuddyAllocator.h"
#    include "Core/Allocator/AllocatorBase.h"
#    include "Core/Allocator/BuddyHeap.h"
#    include "Core/Allocator/HeapAllocator.h"
#    include "Core/Allocator/Heap.h"
#    include "Core/Memory/AlignedStorage.h"
#    include "Core/Memory/MemoryTracking.h"
#    include "Core/IO/FormatHelpers.h"
#    include "Core/IO/StringView.h"
#    include "Core/Container/Hash.h"
#    include "Core/Memory/HashFunctions.h"
#    include "Core/Meta/Singleton.h"
#    include "Core/Allocator/Mallocator.h"
#    include "Core/Allocator/Malloc.h"
#    include "Core/Allocator/New.h"
#    include "Core/Allocator/PoolAllocator.h"
#    include "Core/Allocator/ThreadLocalAllocator.h"
#    include "Core/Allocator/TrackingAllocator.h"
#    include "Core/IO/FS/Filename.h"
#    include "Core/IO/FS/Basename.h"
#    include "Core/IO/FS/BasenameNoExt.h"
#    include "Core/IO/FS/FileSystemToken.h"
#    include "Core/Container/Token.h"
#    include "Core/Container/HashSet.h"
#    include "Core/Container/HashTable.h"
#    include "Core/Container/Pair.h"
#    include "Core/Container/Stack.h"
#    include "Core/IO/FS/Extname.h"
#    include "Core/IO/String.h"
#    include "Core/IO/Stream.h"
#    include "Core/Memory/UniqueView.h"
#    include "Core/IO/FS/Dirpath.h"
#    include "Core/IO/FS/Dirname.h"
#    include "Core/IO/FS/MountingPoint.h"
#    include "Core.RTTI/RTTI_Namespace.h"
#    include "Core.RTTI/RTTI.h"
#    include "Core.RTTI/RTTI_fwd.h"
#    include "Core.RTTI/MetaObjectHelpers.h"
#    include "Core.RTTI/RTTI_Macros.h"
#    include "Core.RTTI/MetaClass.h"
#    include "Core.RTTI/Typedefs.h"
#    include "Core/Container/AssociativeVector.h"
#    include "Core/Container/Vector.h"
#    include "Core/Allocator/InSituAllocator.h"
#    include "Core/Container/RawStorage.h"
#    include "Core/Maths/ScalarVector_fwd.h"
#    include "Core/Maths/ScalarMatrix_fwd.h"
#    include "Core.RTTI/MetaNamespace.h"
#    include "Core/Container/HashMap.h"
#    include "Core/Container/IntrusiveList.h"
#    include "Core/Thread/AtomicSpinLock.h"
#    include "Core.RTTI/MetaObject.h"
#    include "Core.RTTI/MetaType.h"
#    include "Core/IO/Format.h"
#    include "Core.RTTI/MetaTypeVirtualTraits.h"
#    include "Core.RTTI/RTTI_Macros-impl.h"
#    include "Core.RTTI/MetaTypePromote.h"
#    include "Core.RTTI/MetaTypeTraits.h"
#    include "Core/Color/Color.h"
#    include "Core/Color/Color_fwd.h"
#    include "Core/Container/Token_fwd.h"
#    include "Core/Maths/ScalarBoundingBox_fwd.h"
#    include "Core/Maths/PackedVectors.h"
#    include "Core/Maths/Packing_fwd.h"
#    include "Core/Maths/PackingHelpers.h"
#    include "Core/Maths/MathHelpers.h"
#    include "Core/Maths/ScalarVector.h"
#    include "Core/Maths/ScalarVectorHelpers.h"
#    include "Core/Misc/Endianness.h"
#    include "Core/Misc/TargetPlatform.h"
#    include "Core/Time/DateTime.h"
#    include "Core/Time/Timestamp.h"
#    include "Core.RTTI/MetaAtom.h"
#    include "Core.RTTI/MetaAtomVisitor.h"
#    include "Core/Maths/ScalarMatrix.h"
#    include "Core/Allocator/PoolAllocator-impl.h"
#    include "Core/Memory/SegregatedMemoryPool.h"
#    include "Core/Memory/MemoryPool.h"
#    include "Core/Meta/AutoSingleton.h"
#    include "Core.RTTI/MetaFunction.h"
#    include "Core/Container/BitSet.h"
#    include "Core/Meta/BitField.h"
#    include "Core/Container/Tuple.h"
#    include "Core.RTTI/MetaProperty.h"
#    include "Core.RTTI/MetaPropertyAccessor.h"
#    include "Core.RTTI/Exceptions.h"
#    include "Core/Meta/Delegate.h"
#    include "Core/Meta/PointerWFlags.h"
#    include "Core.RTTI/RTTI_extern.h"
#    include "Core.ContentPipeline/ContentIdentity.h"
#    include "Core.ContentPipeline/ContentPipelineNode.h"
#else
#     error "unknown build config"
#endif

