/*
// Generated by PCHRefactor.rb v1.0 for target <core>
//------------------------------------------------------------------------------
// Date : 2018-02-18 13:32:12 UTC
*/

// Processed dependencies for core-Win32-Debug : 49 std, 7 sdk, 40 prj, 109 src
// Processed dependencies for core-Win32-FastDebug : 49 std, 7 sdk, 40 prj, 109 src
// Processed dependencies for core-Win32-Release : 49 std, 7 sdk, 38 prj, 109 src
// Processed dependencies for core-Win32-Profiling : 49 std, 7 sdk, 35 prj, 109 src
// Processed dependencies for core-Win32-Final : 47 std, 7 sdk, 35 prj, 109 src
// Processed dependencies for core-Win64-Debug : 49 std, 7 sdk, 40 prj, 109 src
// Processed dependencies for core-Win64-FastDebug : 49 std, 7 sdk, 40 prj, 109 src
// Processed dependencies for core-Win64-Release : 49 std, 7 sdk, 38 prj, 109 src
// Processed dependencies for core-Win64-Profiling : 49 std, 7 sdk, 35 prj, 109 src
// Processed dependencies for core-Win64-Final : 47 std, 7 sdk, 35 prj, 109 src

/*
// Standard headers
//------------------------------------------------------------------------------
*/
#if 0 // dummy
#elif defined(BUILDCONFIG_Win32_Debug) || defined(BUILDCONFIG_Win32_FastDebug) || defined(BUILDCONFIG_Win32_Release) || defined(BUILDCONFIG_Win32_Profiling) || defined(BUILDCONFIG_Win64_Debug) || defined(BUILDCONFIG_Win64_FastDebug) || defined(BUILDCONFIG_Win64_Release) || defined(BUILDCONFIG_Win64_Profiling)
#    include <algorithm>
#    include <cstdint>
#    include <cstdlib>
#    include <limits>
#    include <cfloat>
#    include <climits>
#    include <cmath>
#    include <cwchar>
#    include <cstddef>
#    include <initializer_list>
#    include <new>
#    include <exception>
#    include <type_traits>
#    include <utility>
#    include <iosfwd>
#    include <cstdio>
#    include <cstring>
#    include <atomic>
#    include <memory>
#    include <typeinfo>
#    include <functional>
#    include <tuple>
#    include <unordered_map>
#    include <list>
#    include <stdexcept>
#    include <vector>
#    include <iterator>
#    include <istream>
#    include <ostream>
#    include <ios>
#    include <streambuf>
#    include <system_error>
#    include <cerrno>
#    include <mutex>
#    include <chrono>
#    include <ratio>
#    include <thread>
#    include <cctype>
#    include <cwctype>
#    include <locale>
#    include <string>
#    include <ctime>
#    include <optional>
#    include <iostream>
#    include <cassert>
#    include <regex>
#    include <condition_variable>
#    include <queue>
#    include <deque>
#elif defined(BUILDCONFIG_Win32_Final) || defined(BUILDCONFIG_Win64_Final)
#    include <algorithm>
#    include <cstdint>
#    include <cstdlib>
#    include <limits>
#    include <cfloat>
#    include <climits>
#    include <cmath>
#    include <cwchar>
#    include <cstddef>
#    include <initializer_list>
#    include <new>
#    include <exception>
#    include <type_traits>
#    include <utility>
#    include <iosfwd>
#    include <cstdio>
#    include <cstring>
#    include <atomic>
#    include <memory>
#    include <typeinfo>
#    include <functional>
#    include <tuple>
#    include <unordered_map>
#    include <list>
#    include <stdexcept>
#    include <vector>
#    include <iterator>
#    include <istream>
#    include <ostream>
#    include <ios>
#    include <streambuf>
#    include <system_error>
#    include <cerrno>
#    include <mutex>
#    include <chrono>
#    include <ratio>
#    include <thread>
#    include <cctype>
#    include <cwctype>
#    include <locale>
#    include <string>
#    include <ctime>
#    include <cassert>
#    include <regex>
#    include <condition_variable>
#    include <queue>
#    include <deque>
#else
#     error "unknown build config"
#endif

/*
// SDK headers
//------------------------------------------------------------------------------
*/
#include "limits.h"
#include "stdint.h"
#include "intrin.h"
#include "immintrin.h"
#include "nmmintrin.h"
#include "pmmintrin.h"
#include "emmintrin.h"

/*
// Project headers
//------------------------------------------------------------------------------
*/
#if 0 // dummy
#elif defined(BUILDCONFIG_Win32_Debug) || defined(BUILDCONFIG_Win32_FastDebug) || defined(BUILDCONFIG_Win64_Debug) || defined(BUILDCONFIG_Win64_FastDebug)
#    include "Core/Misc/Platform_Windows.h"
#    include "Core/Core.h"
#    include "Core/Meta/Config.h"
#    include "Core/Meta/Aliases.h"
#    include "Core/Meta/Alignment.h"
#    include "Core/Meta/TypeTraits.h"
#    include "Core/Meta/Assert.h"
#    include "Core/Diagnostic/Exception.h"
#    include "Core/IO/TextWriter_fwd.h"
#    include "Core/Meta/BitCount.h"
#    include "Core/Meta/Cast.h"
#    include "Core/Meta/TypeHash.h"
#    include "Core/Meta/Hash_fwd.h"
#    include "Core/Meta/Delete.h"
#    include "Core/Meta/Enum.h"
#    include "Core/Meta/ForRange.h"
#    include "Core/Meta/Iterator.h"
#    include "Core/Meta/Warnings.h"
#    include "Core/Meta/NumericLimits.h"
#    include "Core/Meta/OneTimeInitialize.h"
#    include "Core/Meta/StronglyTyped.h"
#    include "Core/Meta/ThreadResource.h"
#    include "Core/Allocator/Alloca.h"
#    include "Core/Memory/MemoryView.h"
#    include "Core/Memory/UniquePtr.h"
#    include "Core/Memory/RefPtr.h"
#    include "Core/Memory/MemoryDomain.h"
#    include "Core/Memory/MemoryTracking.h"
#    include "Core/Meta/Singleton.h"
#    include "Core/Meta/AlignedStorage.h"
#    include "Core/IO/StreamPolicies.h"
#    include "Core/IO/String_fwd.h"
#    include "Core/Allocator/Heap.h"
#    include "Core/Allocator/Malloc.h"
#    include "Core/Allocator/AllocatorBase.h"
#    include "Core/Allocator/ThreadLocalAllocator.h"
#    include "Core/Allocator/HeapAllocator.h"
#    include "Core/IO/StringView.h"
#    include "Core/Container/Hash.h"
#    include "Core/Memory/HashFunctions.h"
#elif defined(BUILDCONFIG_Win32_Release) || defined(BUILDCONFIG_Win64_Release)
#    include "Core/Misc/Platform_Windows.h"
#    include "Core/Core.h"
#    include "Core/Meta/Config.h"
#    include "Core/Meta/Aliases.h"
#    include "Core/Meta/Alignment.h"
#    include "Core/Meta/TypeTraits.h"
#    include "Core/Meta/Assert.h"
#    include "Core/Diagnostic/Exception.h"
#    include "Core/IO/TextWriter_fwd.h"
#    include "Core/Meta/BitCount.h"
#    include "Core/Meta/Cast.h"
#    include "Core/Meta/TypeHash.h"
#    include "Core/Meta/Hash_fwd.h"
#    include "Core/Meta/Delete.h"
#    include "Core/Meta/Enum.h"
#    include "Core/Meta/ForRange.h"
#    include "Core/Meta/Iterator.h"
#    include "Core/Meta/Warnings.h"
#    include "Core/Meta/NumericLimits.h"
#    include "Core/Meta/OneTimeInitialize.h"
#    include "Core/Meta/StronglyTyped.h"
#    include "Core/Meta/ThreadResource.h"
#    include "Core/Allocator/Alloca.h"
#    include "Core/Memory/MemoryView.h"
#    include "Core/Memory/UniquePtr.h"
#    include "Core/Memory/RefPtr.h"
#    include "Core/Memory/MemoryDomain.h"
#    include "Core/Memory/MemoryTracking.h"
#    include "Core/Meta/Singleton.h"
#    include "Core/Meta/AlignedStorage.h"
#    include "Core/IO/StreamPolicies.h"
#    include "Core/IO/String_fwd.h"
#    include "Core/Allocator/Heap.h"
#    include "Core/Allocator/Malloc.h"
#    include "Core/Allocator/AllocatorBase.h"
#    include "Core/IO/StringView.h"
#    include "Core/Container/Hash.h"
#    include "Core/Memory/HashFunctions.h"
#elif defined(BUILDCONFIG_Win32_Profiling) || defined(BUILDCONFIG_Win32_Final) || defined(BUILDCONFIG_Win64_Profiling) || defined(BUILDCONFIG_Win64_Final)
#    include "Core/Misc/Platform_Windows.h"
#    include "Core/Core.h"
#    include "Core/Meta/Config.h"
#    include "Core/Meta/Aliases.h"
#    include "Core/Meta/Alignment.h"
#    include "Core/Meta/TypeTraits.h"
#    include "Core/Meta/Assert.h"
#    include "Core/Diagnostic/Exception.h"
#    include "Core/IO/TextWriter_fwd.h"
#    include "Core/Meta/BitCount.h"
#    include "Core/Meta/Cast.h"
#    include "Core/Meta/TypeHash.h"
#    include "Core/Meta/Hash_fwd.h"
#    include "Core/Meta/Delete.h"
#    include "Core/Meta/Enum.h"
#    include "Core/Meta/ForRange.h"
#    include "Core/Meta/Iterator.h"
#    include "Core/Meta/Warnings.h"
#    include "Core/Meta/NumericLimits.h"
#    include "Core/Meta/OneTimeInitialize.h"
#    include "Core/Meta/StronglyTyped.h"
#    include "Core/Meta/ThreadResource.h"
#    include "Core/Allocator/Alloca.h"
#    include "Core/Memory/MemoryView.h"
#    include "Core/Memory/UniquePtr.h"
#    include "Core/Memory/RefPtr.h"
#    include "Core/Memory/MemoryDomain.h"
#    include "Core/Memory/MemoryTracking.h"
#    include "Core/Meta/Singleton.h"
#    include "Core/Meta/AlignedStorage.h"
#    include "Core/IO/StreamPolicies.h"
#    include "Core/IO/String_fwd.h"
#    include "Core/Memory/HashFunctions.h"
#    include "Core/Container/Hash.h"
#    include "Core/IO/StringView.h"
#else
#     error "unknown build config"
#endif

