/*
// Generated by PCHRefactor.rb v1.0 for target <Core.Serialize>
//------------------------------------------------------------------------------
// Date : 2017-09-20 01:26:08 UTC
*/

// Processed dependencies for Core.Serialize-Win32-Debug : 45 std, 40 sdk, 47 prj, 24 src
// Processed dependencies for Core.Serialize-Win32-FastDebug : 45 std, 40 sdk, 47 prj, 24 src
// Processed dependencies for Core.Serialize-Win32-Release : 45 std, 40 sdk, 47 prj, 24 src
// Processed dependencies for Core.Serialize-Win32-Profiling : 45 std, 40 sdk, 47 prj, 24 src
// Processed dependencies for Core.Serialize-Win32-Final : 45 std, 40 sdk, 47 prj, 24 src
// Processed dependencies for Core.Serialize-Win64-Debug : 45 std, 39 sdk, 47 prj, 24 src
// Processed dependencies for Core.Serialize-Win64-FastDebug : 45 std, 39 sdk, 47 prj, 24 src
// Processed dependencies for Core.Serialize-Win64-Release : 45 std, 39 sdk, 47 prj, 24 src
// Processed dependencies for Core.Serialize-Win64-Profiling : 45 std, 39 sdk, 47 prj, 24 src
// Processed dependencies for Core.Serialize-Win64-Final : 45 std, 39 sdk, 47 prj, 24 src

/*
// Standard headers
//------------------------------------------------------------------------------
*/
#include <algorithm>
#include <cstdint>
#include <cstdlib>
#include <limits>
#include <cfloat>
#include <climits>
#include <cmath>
#include <cwchar>
#include <cstddef>
#include <initializer_list>
#include <new>
#include <exception>
#include <type_traits>
#include <utility>
#include <iosfwd>
#include <cstdio>
#include <cstring>
#include <atomic>
#include <memory>
#include <typeinfo>
#include <functional>
#include <tuple>
#include <stdexcept>
#include <iomanip>
#include <istream>
#include <ostream>
#include <ios>
#include <streambuf>
#include <system_error>
#include <cerrno>
#include <ctime>
#include <iterator>
#include <mutex>
#include <chrono>
#include <ratio>
#include <thread>
#include <iostream>
#include <sstream>
#include <string>
#include <cctype>
#include <cwctype>
#include <locale>
#include <shared_mutex>
#include <condition_variable>
#include <deque>

/*
// SDK headers
//------------------------------------------------------------------------------
*/
#if 0 // dummy
#elif defined(BUILDCONFIG_Win32_Debug) || defined(BUILDCONFIG_Win32_FastDebug) || defined(BUILDCONFIG_Win32_Release) || defined(BUILDCONFIG_Win32_Profiling) || defined(BUILDCONFIG_Win32_Final)
#    include "excpt.h"
#    include "vcruntime.h"
#    include "sal.h"
#    include "concurrencysal.h"
#    include "vadefs.h"
#    include "stdarg.h"
#    include "vcruntime_string.h"
#    include "yvals.h"
#    include "xkeycheck.h"
#    include "crtdefs.h"
#    include "use_ansi.h"
#    include "stdint.h"
#    include "limits.h"
#    include "ymath.h"
#    include "xtgmath.h"
#    include "vcruntime_new.h"
#    include "vcruntime_new_debug.h"
#    include "xatomic0.h"
#    include "intrin0.h"
#    include "xatomic.h"
#    include "vcruntime_typeinfo.h"
#    include "vcruntime_exception.h"
#    include "eh.h"
#    include "intrin.h"
#    include "setjmp.h"
#    include "immintrin.h"
#    include "wmmintrin.h"
#    include "nmmintrin.h"
#    include "smmintrin.h"
#    include "tmmintrin.h"
#    include "pmmintrin.h"
#    include "emmintrin.h"
#    include "xmmintrin.h"
#    include "mmintrin.h"
#    include "zmmintrin.h"
#    include "ammintrin.h"
#    include "mm3dnow.h"
#    include "xlocinfo.h"
#    include "xcall_once.h"
#    include "xstring_insert.h"
#elif defined(BUILDCONFIG_Win64_Debug) || defined(BUILDCONFIG_Win64_FastDebug) || defined(BUILDCONFIG_Win64_Release) || defined(BUILDCONFIG_Win64_Profiling) || defined(BUILDCONFIG_Win64_Final)
#    include "excpt.h"
#    include "vcruntime.h"
#    include "sal.h"
#    include "concurrencysal.h"
#    include "vadefs.h"
#    include "stdarg.h"
#    include "vcruntime_string.h"
#    include "yvals.h"
#    include "xkeycheck.h"
#    include "crtdefs.h"
#    include "use_ansi.h"
#    include "stdint.h"
#    include "limits.h"
#    include "ymath.h"
#    include "xtgmath.h"
#    include "vcruntime_new.h"
#    include "vcruntime_new_debug.h"
#    include "xatomic0.h"
#    include "intrin0.h"
#    include "xatomic.h"
#    include "vcruntime_typeinfo.h"
#    include "vcruntime_exception.h"
#    include "eh.h"
#    include "intrin.h"
#    include "setjmp.h"
#    include "immintrin.h"
#    include "wmmintrin.h"
#    include "nmmintrin.h"
#    include "smmintrin.h"
#    include "tmmintrin.h"
#    include "pmmintrin.h"
#    include "emmintrin.h"
#    include "xmmintrin.h"
#    include "mmintrin.h"
#    include "zmmintrin.h"
#    include "ammintrin.h"
#    include "xlocinfo.h"
#    include "xcall_once.h"
#    include "xstring_insert.h"
#else
#     error "unknown build config"
#endif

/*
// Project headers
//------------------------------------------------------------------------------
*/
#include "Core/Misc/Platform_Windows.h" // 104% 25/24
#include "Core.Serialize/Serialize.h" // 104% 25/24
#include "Core/Core.h" // 104% 25/24
#include "Core/Meta/Aliases.h" // 104% 25/24
#include "Core/Meta/Alignment.h" // 104% 25/24
#include "Core/Meta/TypeTraits.h" // 104% 25/24
#include "Core/Meta/Assert.h" // 104% 25/24
#include "Core/Diagnostic/Exception.h" // 104% 25/24
#include "Core/Meta/BitCount.h" // 104% 25/24
#include "Core/Meta/Cast.h" // 104% 25/24
#include "Core/Meta/TypeHash.h" // 104% 25/24
#include "Core/Meta/Hash_fwd.h" // 104% 25/24
#include "Core/Meta/Delete.h" // 104% 25/24
#include "Core/Meta/Enum.h" // 104% 25/24
#include "Core/Meta/ForRange.h" // 104% 25/24
#include "Core/Meta/Iterator.h" // 104% 25/24
#include "Core/Meta/Warnings.h" // 104% 25/24
#include "Core/Meta/NumericLimits.h" // 104% 25/24
#include "Core/Meta/OneTimeInitialize.h" // 104% 25/24
#include "Core/Meta/StronglyTyped.h" // 104% 25/24
#include "Core/Meta/ThreadResource.h" // 104% 25/24
#include "Core/Allocator/PoolAllocatorTag.h" // 104% 25/24
#include "Core/Memory/MemoryDomain.h" // 104% 25/24
#include "Core.Serialize/Exceptions.h" // 75% 18/24
#include "Core/Allocator/Allocation.h" // 83% 20/24
#include "Core/Allocator/Alloca.h" // 83% 20/24
#include "Core/Memory/MemoryView.h" // 100% 24/24
#include "Core/Memory/UniquePtr.h" // 91% 22/24
#include "Core/Memory/RefPtr.h" // 91% 22/24
#include "Core/Allocator/Mallocator.h" // 83% 20/24
#include "Core/Allocator/AllocatorBase.h" // 83% 20/24
#include "Core/Allocator/Malloc.h" // 83% 20/24
#include "Core/Allocator/ThreadLocalAllocator.h" // 83% 20/24
#include "Core/Allocator/HeapAllocator.h" // 83% 20/24
#include "Core/Allocator/Heap.h" // 83% 20/24
#include "Core/Meta/AlignedStorage.h" // 95% 23/24
#include "Core/Meta/Singleton.h" // 91% 22/24
#include "Core/Allocator/TrackingAllocator.h" // 83% 20/24
#include "Core/Memory/MemoryTracking.h" // 83% 20/24
#include "Core/Container/Hash.h" // 100% 24/24
#include "Core/Memory/HashFunctions.h" // 100% 24/24
#include "Core/IO/String.h" // 79% 19/24
#include "Core/IO/String_fwd.h" // 79% 19/24
#include "Core/IO/Stream.h" // 79% 19/24
#include "Core/Memory/UniqueView.h" // 83% 20/24
#include "Core/IO/StringView.h" // 100% 24/24
#include "Core.Serialize/Lexer/Location.h" // 79% 19/24

