/*
// Generated by PCHRefactor.rb v1.0 for target <Core.Serialize>
//------------------------------------------------------------------------------
// Date : 2018-02-22 09:49:47 UTC
*/

//                                           Target | STD | SDK | PRJ | SRC
// ------------------------------------------------------------------------
//                       Core.Serialize-Win32-Debug |  43 |   0 |   1 |  10
//                   Core.Serialize-Win32-FastDebug |  43 |   0 |   1 |  10
//                     Core.Serialize-Win32-Release |  43 |   0 |   1 |  10
//                   Core.Serialize-Win32-Profiling |  43 |   0 |   1 |  10
//                       Core.Serialize-Win32-Final |  43 |   0 |   1 |  10
//                       Core.Serialize-Win64-Debug |  43 |   0 |   1 |  10
//                   Core.Serialize-Win64-FastDebug |  43 |   0 |   1 |  10
//                     Core.Serialize-Win64-Release |  43 |   0 |   1 |  10
//                   Core.Serialize-Win64-Profiling |  43 |   0 |   1 |  10
//                       Core.Serialize-Win64-Final |  43 |   0 |   1 |  10

/*
// Standard headers
//------------------------------------------------------------------------------
*/
#include <algorithm>
#include <cstdint>
#include <cstdlib>
#include <limits>
#include <cfloat>
#include <climits>
#include <cmath>
#include <cwchar>
#include <cstddef>
#include <initializer_list>
#include <new>
#include <exception>
#include <type_traits>
#include <utility>
#include <iosfwd>
#include <cstdio>
#include <cstring>
#include <atomic>
#include <memory>
#include <typeinfo>
#include <functional>
#include <tuple>
#include <unordered_map>
#include <list>
#include <stdexcept>
#include <vector>
#include <iterator>
#include <istream>
#include <ostream>
#include <ios>
#include <streambuf>
#include <system_error>
#include <cerrno>
#include <mutex>
#include <chrono>
#include <ratio>
#include <thread>
#include <cctype>
#include <cwctype>
#include <locale>
#include <string>
#include <ctime>
#include <deque>

/*
// SDK headers
//------------------------------------------------------------------------------
*/

/*
// Project headers
//------------------------------------------------------------------------------
*/
#include "Core.Serialize/Serialize.h"

