#ifndef _LIB_AUTOAPPIN_FX_INCLUDED
#define _LIB_AUTOAPPIN_FX_INCLUDED

// header file automatically generated by compiler
#include "__AppIn_AutoSubstitutionHeader__"

// generated by shader compiler from vertex declaration
typedef __AppIn_AutoVertexDefinition__ AppIn;

#endif //!_LIB_AUTOAPPIN_FX_INCLUDED
