/*
** Generated by ppe v1.1
*/
#ifdef PLATFORM_WINDOWS
// Global system includes
#include <algorithm>
#include <cstdint>
#include <cstdlib>
#include <limits.h>
#include <limits>
#include <cstddef>
#include <initializer_list>
#include <new>
#include <exception>
#include <type_traits>
#include <cstring>
#include <utility>
#include <atomic>
#include <memory>
#include <optional>
#include <functional>
#include <tuple>
#include <cmath>
#include <list>
#include <stdexcept>
#include <iterator>
#include <numeric>
#include <mutex>
#include <chrono>
#include <thread>
#include <array>
#include <pmmintrin.h>
#include <emmintrin.h>
#include <xmmintrin.h>
#include <immintrin.h>
#include <smmintrin.h>
#include <tmmintrin.h>
#include <intrin.h>
#include <comdef.h>
#include <comutil.h>
#include <cctype>
#include <cwctype>
#include <clocale>
#include <variant>
#include <shared_mutex>
#include <condition_variable>
// Global project includes
#include "winnt_version.h"
#include "Runtime/Core/Public/Core_fwd.h"
#include "Runtime/Core/Public/Meta/Config.h"
#include "Runtime/Core/Public/Meta/Aliases.h"
#include "Runtime/Core/Public/Meta/Alignment.h"
#include "Runtime/Core/Public/Meta/TypeTraits.h"
#include "Runtime/Core/Public/Meta/Arithmetic.h"
#include "Runtime/Core/Public/Meta/Assert.h"
#include "Runtime/Core/Public/Diagnostic/Exception.h"
#include "Runtime/Core/Public/IO/TextWriter_fwd.h"
#include "Runtime/Core/Public/IO/String_fwd.h"
#include "Runtime/Core/Public/HAL/PlatformMacros.h"
#include "Runtime/Core/Public/HAL/Windows/WindowsPlatformMacros.h"
#include "Runtime/Core/Public/HAL/Generic/GenericPlatformMacros.h"
#include "Runtime/Core/Public/Meta/Cast.h"
#include "Runtime/Core/Public/Meta/Delete.h"
#include "Runtime/Core/Public/Meta/Enum.h"
#include "Runtime/Core/Public/Meta/ForRange.h"
#include "Runtime/Core/Public/Meta/Hash_fwd.h"
#include "Runtime/Core/Public/Meta/Iterator.h"
#include "Runtime/Core/Public/Meta/NumericLimits.h"
#include "Runtime/Core/Public/Meta/OneTimeInitialize.h"
#include "Runtime/Core/Public/Meta/StronglyTyped.h"
#include "Runtime/Core/Public/Meta/ThreadResource.h"
#ifdef BUILD_Win32_Debug
// system includes
// project includes
#include "Runtime/Core/Public/Container/BitMask.h"
#include "Runtime/Core/Public/Core.h"
#include "External/stb/stb.git/stb_c_lexer.h"
#include "Runtime/Core/Public/HAL/PlatformMaths.h"
#include "Runtime/Core/Public/HAL/Windows/WindowsPlatformMaths.h"
#include "Runtime/Core/Public/HAL/Generic/GenericPlatformMaths.h"
#include "Runtime/Core/Public/HAL/TargetPlatform.h"
#include "Runtime/Core/Public/HAL/TargetPlatform_fwd.h"
#include "Runtime/Core/Public/Diagnostic/Logger_fwd.h"
#include "Runtime/Core/Public/Memory/MemoryView.h"
#include "Runtime/Core/Public/Memory/PtrRef.h"
#endif // BUILD_Win32_Debug
#ifdef BUILD_Win32_FastDebug
// system includes
#include <ios>
#include <map>
#include <iostream>
#include <regex>
// project includes
#endif // BUILD_Win32_FastDebug
#ifdef BUILD_Win32_Release
// system includes
// project includes
#include "Runtime/Core/Public/Container/BitMask.h"
#include "Runtime/Core/Public/Core.h"
#include "External/stb/stb.git/stb_c_lexer.h"
#include "Runtime/Core/Public/HAL/PlatformMaths.h"
#include "Runtime/Core/Public/HAL/Windows/WindowsPlatformMaths.h"
#include "Runtime/Core/Public/HAL/Generic/GenericPlatformMaths.h"
#include "Runtime/Core/Public/HAL/TargetPlatform.h"
#include "Runtime/Core/Public/HAL/TargetPlatform_fwd.h"
#include "Runtime/Core/Public/Diagnostic/Logger_fwd.h"
#include "Runtime/Core/Public/Memory/MemoryView.h"
#include "Runtime/Core/Public/Memory/PtrRef.h"
#endif // BUILD_Win32_Release
#ifdef BUILD_Win32_Profiling
// system includes
// project includes
#include "Runtime/Core/Public/Container/BitMask.h"
#include "Runtime/Core/Public/Core.h"
#include "External/stb/stb.git/stb_c_lexer.h"
#include "Runtime/Core/Public/HAL/PlatformMaths.h"
#include "Runtime/Core/Public/HAL/Windows/WindowsPlatformMaths.h"
#include "Runtime/Core/Public/HAL/Generic/GenericPlatformMaths.h"
#include "Runtime/Core/Public/HAL/TargetPlatform.h"
#include "Runtime/Core/Public/HAL/TargetPlatform_fwd.h"
#include "Runtime/Core/Public/Diagnostic/Logger_fwd.h"
#include "Runtime/Core/Public/Memory/MemoryView.h"
#include "Runtime/Core/Public/Memory/PtrRef.h"
#endif // BUILD_Win32_Profiling
#ifdef BUILD_Win32_Final
// system includes
// project includes
#include "Runtime/Core/Public/Container/BitMask.h"
#include "Runtime/Core/Public/Core.h"
#include "External/stb/stb.git/stb_c_lexer.h"
#include "Runtime/Core/Public/HAL/PlatformMaths.h"
#include "Runtime/Core/Public/HAL/Windows/WindowsPlatformMaths.h"
#include "Runtime/Core/Public/HAL/Generic/GenericPlatformMaths.h"
#include "Runtime/Core/Public/HAL/TargetPlatform.h"
#include "Runtime/Core/Public/HAL/TargetPlatform_fwd.h"
#include "Runtime/Core/Public/Diagnostic/Logger_fwd.h"
#include "Runtime/Core/Public/Memory/MemoryView.h"
#include "Runtime/Core/Public/Memory/PtrRef.h"
#endif // BUILD_Win32_Final
#ifdef BUILD_Win64_Debug
// system includes
// project includes
#include "Runtime/Core/Public/Container/BitMask.h"
#include "Runtime/Core/Public/Core.h"
#include "External/stb/stb.git/stb_c_lexer.h"
#include "Runtime/Core/Public/HAL/PlatformMaths.h"
#include "Runtime/Core/Public/HAL/Windows/WindowsPlatformMaths.h"
#include "Runtime/Core/Public/HAL/Generic/GenericPlatformMaths.h"
#include "Runtime/Core/Public/HAL/TargetPlatform.h"
#include "Runtime/Core/Public/HAL/TargetPlatform_fwd.h"
#include "Runtime/Core/Public/Diagnostic/Logger_fwd.h"
#include "Runtime/Core/Public/Memory/MemoryView.h"
#include "Runtime/Core/Public/Memory/PtrRef.h"
#endif // BUILD_Win64_Debug
#ifdef BUILD_Win64_FastDebug
// system includes
#include <ios>
#include <map>
#include <iostream>
#include <regex>
// project includes
#endif // BUILD_Win64_FastDebug
#ifdef BUILD_Win64_Release
// system includes
// project includes
#include "Runtime/Core/Public/Container/BitMask.h"
#include "Runtime/Core/Public/Core.h"
#include "External/stb/stb.git/stb_c_lexer.h"
#include "Runtime/Core/Public/HAL/PlatformMaths.h"
#include "Runtime/Core/Public/HAL/Windows/WindowsPlatformMaths.h"
#include "Runtime/Core/Public/HAL/Generic/GenericPlatformMaths.h"
#include "Runtime/Core/Public/HAL/TargetPlatform.h"
#include "Runtime/Core/Public/HAL/TargetPlatform_fwd.h"
#include "Runtime/Core/Public/Diagnostic/Logger_fwd.h"
#include "Runtime/Core/Public/Memory/MemoryView.h"
#include "Runtime/Core/Public/Memory/PtrRef.h"
#endif // BUILD_Win64_Release
#ifdef BUILD_Win64_Profiling
// system includes
// project includes
#include "Runtime/Core/Public/Container/BitMask.h"
#include "Runtime/Core/Public/Core.h"
#include "External/stb/stb.git/stb_c_lexer.h"
#include "Runtime/Core/Public/HAL/PlatformMaths.h"
#include "Runtime/Core/Public/HAL/Windows/WindowsPlatformMaths.h"
#include "Runtime/Core/Public/HAL/Generic/GenericPlatformMaths.h"
#include "Runtime/Core/Public/HAL/TargetPlatform.h"
#include "Runtime/Core/Public/HAL/TargetPlatform_fwd.h"
#include "Runtime/Core/Public/Diagnostic/Logger_fwd.h"
#include "Runtime/Core/Public/Memory/MemoryView.h"
#include "Runtime/Core/Public/Memory/PtrRef.h"
#endif // BUILD_Win64_Profiling
#ifdef BUILD_Win64_Final
// system includes
// project includes
#include "Runtime/Core/Public/Container/BitMask.h"
#include "Runtime/Core/Public/Core.h"
#include "External/stb/stb.git/stb_c_lexer.h"
#include "Runtime/Core/Public/HAL/PlatformMaths.h"
#include "Runtime/Core/Public/HAL/Windows/WindowsPlatformMaths.h"
#include "Runtime/Core/Public/HAL/Generic/GenericPlatformMaths.h"
#include "Runtime/Core/Public/HAL/TargetPlatform.h"
#include "Runtime/Core/Public/HAL/TargetPlatform_fwd.h"
#include "Runtime/Core/Public/Diagnostic/Logger_fwd.h"
#include "Runtime/Core/Public/Memory/MemoryView.h"
#include "Runtime/Core/Public/Memory/PtrRef.h"
#endif // BUILD_Win64_Final
#endif //! PLATFORM_WINDOWS
