/*
// Generated by PCHRefactor.rb v1.0 for target <core.pixmap>
//------------------------------------------------------------------------------
// Date : 2018-02-18 13:32:55 UTC
*/

// Processed dependencies for core.pixmap-Win32-Debug : 42 std, 0 sdk, 3 prj, 9 src
// Processed dependencies for core.pixmap-Win32-FastDebug : 42 std, 0 sdk, 3 prj, 9 src
// Processed dependencies for core.pixmap-Win32-Release : 42 std, 0 sdk, 3 prj, 9 src
// Processed dependencies for core.pixmap-Win32-Profiling : 42 std, 0 sdk, 3 prj, 9 src
// Processed dependencies for core.pixmap-Win32-Final : 42 std, 0 sdk, 3 prj, 9 src
// Processed dependencies for core.pixmap-Win64-Debug : 42 std, 0 sdk, 3 prj, 9 src
// Processed dependencies for core.pixmap-Win64-FastDebug : 42 std, 0 sdk, 3 prj, 9 src
// Processed dependencies for core.pixmap-Win64-Release : 42 std, 0 sdk, 3 prj, 9 src
// Processed dependencies for core.pixmap-Win64-Profiling : 42 std, 0 sdk, 3 prj, 9 src
// Processed dependencies for core.pixmap-Win64-Final : 42 std, 0 sdk, 3 prj, 9 src

/*
// Standard headers
//------------------------------------------------------------------------------
*/
#include <algorithm>
#include <cstdint>
#include <cstdlib>
#include <limits>
#include <cfloat>
#include <climits>
#include <cmath>
#include <cwchar>
#include <cstddef>
#include <initializer_list>
#include <new>
#include <exception>
#include <type_traits>
#include <utility>
#include <iosfwd>
#include <cstdio>
#include <cstring>
#include <atomic>
#include <memory>
#include <typeinfo>
#include <functional>
#include <tuple>
#include <unordered_map>
#include <list>
#include <stdexcept>
#include <vector>
#include <iterator>
#include <istream>
#include <ostream>
#include <ios>
#include <streambuf>
#include <system_error>
#include <cerrno>
#include <mutex>
#include <chrono>
#include <ratio>
#include <thread>
#include <cctype>
#include <cwctype>
#include <locale>
#include <string>
#include <ctime>

/*
// SDK headers
//------------------------------------------------------------------------------
*/

/*
// Project headers
//------------------------------------------------------------------------------
*/
#include "Core.Pixmap/Pixmap.h"
#include "Core.Pixmap/PixelStorage.h"
#include "Core.Pixmap/Pixmap_fwd.h"

