/*
// Generated by PCHRefactor.rb v1.0 for target <Core.RTTI>
//------------------------------------------------------------------------------
// Date : 2017-09-26 00:46:21 UTC
*/

// Processed dependencies for Core.RTTI-Win32-Debug : 44 std, 0 sdk, 13 prj, 16 src
// Processed dependencies for Core.RTTI-Win32-FastDebug : 44 std, 0 sdk, 13 prj, 16 src
// Processed dependencies for Core.RTTI-Win32-Release : 44 std, 0 sdk, 13 prj, 16 src
// Processed dependencies for Core.RTTI-Win32-Profiling : 44 std, 0 sdk, 13 prj, 16 src
// Processed dependencies for Core.RTTI-Win32-Final : 44 std, 0 sdk, 13 prj, 16 src
// Processed dependencies for Core.RTTI-Win64-Debug : 44 std, 0 sdk, 13 prj, 16 src
// Processed dependencies for Core.RTTI-Win64-FastDebug : 44 std, 0 sdk, 13 prj, 16 src
// Processed dependencies for Core.RTTI-Win64-Release : 44 std, 0 sdk, 13 prj, 16 src
// Processed dependencies for Core.RTTI-Win64-Profiling : 44 std, 0 sdk, 13 prj, 16 src
// Processed dependencies for Core.RTTI-Win64-Final : 44 std, 0 sdk, 13 prj, 16 src

/*
// Standard headers
//------------------------------------------------------------------------------
*/
#include <algorithm>
#include <cstdint>
#include <cstdlib>
#include <limits>
#include <cfloat>
#include <climits>
#include <cmath>
#include <cwchar>
#include <cstddef>
#include <initializer_list>
#include <new>
#include <exception>
#include <type_traits>
#include <utility>
#include <iosfwd>
#include <cstdio>
#include <cstring>
#include <atomic>
#include <memory>
#include <typeinfo>
#include <functional>
#include <tuple>
#include <stdexcept>
#include <iomanip>
#include <istream>
#include <ostream>
#include <ios>
#include <streambuf>
#include <system_error>
#include <cerrno>
#include <ctime>
#include <iterator>
#include <mutex>
#include <chrono>
#include <ratio>
#include <thread>
#include <cctype>
#include <cwctype>
#include <locale>
#include <string>
#include <iostream>
#include <sstream>
#include <shared_mutex>
#include <condition_variable>

/*
// SDK headers
//------------------------------------------------------------------------------
*/

/*
// Project headers
//------------------------------------------------------------------------------
*/
#include "Core.RTTI/RTTI.h"
#include "Core.RTTI/Typedefs.h"
#include "Core.RTTI/RTTI_fwd.h"
