/*
// Generated by PCHRefactor.rb v1.0 for target <core.rtti>
//------------------------------------------------------------------------------
// Date : 2018-01-14 22:37:53 UTC
*/

// Processed dependencies for core.rtti-Win32-Debug : 44 std, 0 sdk, 11 prj, 15 src
// Processed dependencies for core.rtti-Win32-FastDebug : 44 std, 0 sdk, 11 prj, 15 src
// Processed dependencies for core.rtti-Win32-Release : 44 std, 0 sdk, 10 prj, 15 src
// Processed dependencies for core.rtti-Win32-Profiling : 44 std, 0 sdk, 9 prj, 15 src
// Processed dependencies for core.rtti-Win32-Final : 44 std, 0 sdk, 9 prj, 15 src
// Processed dependencies for core.rtti-Win64-Debug : 44 std, 0 sdk, 11 prj, 15 src
// Processed dependencies for core.rtti-Win64-FastDebug : 44 std, 0 sdk, 11 prj, 15 src
// Processed dependencies for core.rtti-Win64-Release : 44 std, 0 sdk, 10 prj, 15 src
// Processed dependencies for core.rtti-Win64-Profiling : 44 std, 0 sdk, 9 prj, 15 src
// Processed dependencies for core.rtti-Win64-Final : 44 std, 0 sdk, 9 prj, 15 src

/*
// Standard headers
//------------------------------------------------------------------------------
*/
#include <algorithm>
#include <cstdint>
#include <cstdlib>
#include <limits>
#include <cfloat>
#include <climits>
#include <cmath>
#include <cwchar>
#include <cstddef>
#include <initializer_list>
#include <new>
#include <exception>
#include <type_traits>
#include <utility>
#include <iosfwd>
#include <cstdio>
#include <cstring>
#include <atomic>
#include <memory>
#include <typeinfo>
#include <functional>
#include <tuple>
#include <unordered_map>
#include <list>
#include <stdexcept>
#include <vector>
#include <iterator>
#include <istream>
#include <ostream>
#include <ios>
#include <streambuf>
#include <system_error>
#include <cerrno>
#include <mutex>
#include <chrono>
#include <ratio>
#include <thread>
#include <cctype>
#include <cwctype>
#include <locale>
#include <string>
#include <ctime>
#include <shared_mutex>
#include <condition_variable>

/*
// SDK headers
//------------------------------------------------------------------------------
*/

/*
// Project headers
//------------------------------------------------------------------------------
*/
#if 0 // dummy
#elif defined(BUILDCONFIG_Win32_Debug) || defined(BUILDCONFIG_Win32_FastDebug) || defined(BUILDCONFIG_Win64_Debug) || defined(BUILDCONFIG_Win64_FastDebug)
#    include "Core.RTTI/RTTI.h"
#    include "core.rtti/Atom.h"
#    include "Core.RTTI/TypeTraits.h"
#    include "Core.RTTI/TypeInfos.h"
#    include "Core.RTTI/Typedefs.h"
#    include "core.rtti/RTTI_fwd.h"
#    include "Core.RTTI/MetaClass.h"
#    include "Core.RTTI/MetaNamespace.h"
#    include "Core.RTTI/MetaFunction.h"
#    include "Core.RTTI/MetaProperty.h"
#    include "core.rtti/MetaObject.h"
#elif defined(BUILDCONFIG_Win32_Release) || defined(BUILDCONFIG_Win64_Release)
#    include "Core.RTTI/RTTI.h"
#    include "core.rtti/Atom.h"
#    include "Core.RTTI/TypeTraits.h"
#    include "Core.RTTI/TypeInfos.h"
#    include "Core.RTTI/Typedefs.h"
#    include "Core.RTTI/MetaClass.h"
#    include "Core.RTTI/MetaNamespace.h"
#    include "Core.RTTI/MetaFunction.h"
#    include "Core.RTTI/MetaProperty.h"
#    include "core.rtti/MetaObject.h"
#elif defined(BUILDCONFIG_Win32_Profiling) || defined(BUILDCONFIG_Win32_Final) || defined(BUILDCONFIG_Win64_Profiling) || defined(BUILDCONFIG_Win64_Final)
#    include "Core.RTTI/RTTI.h"
#    include "core.rtti/Atom.h"
#    include "Core.RTTI/TypeTraits.h"
#    include "Core.RTTI/TypeInfos.h"
#    include "Core.RTTI/Typedefs.h"
#    include "Core.RTTI/MetaClass.h"
#    include "Core.RTTI/MetaNamespace.h"
#    include "Core.RTTI/MetaFunction.h"
#    include "Core.RTTI/MetaProperty.h"
#else
#     error "unknown build config"
#endif

