//----------------------------------------------------------------------------
UNITS_BEGIN(Time)
UNITS_DECL(Time,        us, FMicroseconds,  1000,   void)
UNITS_DECL(Time,        ms, FMilliseconds,  1000,   Core::Units::Time::FMicroseconds)
UNITS_DECL(Time,         s, FSeconds,       60,     Core::Units::Time::FMilliseconds)
UNITS_DECL(Time,         m, FMinutes,       60,     Core::Units::Time::FSeconds)
UNITS_DECL(Time,         h, FHours,         24,     Core::Units::Time::FMinutes)
UNITS_DECL(Time,         d, FDays,          1,      Core::Units::Time::FHours)
UNITS_END()
//----------------------------------------------------------------------------
UNITS_BEGIN(Distance)
UNITS_DECL(Distance,    mm, FMillimeters,   10,     void)
UNITS_DECL(Distance,    cm, FCentimeters,   100,    Core::Units::Distance::FMillimeters)
UNITS_DECL(Distance,     m, FMeters,        1000,   Core::Units::Distance::FCentimeters)
UNITS_DECL(Distance,    km, FKilometers,    1,      Core::Units::Distance::FMeters)
UNITS_END()
//----------------------------------------------------------------------------
UNITS_BEGIN(Mass)
UNITS_DECL(Mass,        pg, FPicograms,     1000,   void)
UNITS_DECL(Mass,        ng, FNanograms,     1000,   Core::Units::Mass::FPicograms)
UNITS_DECL(Mass,        ug, FMicrograms,    1000,   Core::Units::Mass::FNanograms)
UNITS_DECL(Mass,        mg, FMilligrams,    1000,   Core::Units::Mass::FMicrograms)
UNITS_DECL(Mass,         g, FGrams,         1000,   Core::Units::Mass::FMilligrams)
UNITS_DECL(Mass,        kg, FKilograms,     1000,   Core::Units::Mass::FGrams)
UNITS_DECL(Mass,         t, FTonnes,        1,      Core::Units::Mass::FKilograms)
UNITS_END()
//----------------------------------------------------------------------------
UNITS_BEGIN(Storage)
UNITS_DECL(Storage,      b, FBytes,         1024,   void)
UNITS_DECL(Storage,     kb, FKilobytes,     1024,   Core::Units::Storage::FBytes)
UNITS_DECL(Storage,     mb, FMegabytes,     1024,   Core::Units::Storage::FKilobytes)
UNITS_DECL(Storage,     gb, FGigabytes,     1024,   Core::Units::Storage::FMegabytes)
UNITS_DECL(Storage,     tb, FTerabytes,     1024,   Core::Units::Storage::FGigabytes)
UNITS_DECL(Storage,     pb, FPetabytes,     1,      Core::Units::Storage::FTerabytes)
UNITS_END()
//----------------------------------------------------------------------------
