/*
// Generated by PCHRefactor.rb v1.0 for target <Core.ContentGenerator>
//------------------------------------------------------------------------------
// Date : 2018-02-22 09:48:33 UTC
*/

//                                           Target | STD | SDK | PRJ | SRC
// ------------------------------------------------------------------------
//                Core.ContentGenerator-Win32-Debug |  49 |   0 |   0 |   2
//            Core.ContentGenerator-Win32-FastDebug |  49 |   0 |   0 |   2
//              Core.ContentGenerator-Win32-Release |  49 |   0 |   0 |   2
//            Core.ContentGenerator-Win32-Profiling |  49 |   0 |   0 |   2
//                Core.ContentGenerator-Win32-Final |  48 |   0 |   0 |   2
//                Core.ContentGenerator-Win64-Debug |  49 |   0 |   0 |   2
//            Core.ContentGenerator-Win64-FastDebug |  49 |   0 |   0 |   2
//              Core.ContentGenerator-Win64-Release |  49 |   0 |   0 |   2
//            Core.ContentGenerator-Win64-Profiling |  49 |   0 |   0 |   2
//                Core.ContentGenerator-Win64-Final |  48 |   0 |   0 |   2

/*
// Standard headers
//------------------------------------------------------------------------------
*/
#if 0 // dummy
#elif defined(BUILDCONFIG_Win32_Debug) || defined(BUILDCONFIG_Win32_FastDebug) || defined(BUILDCONFIG_Win32_Release) || defined(BUILDCONFIG_Win32_Profiling) || defined(BUILDCONFIG_Win64_Debug) || defined(BUILDCONFIG_Win64_FastDebug) || defined(BUILDCONFIG_Win64_Release) || defined(BUILDCONFIG_Win64_Profiling)
#    include <algorithm>
#    include <cstdint>
#    include <cstdlib>
#    include <limits>
#    include <cfloat>
#    include <climits>
#    include <cmath>
#    include <cwchar>
#    include <cstddef>
#    include <initializer_list>
#    include <new>
#    include <exception>
#    include <type_traits>
#    include <utility>
#    include <iosfwd>
#    include <cstdio>
#    include <cstring>
#    include <atomic>
#    include <memory>
#    include <typeinfo>
#    include <functional>
#    include <tuple>
#    include <unordered_map>
#    include <list>
#    include <stdexcept>
#    include <vector>
#    include <iterator>
#    include <istream>
#    include <ostream>
#    include <ios>
#    include <streambuf>
#    include <system_error>
#    include <cerrno>
#    include <mutex>
#    include <chrono>
#    include <ratio>
#    include <thread>
#    include <cctype>
#    include <cwctype>
#    include <locale>
#    include <string>
#    include <ctime>
#    include <optional>
#    include <iostream>
#    include <cassert>
#    include <regex>
#    include <condition_variable>
#    include <queue>
#    include <deque>
#elif defined(BUILDCONFIG_Win32_Final) || defined(BUILDCONFIG_Win64_Final)
#    include <algorithm>
#    include <cstdint>
#    include <cstdlib>
#    include <limits>
#    include <cfloat>
#    include <climits>
#    include <cmath>
#    include <cwchar>
#    include <cstddef>
#    include <initializer_list>
#    include <new>
#    include <exception>
#    include <type_traits>
#    include <utility>
#    include <iosfwd>
#    include <cstdio>
#    include <cstring>
#    include <atomic>
#    include <memory>
#    include <typeinfo>
#    include <functional>
#    include <tuple>
#    include <unordered_map>
#    include <list>
#    include <stdexcept>
#    include <vector>
#    include <iterator>
#    include <istream>
#    include <ostream>
#    include <ios>
#    include <streambuf>
#    include <system_error>
#    include <cerrno>
#    include <mutex>
#    include <chrono>
#    include <ratio>
#    include <thread>
#    include <cctype>
#    include <cwctype>
#    include <locale>
#    include <string>
#    include <ctime>
#    include <cassert>
#    include <regex>
#    include <condition_variable>
#    include <queue>
#    include <deque>
#    include <optional>
#else
#     error "unknown build config"
#endif

/*
// SDK headers
//------------------------------------------------------------------------------
*/

/*
// Project headers
//------------------------------------------------------------------------------
*/

