/*
// Generated by PCHRefactor.rb v1.0 for target <Core.Application.Graphics>
//------------------------------------------------------------------------------
// Date : 2018-02-22 10:26:01 UTC
*/

//                                           Target | STD | SDK | PRJ | SRC
// ------------------------------------------------------------------------
//            Core.Application.Graphics-Win32-Debug |  44 |   0 |   0 |   0
//        Core.Application.Graphics-Win32-FastDebug |  44 |   0 |   0 |   0
//          Core.Application.Graphics-Win32-Release |  44 |   0 |   0 |   0
//        Core.Application.Graphics-Win32-Profiling |  44 |   0 |   0 |   0
//            Core.Application.Graphics-Win32-Final |  44 |   0 |   0 |   0
//            Core.Application.Graphics-Win64-Debug |  44 |   0 |   0 |   0
//        Core.Application.Graphics-Win64-FastDebug |  44 |   0 |   0 |   0
//          Core.Application.Graphics-Win64-Release |  44 |   0 |   0 |   0
//        Core.Application.Graphics-Win64-Profiling |  44 |   0 |   0 |   0
//            Core.Application.Graphics-Win64-Final |  44 |   0 |   0 |   0

/*
// Standard headers
//------------------------------------------------------------------------------
*/
#include <algorithm>
#include <cstdint>
#include <cstdlib>
#include <limits>
#include <cfloat>
#include <climits>
#include <cmath>
#include <cwchar>
#include <cstddef>
#include <initializer_list>
#include <new>
#include <exception>
#include <type_traits>
#include <utility>
#include <iosfwd>
#include <cstdio>
#include <cstring>
#include <atomic>
#include <memory>
#include <typeinfo>
#include <functional>
#include <tuple>
#include <unordered_map>
#include <list>
#include <stdexcept>
#include <vector>
#include <iterator>
#include <istream>
#include <ostream>
#include <ios>
#include <streambuf>
#include <system_error>
#include <cerrno>
#include <mutex>
#include <chrono>
#include <ratio>
#include <thread>
#include <cctype>
#include <cwctype>
#include <locale>
#include <string>
#include <ctime>
#include <optional>
#include <clocale>

/*
// SDK headers
//------------------------------------------------------------------------------
*/

/*
// Project headers
//------------------------------------------------------------------------------
*/

