/*
// Generated by PCHRefactor.rb v1.1 for target <Runtime/Application>
//------------------------------------------------------------------------------
// Date : 2019-11-28 08:38:10 UTC
*/

//                                           Target | STD | SDK | PRJ | SRC
// ------------------------------------------------------------------------
//                  Runtime/Application-Win32-Debug |  41 |   5 |   0 |  30
//              Runtime/Application-Win32-FastDebug |  50 |   5 |   2 |  30
//                Runtime/Application-Win32-Release |  41 |   5 |   0 |  30
//              Runtime/Application-Win32-Profiling |  41 |   5 |   0 |  30
//                  Runtime/Application-Win32-Final |  41 |   5 |   0 |  30
//                  Runtime/Application-Win64-Debug |  41 |   5 |   0 |  30
//              Runtime/Application-Win64-FastDebug |  50 |   5 |   2 |  30
//                Runtime/Application-Win64-Release |  41 |   5 |   0 |  30
//              Runtime/Application-Win64-Profiling |  41 |   5 |   0 |  30
//                  Runtime/Application-Win64-Final |  41 |   5 |   0 |  30

/*
// Standard headers
//------------------------------------------------------------------------------
*/
#if 0 // dummy
#elif defined(BUILDCONFIG_Win32_Debug) || defined(BUILDCONFIG_Win32_Release) || defined(BUILDCONFIG_Win32_Profiling) || defined(BUILDCONFIG_Win32_Final) || defined(BUILDCONFIG_Win64_Debug) || defined(BUILDCONFIG_Win64_Release) || defined(BUILDCONFIG_Win64_Profiling) || defined(BUILDCONFIG_Win64_Final)
#    include <algorithm>
#    include <cstdint>
#    include <cstdlib>
#    include <limits>
#    include <cfloat>
#    include <climits>
#    include <cwchar>
#    include <cstdio>
#    include <cstddef>
#    include <initializer_list>
#    include <new>
#    include <exception>
#    include <type_traits>
#    include <cstring>
#    include <utility>
#    include <atomic>
#    include <memory>
#    include <iosfwd>
#    include <typeinfo>
#    include <functional>
#    include <tuple>
#    include <unordered_map>
#    include <cmath>
#    include <list>
#    include <vector>
#    include <stdexcept>
#    include <iterator>
#    include <istream>
#    include <ostream>
#    include <ios>
#    include <streambuf>
#    include <system_error>
#    include <cerrno>
#    include <mutex>
#    include <chrono>
#    include <ratio>
#    include <thread>
#    include <cctype>
#    include <cwctype>
#    include <locale>
#    include <ctime>
#elif defined(BUILDCONFIG_Win32_FastDebug) || defined(BUILDCONFIG_Win64_FastDebug)
#    include <algorithm>
#    include <cstdint>
#    include <cstdlib>
#    include <limits>
#    include <cfloat>
#    include <climits>
#    include <cwchar>
#    include <cstdio>
#    include <cstddef>
#    include <initializer_list>
#    include <new>
#    include <exception>
#    include <type_traits>
#    include <cstring>
#    include <utility>
#    include <atomic>
#    include <memory>
#    include <iosfwd>
#    include <typeinfo>
#    include <functional>
#    include <tuple>
#    include <unordered_map>
#    include <cmath>
#    include <list>
#    include <vector>
#    include <stdexcept>
#    include <iterator>
#    include <istream>
#    include <ostream>
#    include <ios>
#    include <streambuf>
#    include <system_error>
#    include <cerrno>
#    include <mutex>
#    include <chrono>
#    include <ratio>
#    include <thread>
#    include <cctype>
#    include <cwctype>
#    include <locale>
#    include <ctime>
#    include <optional>
#    include <iostream>
#    include <clocale>
#    include <regex>
#    include <string>
#    include <cassert>
#    include <condition_variable>
#    include <memory_resource>
#    include <cstdarg>
#else
#     error "unknown build config"
#endif

/*
// SDK headers
//------------------------------------------------------------------------------
*/
#include <ShellScalingApi.h>
#include <XInput.h>
#include <windowsx.h>
#include <shellapi.h>
#include <Shobjidl.h>

/*
// Project headers
//------------------------------------------------------------------------------
*/
#if 0 // dummy
#elif defined(BUILDCONFIG_Win32_Debug) || defined(BUILDCONFIG_Win32_Release) || defined(BUILDCONFIG_Win32_Profiling) || defined(BUILDCONFIG_Win32_Final) || defined(BUILDCONFIG_Win64_Debug) || defined(BUILDCONFIG_Win64_Release) || defined(BUILDCONFIG_Win64_Profiling) || defined(BUILDCONFIG_Win64_Final)
#elif defined(BUILDCONFIG_Win32_FastDebug) || defined(BUILDCONFIG_Win64_FastDebug)
#    include "Runtime/Core/Public/Core.h"
#    include "Runtime/Core/Public/Meta/ThreadResource.h"
#else
#     error "unknown build config"
#endif

