/*
// Generated by PCHRefactor.rb v1.1 for target <Runtime/Network>
//------------------------------------------------------------------------------
// Date : 2019-12-24 02:37:51 UTC
*/

//                                           Target | STD | SDK | PRJ | SRC
// ------------------------------------------------------------------------
//                      Runtime/Network-Win32-Debug |  42 |   2 |   0 |  18
//                  Runtime/Network-Win32-FastDebug |  50 |   2 |   6 |  18
//                    Runtime/Network-Win32-Release |  42 |   2 |   0 |  18
//                  Runtime/Network-Win32-Profiling |  42 |   2 |   0 |  18
//                      Runtime/Network-Win32-Final |  42 |   2 |   0 |  18
//                      Runtime/Network-Win64-Debug |  42 |   2 |   0 |  18
//                  Runtime/Network-Win64-FastDebug |  50 |   2 |   6 |  18
//                    Runtime/Network-Win64-Release |  42 |   2 |   0 |  18
//                  Runtime/Network-Win64-Profiling |  42 |   2 |   0 |  18
//                      Runtime/Network-Win64-Final |  42 |   2 |   0 |  18

/*
// Standard headers
//------------------------------------------------------------------------------
*/
#if 0 // dummy
#elif defined(BUILD_Win32_Debug) || defined(BUILD_Win32_Release) || defined(BUILD_Win32_Profiling) || defined(BUILD_Win32_Final) || defined(BUILD_Win64_Debug) || defined(BUILD_Win64_Release) || defined(BUILD_Win64_Profiling) || defined(BUILD_Win64_Final)
#    include <algorithm>
#    include <cstdint>
#    include <cstdlib>
#    include <limits>
#    include <cfloat>
#    include <climits>
#    include <cwchar>
#    include <cstdio>
#    include <cstddef>
#    include <initializer_list>
#    include <new>
#    include <exception>
#    include <type_traits>
#    include <cstring>
#    include <utility>
#    include <atomic>
#    include <memory>
#    include <iosfwd>
#    include <typeinfo>
#    include <functional>
#    include <tuple>
#    include <unordered_map>
#    include <cmath>
#    include <list>
#    include <vector>
#    include <stdexcept>
#    include <iterator>
#    include <istream>
#    include <ostream>
#    include <ios>
#    include <streambuf>
#    include <system_error>
#    include <cerrno>
#    include <mutex>
#    include <chrono>
#    include <ratio>
#    include <thread>
#    include <cctype>
#    include <cwctype>
#    include <locale>
#    include <ctime>
#    include <optional>
#elif defined(BUILD_Win32_FastDebug) || defined(BUILD_Win64_FastDebug)
#    include <algorithm>
#    include <cstdint>
#    include <cstdlib>
#    include <limits>
#    include <cfloat>
#    include <climits>
#    include <cwchar>
#    include <cstdio>
#    include <cstddef>
#    include <initializer_list>
#    include <new>
#    include <exception>
#    include <type_traits>
#    include <cstring>
#    include <utility>
#    include <atomic>
#    include <memory>
#    include <iosfwd>
#    include <typeinfo>
#    include <functional>
#    include <tuple>
#    include <unordered_map>
#    include <cmath>
#    include <list>
#    include <vector>
#    include <stdexcept>
#    include <iterator>
#    include <istream>
#    include <ostream>
#    include <ios>
#    include <streambuf>
#    include <system_error>
#    include <cerrno>
#    include <mutex>
#    include <chrono>
#    include <ratio>
#    include <thread>
#    include <cctype>
#    include <cwctype>
#    include <locale>
#    include <ctime>
#    include <optional>
#    include <iostream>
#    include <clocale>
#    include <regex>
#    include <string>
#    include <cassert>
#    include <condition_variable>
#    include <memory_resource>
#    include <cstdarg>
#else
#     error "unknown build config"
#endif

/*
// SDK headers
//------------------------------------------------------------------------------
*/
#include <WinSock2.h>
#include <Ws2tcpip.h>

/*
// Project headers
//------------------------------------------------------------------------------
*/
#if 0 // dummy
#elif defined(BUILD_Win32_Debug) || defined(BUILD_Win32_Release) || defined(BUILD_Win32_Profiling) || defined(BUILD_Win32_Final) || defined(BUILD_Win64_Debug) || defined(BUILD_Win64_Release) || defined(BUILD_Win64_Profiling) || defined(BUILD_Win64_Final)
#elif defined(BUILD_Win32_FastDebug) || defined(BUILD_Win64_FastDebug)
#    include "Runtime/Core/Public/Diagnostic/Exception.h"
#    include "Runtime/Core/Public/IO/TextWriter_fwd.h"
#    include "Runtime/Core/Public/IO/String_fwd.h"
#    include "Runtime/Core/Public/Core.h"
#    include "Runtime/Core/Public/Memory/MemoryView.h"
#    include "Runtime/Core/Public/HAL/Windows/WindowsPlatformIncludes.h"
#else
#     error "unknown build config"
#endif

