/*
// Generated by PCHRefactor.rb v1.1 for target <Core.RTTI>
//------------------------------------------------------------------------------
// Date : 2018-07-21 21:31:11 UTC
*/

//                                           Target | STD | SDK | PRJ | SRC
// ------------------------------------------------------------------------
//                            Core.RTTI-Win32-Debug |  42 |   0 |  10 |  17
//                        Core.RTTI-Win32-FastDebug |  42 |   0 |  10 |  17
//                          Core.RTTI-Win32-Release |  42 |   0 |  10 |  17
//                        Core.RTTI-Win32-Profiling |  42 |   0 |   6 |  17
//                            Core.RTTI-Win32-Final |  42 |   0 |   6 |  17
//                            Core.RTTI-Win64-Debug |  42 |   0 |  10 |  17
//                        Core.RTTI-Win64-FastDebug |  42 |   0 |  10 |  17
//                          Core.RTTI-Win64-Release |  42 |   0 |  10 |  17
//                        Core.RTTI-Win64-Profiling |  42 |   0 |   6 |  17
//                            Core.RTTI-Win64-Final |  42 |   0 |   6 |  17

/*
// Standard headers
//------------------------------------------------------------------------------
*/
#include <algorithm>
#include <cstdint>
#include <cstdlib>
#include <limits>
#include <cfloat>
#include <climits>
#include <cmath>
#include <cwchar>
#include <cstddef>
#include <initializer_list>
#include <new>
#include <exception>
#include <type_traits>
#include <utility>
#include <iosfwd>
#include <cstdio>
#include <cstring>
#include <atomic>
#include <memory>
#include <typeinfo>
#include <functional>
#include <tuple>
#include <unordered_map>
#include <list>
#include <stdexcept>
#include <vector>
#include <iterator>
#include <istream>
#include <ostream>
#include <ios>
#include <streambuf>
#include <system_error>
#include <cerrno>
#include <mutex>
#include <chrono>
#include <ratio>
#include <thread>
#include <cctype>
#include <cwctype>
#include <locale>
#include <string>
#include <ctime>

/*
// SDK headers
//------------------------------------------------------------------------------
*/

/*
// Project headers
//------------------------------------------------------------------------------
*/
#if 0 // dummy
#elif defined(BUILDCONFIG_Win32_Debug) || defined(BUILDCONFIG_Win32_FastDebug) || defined(BUILDCONFIG_Win32_Release) || defined(BUILDCONFIG_Win64_Debug) || defined(BUILDCONFIG_Win64_FastDebug) || defined(BUILDCONFIG_Win64_Release)
#    include "Core.RTTI/RTTI.h"
#    include "Core.RTTI/Atom.h"
#    include "Core.RTTI/TypeTraits.h"
#    include "Core.RTTI/TypeInfos.h"
#    include "Core.RTTI/Typedefs.h"
#    include "Core.RTTI/RTTI_fwd.h"
#    include "Core.RTTI/MetaClass.h"
#    include "Core.RTTI/MetaNamespace.h"
#    include "Core.RTTI/MetaFunction.h"
#    include "Core.RTTI/MetaProperty.h"
#elif defined(BUILDCONFIG_Win32_Profiling) || defined(BUILDCONFIG_Win32_Final) || defined(BUILDCONFIG_Win64_Profiling) || defined(BUILDCONFIG_Win64_Final)
#    include "Core.RTTI/RTTI.h"
#    include "Core.RTTI/Atom.h"
#    include "Core.RTTI/TypeTraits.h"
#    include "Core.RTTI/TypeInfos.h"
#    include "Core.RTTI/Typedefs.h"
#    include "Core.RTTI/RTTI_fwd.h"
#else
#     error "unknown build config"
#endif

