/*
** Generated by ./ppe.rb v1.0.0
*/
#ifdef PLATFORM_WINDOWS
// Global system includes (47)
#include <stdio.h> // 177 refs
#include <algorithm> // 177 refs
#include <stdint.h> // 177 refs
#include <limits.h> // 177 refs
#include <limits> // 177 refs
#include <float.h> // 177 refs
#include <wchar.h> // 177 refs
#include <errno.h> // 177 refs
#include <sys/stat.h> // 177 refs
#include <sys/types.h> // 177 refs
#include <initializer_list> // 177 refs
#include <new> // 177 refs
#include <exception> // 177 refs
#include <type_traits> // 177 refs
#include <string.h> // 177 refs
#include <utility> // 177 refs
#include <atomic> // 175 refs
#include <memory> // 175 refs
#include <typeinfo> // 175 refs
#include <functional> // 175 refs
#include <tuple> // 175 refs
#include <cmath> // 175 refs
#include <list> // 175 refs
#include <stdexcept> // 175 refs
#include <iterator> // 175 refs
#include <locale.h> // 175 refs
#include <mutex> // 175 refs
#include <chrono> // 175 refs
#include <time.h> // 175 refs
#include <thread> // 175 refs
#include <intrin.h> // 138 refs
#include <immintrin.h> // 139 refs
#include <smmintrin.h> // 139 refs
#include <tmmintrin.h> // 139 refs
#include <pmmintrin.h> // 140 refs
#include <emmintrin.h> // 140 refs
#include <xmmintrin.h> // 140 refs
#include <malloc.h> // 169 refs
#include <cctype> // 98 refs
#include <cwctype> // 98 refs
#include <locale> // 99 refs
#include <comdef.h> // 167 refs
#include <Windows.h> // 167 refs
#include <winnt.h> // 167 refs
#include <comutil.h> // 167 refs
#include <tchar.h> // 167 refs
#include <memory.h> // 115 refs
// Global project includes (23)
#include "winnt_version.h" // 177 refs
#include "Runtime/Core/Public/Core_fwd.h" // 175 refs
#include "Runtime/Core/Public/Meta/Config.h" // 175 refs
#include "Runtime/Core/Public/Meta/Aliases.h" // 177 refs
#include "Runtime/Core/Public/Meta/Alignment.h" // 175 refs
#include "Runtime/Core/Public/Meta/TypeTraits.h" // 175 refs
#include "Runtime/Core/Public/Meta/Assert.h" // 175 refs
#include "Runtime/Core/Public/Diagnostic/Exception.h" // 175 refs
#include "Runtime/Core/Public/IO/TextWriter_fwd.h" // 175 refs
#include "Runtime/Core/Public/IO/String_fwd.h" // 175 refs
#include "Runtime/Core/Public/Meta/Cast.h" // 175 refs
#include "Runtime/Core/Public/Meta/TypeHash.h" // 175 refs
#include "Runtime/Core/Public/Meta/Hash_fwd.h" // 175 refs
#include "Runtime/Core/Public/Meta/Warnings.h" // 177 refs
#include "Runtime/Core/Public/Meta/Delete.h" // 175 refs
#include "Runtime/Core/Public/Core.h" // 175 refs
#include "Runtime/Core/Public/Meta/Enum.h" // 175 refs
#include "Runtime/Core/Public/Meta/ForRange.h" // 175 refs
#include "Runtime/Core/Public/Meta/Iterator.h" // 175 refs
#include "Runtime/Core/Public/Meta/NumericLimits.h" // 175 refs
#include "Runtime/Core/Public/Meta/OneTimeInitialize.h" // 175 refs
#include "Runtime/Core/Public/Meta/StronglyTyped.h" // 175 refs
#include "Runtime/Core/Public/Meta/ThreadResource.h" // 175 refs
#ifdef BUILD_Win32_Debug
// system includes (0)
// project includes (24)
#include "Runtime/Core/ModuleExport.h" // 23 refs
#include "Runtime/Core/Public/Module.h" // 23 refs
#include "Runtime/RTTI/ModuleExport.h" // 23 refs
#include "Runtime/RTTI/Public/RTTI_fwd.h" // 23 refs
#include "Runtime/Core/Public/IO/StringView.h" // 23 refs
#include "Runtime/Core/Public/Container/Hash.h" // 23 refs
#include "Runtime/Core/Public/HAL/PlatformHash.h" // 23 refs
#include "Runtime/Core/Public/HAL/TargetPlatform.h" // 23 refs
#include "Runtime/Core/Public/HAL/TargetPlatform_fwd.h" // 23 refs
#include "Runtime/Core/Public/Diagnostic/Logger_fwd.h" // 23 refs
#include "Runtime/Core/Public/Memory/MemoryView.h" // 23 refs
#include "Runtime/Core/Public/HAL/Windows/WindowsPlatformHash.h" // 23 refs
#include "Runtime/Core/Public/HAL/Generic/GenericPlatformHash.h" // 23 refs
#include "Runtime/Core/Public/Memory/HashFunctions.h" // 23 refs
#include "Runtime/Core/Public/Memory/MemoryDomain.h" // 23 refs
#include "Runtime/Core/Public/Memory/RefPtr.h" // 23 refs
#include "Runtime/Core/Public/Allocator/TrackingMalloc.h" // 23 refs
#include "Runtime/Core/Public/Allocator/Malloc.h" // 23 refs
#include "Runtime/Core/Public/HAL/PlatformDebug.h" // 23 refs
#include "Runtime/Core/Public/HAL/Generic/GenericPlatformDebug.h" // 23 refs
#include "Runtime/Core/Public/HAL/Windows/WindowsPlatformDebug.h" // 23 refs
#include "Runtime/Core/Public/HAL/Windows/WindowsPlatformIncludes.h" // 23 refs
#include "Runtime/Core/Public/HAL/Generic/GenericPlatformIncludes.h" // 23 refs
#include "Runtime/Core/Public/HAL/PlatformIncludes.h" // 23 refs
#endif // BUILD_Win32_Debug
#ifdef BUILD_Win32_FastDebug
// system includes (18)
#include <optional> // 1 refs
#include <iostream> // 2 refs
#include <DbgHelp.h> // 4 refs
#include <TlHelp32.h> // 3 refs
#include <initguid.h> // 1 refs
#include <KnownFolders.h> // 1 refs
#include <shellapi.h> // 2 refs
#include <Shlwapi.h> // 1 refs
#include <ShlObj.h> // 1 refs
#include <fcntl.h> // 2 refs
#include <io.h> // 2 refs
#include <Psapi.h> // 2 refs
#include <clocale> // 1 refs
#include <mbctype.h> // 1 refs
#include <VersionHelpers.h> // 1 refs
#include <timeapi.h> // 1 refs
#include <regex> // 1 refs
#include <condition_variable> // 2 refs
// project includes (0)
#endif // BUILD_Win32_FastDebug
#ifdef BUILD_Win32_Release
// system includes (0)
// project includes (24)
#include "Runtime/Core/ModuleExport.h" // 23 refs
#include "Runtime/Core/Public/Module.h" // 23 refs
#include "Runtime/RTTI/ModuleExport.h" // 23 refs
#include "Runtime/RTTI/Public/RTTI_fwd.h" // 23 refs
#include "Runtime/Core/Public/IO/StringView.h" // 23 refs
#include "Runtime/Core/Public/Container/Hash.h" // 23 refs
#include "Runtime/Core/Public/HAL/PlatformHash.h" // 23 refs
#include "Runtime/Core/Public/HAL/TargetPlatform.h" // 23 refs
#include "Runtime/Core/Public/HAL/TargetPlatform_fwd.h" // 23 refs
#include "Runtime/Core/Public/Diagnostic/Logger_fwd.h" // 23 refs
#include "Runtime/Core/Public/Memory/MemoryView.h" // 23 refs
#include "Runtime/Core/Public/HAL/Windows/WindowsPlatformHash.h" // 23 refs
#include "Runtime/Core/Public/HAL/Generic/GenericPlatformHash.h" // 23 refs
#include "Runtime/Core/Public/Memory/HashFunctions.h" // 23 refs
#include "Runtime/Core/Public/Memory/MemoryDomain.h" // 23 refs
#include "Runtime/Core/Public/Memory/RefPtr.h" // 23 refs
#include "Runtime/Core/Public/Allocator/TrackingMalloc.h" // 23 refs
#include "Runtime/Core/Public/Allocator/Malloc.h" // 23 refs
#include "Runtime/Core/Public/HAL/PlatformDebug.h" // 23 refs
#include "Runtime/Core/Public/HAL/Generic/GenericPlatformDebug.h" // 23 refs
#include "Runtime/Core/Public/HAL/Windows/WindowsPlatformDebug.h" // 23 refs
#include "Runtime/Core/Public/HAL/Windows/WindowsPlatformIncludes.h" // 23 refs
#include "Runtime/Core/Public/HAL/Generic/GenericPlatformIncludes.h" // 23 refs
#include "Runtime/Core/Public/HAL/PlatformIncludes.h" // 23 refs
#endif // BUILD_Win32_Release
#ifdef BUILD_Win32_Profiling
// system includes (0)
// project includes (23)
#include "Runtime/Core/ModuleExport.h" // 23 refs
#include "Runtime/Core/Public/Module.h" // 23 refs
#include "Runtime/RTTI/ModuleExport.h" // 23 refs
#include "Runtime/RTTI/Public/RTTI_fwd.h" // 23 refs
#include "Runtime/Core/Public/IO/StringView.h" // 23 refs
#include "Runtime/Core/Public/Container/Hash.h" // 23 refs
#include "Runtime/Core/Public/HAL/PlatformHash.h" // 23 refs
#include "Runtime/Core/Public/HAL/TargetPlatform.h" // 23 refs
#include "Runtime/Core/Public/HAL/TargetPlatform_fwd.h" // 23 refs
#include "Runtime/Core/Public/Diagnostic/Logger_fwd.h" // 23 refs
#include "Runtime/Core/Public/Memory/MemoryView.h" // 23 refs
#include "Runtime/Core/Public/HAL/Windows/WindowsPlatformHash.h" // 23 refs
#include "Runtime/Core/Public/HAL/Generic/GenericPlatformHash.h" // 23 refs
#include "Runtime/Core/Public/Memory/HashFunctions.h" // 23 refs
#include "Runtime/Core/Public/Memory/MemoryDomain.h" // 23 refs
#include "Runtime/Core/Public/Memory/RefPtr.h" // 23 refs
#include "Runtime/Core/Public/Allocator/Malloc.h" // 23 refs
#include "Runtime/Core/Public/HAL/PlatformDebug.h" // 23 refs
#include "Runtime/Core/Public/HAL/Generic/GenericPlatformDebug.h" // 23 refs
#include "Runtime/Core/Public/HAL/Windows/WindowsPlatformDebug.h" // 23 refs
#include "Runtime/Core/Public/HAL/Windows/WindowsPlatformIncludes.h" // 23 refs
#include "Runtime/Core/Public/HAL/Generic/GenericPlatformIncludes.h" // 23 refs
#include "Runtime/Core/Public/HAL/PlatformIncludes.h" // 23 refs
#endif // BUILD_Win32_Profiling
#ifdef BUILD_Win32_Final
// system includes (0)
// project includes (22)
#include "Runtime/Core/ModuleExport.h" // 23 refs
#include "Runtime/Core/Public/Module.h" // 23 refs
#include "Runtime/RTTI/ModuleExport.h" // 23 refs
#include "Runtime/RTTI/Public/RTTI_fwd.h" // 23 refs
#include "Runtime/Core/Public/IO/StringView.h" // 23 refs
#include "Runtime/Core/Public/Container/Hash.h" // 23 refs
#include "Runtime/Core/Public/HAL/PlatformHash.h" // 23 refs
#include "Runtime/Core/Public/HAL/TargetPlatform.h" // 23 refs
#include "Runtime/Core/Public/HAL/TargetPlatform_fwd.h" // 23 refs
#include "Runtime/Core/Public/Diagnostic/Logger_fwd.h" // 23 refs
#include "Runtime/Core/Public/Memory/MemoryView.h" // 23 refs
#include "Runtime/Core/Public/HAL/Windows/WindowsPlatformHash.h" // 23 refs
#include "Runtime/Core/Public/HAL/Generic/GenericPlatformHash.h" // 23 refs
#include "Runtime/Core/Public/Memory/HashFunctions.h" // 23 refs
#include "Runtime/Core/Public/Memory/MemoryDomain.h" // 23 refs
#include "Runtime/Core/Public/Memory/RefPtr.h" // 23 refs
#include "Runtime/Core/Public/Allocator/Malloc.h" // 23 refs
#include "Runtime/Core/Public/HAL/PlatformDebug.h" // 23 refs
#include "Runtime/Core/Public/HAL/Generic/GenericPlatformDebug.h" // 23 refs
#include "Runtime/Core/Public/HAL/PlatformIncludes.h" // 23 refs
#include "Runtime/Core/Public/HAL/Windows/WindowsPlatformIncludes.h" // 23 refs
#include "Runtime/Core/Public/HAL/Generic/GenericPlatformIncludes.h" // 23 refs
#endif // BUILD_Win32_Final
#ifdef BUILD_Win64_Debug
// system includes (0)
// project includes (24)
#include "Runtime/Core/ModuleExport.h" // 23 refs
#include "Runtime/Core/Public/Module.h" // 23 refs
#include "Runtime/RTTI/ModuleExport.h" // 23 refs
#include "Runtime/RTTI/Public/RTTI_fwd.h" // 23 refs
#include "Runtime/Core/Public/IO/StringView.h" // 23 refs
#include "Runtime/Core/Public/Container/Hash.h" // 23 refs
#include "Runtime/Core/Public/HAL/PlatformHash.h" // 23 refs
#include "Runtime/Core/Public/HAL/TargetPlatform.h" // 23 refs
#include "Runtime/Core/Public/HAL/TargetPlatform_fwd.h" // 23 refs
#include "Runtime/Core/Public/Diagnostic/Logger_fwd.h" // 23 refs
#include "Runtime/Core/Public/Memory/MemoryView.h" // 23 refs
#include "Runtime/Core/Public/HAL/Windows/WindowsPlatformHash.h" // 23 refs
#include "Runtime/Core/Public/HAL/Generic/GenericPlatformHash.h" // 23 refs
#include "Runtime/Core/Public/Memory/HashFunctions.h" // 23 refs
#include "Runtime/Core/Public/Memory/MemoryDomain.h" // 23 refs
#include "Runtime/Core/Public/Memory/RefPtr.h" // 23 refs
#include "Runtime/Core/Public/Allocator/TrackingMalloc.h" // 23 refs
#include "Runtime/Core/Public/Allocator/Malloc.h" // 23 refs
#include "Runtime/Core/Public/HAL/PlatformDebug.h" // 23 refs
#include "Runtime/Core/Public/HAL/Generic/GenericPlatformDebug.h" // 23 refs
#include "Runtime/Core/Public/HAL/Windows/WindowsPlatformDebug.h" // 23 refs
#include "Runtime/Core/Public/HAL/Windows/WindowsPlatformIncludes.h" // 23 refs
#include "Runtime/Core/Public/HAL/Generic/GenericPlatformIncludes.h" // 23 refs
#include "Runtime/Core/Public/HAL/PlatformIncludes.h" // 23 refs
#endif // BUILD_Win64_Debug
#ifdef BUILD_Win64_FastDebug
// system includes (18)
#include <optional> // 1 refs
#include <iostream> // 2 refs
#include <DbgHelp.h> // 4 refs
#include <TlHelp32.h> // 3 refs
#include <initguid.h> // 1 refs
#include <KnownFolders.h> // 1 refs
#include <shellapi.h> // 2 refs
#include <Shlwapi.h> // 1 refs
#include <ShlObj.h> // 1 refs
#include <fcntl.h> // 2 refs
#include <io.h> // 2 refs
#include <Psapi.h> // 2 refs
#include <clocale> // 1 refs
#include <mbctype.h> // 1 refs
#include <VersionHelpers.h> // 1 refs
#include <timeapi.h> // 1 refs
#include <regex> // 1 refs
#include <condition_variable> // 2 refs
// project includes (0)
#endif // BUILD_Win64_FastDebug
#ifdef BUILD_Win64_Release
// system includes (0)
// project includes (24)
#include "Runtime/Core/ModuleExport.h" // 23 refs
#include "Runtime/Core/Public/Module.h" // 23 refs
#include "Runtime/RTTI/ModuleExport.h" // 23 refs
#include "Runtime/RTTI/Public/RTTI_fwd.h" // 23 refs
#include "Runtime/Core/Public/IO/StringView.h" // 23 refs
#include "Runtime/Core/Public/Container/Hash.h" // 23 refs
#include "Runtime/Core/Public/HAL/PlatformHash.h" // 23 refs
#include "Runtime/Core/Public/HAL/TargetPlatform.h" // 23 refs
#include "Runtime/Core/Public/HAL/TargetPlatform_fwd.h" // 23 refs
#include "Runtime/Core/Public/Diagnostic/Logger_fwd.h" // 23 refs
#include "Runtime/Core/Public/Memory/MemoryView.h" // 23 refs
#include "Runtime/Core/Public/HAL/Windows/WindowsPlatformHash.h" // 23 refs
#include "Runtime/Core/Public/HAL/Generic/GenericPlatformHash.h" // 23 refs
#include "Runtime/Core/Public/Memory/HashFunctions.h" // 23 refs
#include "Runtime/Core/Public/Memory/MemoryDomain.h" // 23 refs
#include "Runtime/Core/Public/Memory/RefPtr.h" // 23 refs
#include "Runtime/Core/Public/Allocator/TrackingMalloc.h" // 23 refs
#include "Runtime/Core/Public/Allocator/Malloc.h" // 23 refs
#include "Runtime/Core/Public/HAL/PlatformDebug.h" // 23 refs
#include "Runtime/Core/Public/HAL/Generic/GenericPlatformDebug.h" // 23 refs
#include "Runtime/Core/Public/HAL/Windows/WindowsPlatformDebug.h" // 23 refs
#include "Runtime/Core/Public/HAL/Windows/WindowsPlatformIncludes.h" // 23 refs
#include "Runtime/Core/Public/HAL/Generic/GenericPlatformIncludes.h" // 23 refs
#include "Runtime/Core/Public/HAL/PlatformIncludes.h" // 23 refs
#endif // BUILD_Win64_Release
#ifdef BUILD_Win64_Profiling
// system includes (0)
// project includes (23)
#include "Runtime/Core/ModuleExport.h" // 23 refs
#include "Runtime/Core/Public/Module.h" // 23 refs
#include "Runtime/RTTI/ModuleExport.h" // 23 refs
#include "Runtime/RTTI/Public/RTTI_fwd.h" // 23 refs
#include "Runtime/Core/Public/IO/StringView.h" // 23 refs
#include "Runtime/Core/Public/Container/Hash.h" // 23 refs
#include "Runtime/Core/Public/HAL/PlatformHash.h" // 23 refs
#include "Runtime/Core/Public/HAL/TargetPlatform.h" // 23 refs
#include "Runtime/Core/Public/HAL/TargetPlatform_fwd.h" // 23 refs
#include "Runtime/Core/Public/Diagnostic/Logger_fwd.h" // 23 refs
#include "Runtime/Core/Public/Memory/MemoryView.h" // 23 refs
#include "Runtime/Core/Public/HAL/Windows/WindowsPlatformHash.h" // 23 refs
#include "Runtime/Core/Public/HAL/Generic/GenericPlatformHash.h" // 23 refs
#include "Runtime/Core/Public/Memory/HashFunctions.h" // 23 refs
#include "Runtime/Core/Public/Memory/MemoryDomain.h" // 23 refs
#include "Runtime/Core/Public/Memory/RefPtr.h" // 23 refs
#include "Runtime/Core/Public/Allocator/Malloc.h" // 23 refs
#include "Runtime/Core/Public/HAL/PlatformDebug.h" // 23 refs
#include "Runtime/Core/Public/HAL/Generic/GenericPlatformDebug.h" // 23 refs
#include "Runtime/Core/Public/HAL/Windows/WindowsPlatformDebug.h" // 23 refs
#include "Runtime/Core/Public/HAL/Windows/WindowsPlatformIncludes.h" // 23 refs
#include "Runtime/Core/Public/HAL/Generic/GenericPlatformIncludes.h" // 23 refs
#include "Runtime/Core/Public/HAL/PlatformIncludes.h" // 23 refs
#endif // BUILD_Win64_Profiling
#ifdef BUILD_Win64_Final
// system includes (0)
// project includes (22)
#include "Runtime/Core/ModuleExport.h" // 23 refs
#include "Runtime/Core/Public/Module.h" // 23 refs
#include "Runtime/RTTI/ModuleExport.h" // 23 refs
#include "Runtime/RTTI/Public/RTTI_fwd.h" // 23 refs
#include "Runtime/Core/Public/IO/StringView.h" // 23 refs
#include "Runtime/Core/Public/Container/Hash.h" // 23 refs
#include "Runtime/Core/Public/HAL/PlatformHash.h" // 23 refs
#include "Runtime/Core/Public/HAL/TargetPlatform.h" // 23 refs
#include "Runtime/Core/Public/HAL/TargetPlatform_fwd.h" // 23 refs
#include "Runtime/Core/Public/Diagnostic/Logger_fwd.h" // 23 refs
#include "Runtime/Core/Public/Memory/MemoryView.h" // 23 refs
#include "Runtime/Core/Public/HAL/Windows/WindowsPlatformHash.h" // 23 refs
#include "Runtime/Core/Public/HAL/Generic/GenericPlatformHash.h" // 23 refs
#include "Runtime/Core/Public/Memory/HashFunctions.h" // 23 refs
#include "Runtime/Core/Public/Memory/MemoryDomain.h" // 23 refs
#include "Runtime/Core/Public/Memory/RefPtr.h" // 23 refs
#include "Runtime/Core/Public/Allocator/Malloc.h" // 23 refs
#include "Runtime/Core/Public/HAL/PlatformDebug.h" // 23 refs
#include "Runtime/Core/Public/HAL/Generic/GenericPlatformDebug.h" // 23 refs
#include "Runtime/Core/Public/HAL/PlatformIncludes.h" // 23 refs
#include "Runtime/Core/Public/HAL/Windows/WindowsPlatformIncludes.h" // 23 refs
#include "Runtime/Core/Public/HAL/Generic/GenericPlatformIncludes.h" // 23 refs
#endif // BUILD_Win64_Final
#endif //! PLATFORM_WINDOWS
