/*
** Generated by Build.rb v1.0.0
*/
#ifdef PLATFORM_WINDOWS
// Global system includes (47)
#include <stdio.h> // 18 refs
#include <algorithm> // 18 refs
#include <stdint.h> // 18 refs
#include <limits.h> // 18 refs
#include <limits> // 18 refs
#include <float.h> // 18 refs
#include <wchar.h> // 18 refs
#include <errno.h> // 18 refs
#include <sys/stat.h> // 18 refs
#include <sys/types.h> // 18 refs
#include <initializer_list> // 18 refs
#include <new> // 18 refs
#include <exception> // 18 refs
#include <type_traits> // 18 refs
#include <string.h> // 18 refs
#include <utility> // 18 refs
#include <atomic> // 16 refs
#include <memory> // 16 refs
#include <typeinfo> // 16 refs
#include <functional> // 16 refs
#include <tuple> // 16 refs
#include <cmath> // 16 refs
#include <list> // 16 refs
#include <stdexcept> // 16 refs
#include <iterator> // 16 refs
#include <locale.h> // 16 refs
#include <mutex> // 16 refs
#include <chrono> // 16 refs
#include <time.h> // 16 refs
#include <thread> // 16 refs
#include <intrin.h> // 9 refs
#include <immintrin.h> // 10 refs
#include <smmintrin.h> // 10 refs
#include <tmmintrin.h> // 10 refs
#include <pmmintrin.h> // 10 refs
#include <emmintrin.h> // 10 refs
#include <xmmintrin.h> // 10 refs
#include <malloc.h> // 10 refs
#include <cctype> // 5 refs
#include <cwctype> // 5 refs
#include <locale> // 6 refs
#include <comdef.h> // 8 refs
#include <Windows.h> // 8 refs
#include <winnt.h> // 8 refs
#include <comutil.h> // 8 refs
#include <tchar.h> // 8 refs
#include <memory.h> // 4 refs
// Global project includes (0)
#ifdef BUILD_Win32_FastDebug
// system includes (18)
#include <optional> // 1 refs
#include <iostream> // 1 refs
#include <DbgHelp.h> // 1 refs
#include <TlHelp32.h> // 1 refs
#include <initguid.h> // 1 refs
#include <KnownFolders.h> // 1 refs
#include <shellapi.h> // 1 refs
#include <Shlwapi.h> // 1 refs
#include <ShlObj.h> // 1 refs
#include <fcntl.h> // 1 refs
#include <io.h> // 1 refs
#include <Psapi.h> // 1 refs
#include <clocale> // 1 refs
#include <mbctype.h> // 1 refs
#include <VersionHelpers.h> // 1 refs
#include <timeapi.h> // 1 refs
#include <regex> // 1 refs
#include <condition_variable> // 1 refs
// project includes (0)
#endif // BUILD_Win32_FastDebug
#ifdef BUILD_Win64_FastDebug
// system includes (18)
#include <optional> // 1 refs
#include <iostream> // 1 refs
#include <DbgHelp.h> // 1 refs
#include <TlHelp32.h> // 1 refs
#include <initguid.h> // 1 refs
#include <KnownFolders.h> // 1 refs
#include <shellapi.h> // 1 refs
#include <Shlwapi.h> // 1 refs
#include <ShlObj.h> // 1 refs
#include <fcntl.h> // 1 refs
#include <io.h> // 1 refs
#include <Psapi.h> // 1 refs
#include <clocale> // 1 refs
#include <mbctype.h> // 1 refs
#include <VersionHelpers.h> // 1 refs
#include <timeapi.h> // 1 refs
#include <regex> // 1 refs
#include <condition_variable> // 1 refs
// project includes (0)
#endif // BUILD_Win64_FastDebug
#endif //! PLATFORM_WINDOWS
