/*
// Generated by PCHRefactor.rb v1.0 for target <Core.ContentGenerator>
//------------------------------------------------------------------------------
// Date : 2017-08-22 12:50:52 UTC
*/

// Processed dependencies for Core.ContentGenerator-Win32-Debug : 53 std, 43 sdk, 226 prj, 10 src
// Processed dependencies for Core.ContentGenerator-Win32-FastDebug : 53 std, 43 sdk, 226 prj, 10 src
// Processed dependencies for Core.ContentGenerator-Win32-Release : 53 std, 43 sdk, 226 prj, 10 src
// Processed dependencies for Core.ContentGenerator-Win32-Profiling : 53 std, 43 sdk, 226 prj, 10 src
// Processed dependencies for Core.ContentGenerator-Win32-Final : 53 std, 43 sdk, 226 prj, 10 src
// Processed dependencies for Core.ContentGenerator-Win64-Debug : 53 std, 42 sdk, 226 prj, 10 src
// Processed dependencies for Core.ContentGenerator-Win64-FastDebug : 53 std, 42 sdk, 226 prj, 10 src
// Processed dependencies for Core.ContentGenerator-Win64-Release : 53 std, 42 sdk, 226 prj, 10 src
// Processed dependencies for Core.ContentGenerator-Win64-Profiling : 53 std, 42 sdk, 226 prj, 10 src
// Processed dependencies for Core.ContentGenerator-Win64-Final : 53 std, 42 sdk, 226 prj, 10 src

/*
// Standard headers
//------------------------------------------------------------------------------
*/
#include <algorithm>
#include <cstdint>
#include <cstdlib>
#include <limits>
#include <cfloat>
#include <climits>
#include <cmath>
#include <cwchar>
#include <cstddef>
#include <initializer_list>
#include <new>
#include <exception>
#include <type_traits>
#include <utility>
#include <iosfwd>
#include <cstdio>
#include <cstring>
#include <atomic>
#include <memory>
#include <typeinfo>
#include <functional>
#include <tuple>
#include <stdexcept>
#include <iomanip>
#include <istream>
#include <ostream>
#include <ios>
#include <streambuf>
#include <system_error>
#include <cerrno>
#include <ctime>
#include <iterator>
#include <mutex>
#include <chrono>
#include <ratio>
#include <thread>
#include <cctype>
#include <cwctype>
#include <locale>
#include <string>
#include <iostream>
#include <sstream>
#include <shared_mutex>
#include <condition_variable>
#include <unordered_map>
#include <list>
#include <vector>
#include <regex>
#include <queue>
#include <deque>
#include <fstream>
#include <bitset>
#include <unordered_set>

/*
// SDK headers
//------------------------------------------------------------------------------
*/
#if 0 // dummy
#elif defined(BUILDCONFIG_Win32_Debug) || defined(BUILDCONFIG_Win32_FastDebug) || defined(BUILDCONFIG_Win32_Release) || defined(BUILDCONFIG_Win32_Profiling) || defined(BUILDCONFIG_Win32_Final)
#    include "excpt.h"
#    include "vcruntime.h"
#    include "sal.h"
#    include "ConcurrencySal.h"
#    include "vadefs.h"
#    include "stdarg.h"
#    include "vcruntime_string.h"
#    include "yvals.h"
#    include "xkeycheck.h"
#    include "crtdefs.h"
#    include "use_ansi.h"
#    include "stdint.h"
#    include "limits.h"
#    include "ymath.h"
#    include "xtgmath.h"
#    include "vcruntime_new.h"
#    include "vcruntime_new_debug.h"
#    include "xatomic0.h"
#    include "intrin0.h"
#    include "xatomic.h"
#    include "vcruntime_typeinfo.h"
#    include "vcruntime_exception.h"
#    include "eh.h"
#    include "intrin.h"
#    include "setjmp.h"
#    include "immintrin.h"
#    include "wmmintrin.h"
#    include "nmmintrin.h"
#    include "smmintrin.h"
#    include "tmmintrin.h"
#    include "pmmintrin.h"
#    include "emmintrin.h"
#    include "xmmintrin.h"
#    include "mmintrin.h"
#    include "zmmintrin.h"
#    include "ammintrin.h"
#    include "mm3dnow.h"
#    include "xlocinfo.h"
#    include "xstring_insert.h"
#    include "comdef.h"
#    include "comutil.h"
#    include "comip.h"
#    include "comdefsp.h"
#elif defined(BUILDCONFIG_Win64_Debug) || defined(BUILDCONFIG_Win64_FastDebug) || defined(BUILDCONFIG_Win64_Release) || defined(BUILDCONFIG_Win64_Profiling) || defined(BUILDCONFIG_Win64_Final)
#    include "excpt.h"
#    include "vcruntime.h"
#    include "sal.h"
#    include "ConcurrencySal.h"
#    include "vadefs.h"
#    include "stdarg.h"
#    include "vcruntime_string.h"
#    include "yvals.h"
#    include "xkeycheck.h"
#    include "crtdefs.h"
#    include "use_ansi.h"
#    include "stdint.h"
#    include "limits.h"
#    include "ymath.h"
#    include "xtgmath.h"
#    include "vcruntime_new.h"
#    include "vcruntime_new_debug.h"
#    include "xatomic0.h"
#    include "intrin0.h"
#    include "xatomic.h"
#    include "vcruntime_typeinfo.h"
#    include "vcruntime_exception.h"
#    include "eh.h"
#    include "intrin.h"
#    include "setjmp.h"
#    include "immintrin.h"
#    include "wmmintrin.h"
#    include "nmmintrin.h"
#    include "smmintrin.h"
#    include "tmmintrin.h"
#    include "pmmintrin.h"
#    include "emmintrin.h"
#    include "xmmintrin.h"
#    include "mmintrin.h"
#    include "zmmintrin.h"
#    include "ammintrin.h"
#    include "xlocinfo.h"
#    include "xstring_insert.h"
#    include "comdef.h"
#    include "comutil.h"
#    include "comip.h"
#    include "comdefsp.h"
#else
#     error "unknown build config"
#endif

/*
// Project headers
//------------------------------------------------------------------------------
*/
#if 0 // dummy
#elif defined(BUILDCONFIG_Win32_Debug) || defined(BUILDCONFIG_Win32_FastDebug) || defined(BUILDCONFIG_Win64_Debug) || defined(BUILDCONFIG_Win64_FastDebug)
#    include "Core/Misc/Platform_Windows.h" // 2870% 287/10
#    include "Core/Core.h" // 2880% 288/10
#    include "Core/Meta/Aliases.h" // 2880% 288/10
#    include "Core/Meta/Alignment.h" // 2880% 288/10
#    include "Core/Meta/TypeTraits.h" // 2880% 288/10
#    include "Core/Meta/Assert.h" // 2880% 288/10
#    include "Core/Diagnostic/Exception.h" // 2880% 288/10
#    include "Core/Meta/BitCount.h" // 2880% 288/10
#    include "Core/Meta/Cast.h" // 2880% 288/10
#    include "Core/Meta/TypeHash.h" // 2880% 288/10
#    include "Core/Meta/Hash_fwd.h" // 2880% 288/10
#    include "Core/Meta/Delete.h" // 2880% 288/10
#    include "Core/Meta/Enum.h" // 2880% 288/10
#    include "Core/Meta/ForRange.h" // 2880% 288/10
#    include "Core/Meta/Iterator.h" // 2880% 288/10
#    include "Core/Meta/Warnings.h" // 2880% 288/10
#    include "Core/Meta/NumericLimits.h" // 2880% 288/10
#    include "Core/Meta/OneTimeInitialize.h" // 2880% 288/10
#    include "Core/Meta/StronglyTyped.h" // 2880% 288/10
#    include "Core/Meta/ThreadResource.h" // 2880% 288/10
#    include "Core/Allocator/Alloca.h" // 2200% 220/10
#    include "Core/Memory/MemoryView.h" // 2500% 250/10
#    include "Core/Memory/UniquePtr.h" // 2210% 221/10
#    include "Core/Memory/RefPtr.h" // 2240% 224/10
#    include "Core/Memory/MemoryDomain.h" // 2400% 240/10
#    include "Core/Memory/MemoryTracking.h" // 2190% 219/10
#    include "Core/IO/FormatHelpers.h" // 2190% 219/10
#    include "Core/IO/StringView.h" // 2450% 245/10
#    include "Core/Container/Hash.h" // 2480% 248/10
#    include "Core/Memory/HashFunctions.h" // 2520% 252/10
#    include "Core/Meta/Singleton.h" // 2230% 223/10
#    include "Core/Meta/AlignedStorage.h" // 2250% 225/10
#    include "Core/Allocator/Heap.h" // 2200% 220/10
#    include "Core/Allocator/Malloc.h" // 2210% 221/10
#    include "Core/Allocator/New.h" // 2180% 218/10
#    include "Core/Allocator/PoolAllocatorTag.h" // 2370% 237/10
#    include "Core/Allocator/SingletonPoolAllocator.h" // 120% 12/10
#    include "Core/Allocator/AllocatorBase.h" // 2170% 217/10
#    include "Core/Memory/SegregatedMemoryPool.h" // 720% 72/10
#    include "Core/Allocator/ThreadLocalAllocator.h" // 2170% 217/10
#    include "Core/Allocator/HeapAllocator.h" // 2170% 217/10
#    include "Core/Memory/MemoryPool.h" // 850% 85/10
#    include "Core/Container/IntrusiveList.h" // 960% 96/10
#    include "Core/Thread/AtomicSpinLock.h" // 910% 91/10
#    include "Core/Meta/AutoSingleton.h" // 740% 74/10
#    include "Core/IO/Format.h" // 1250% 125/10
#    include "Core/IO/String.h" // 1900% 190/10
#    include "Core/Allocator/Allocation.h" // 2170% 217/10
#    include "Core/Allocator/Mallocator.h" // 2170% 217/10
#    include "Core/Allocator/PoolAllocator.h" // 2180% 218/10
#    include "Core/Allocator/TrackingAllocator.h" // 2170% 217/10
#    include "Core/IO/Stream.h" // 1900% 190/10
#    include "Core/Memory/UniqueView.h" // 1920% 192/10
#    include "Core/Diagnostic/Logger.h" // 1160% 116/10
#    include "Core/Allocator/PoolAllocatorTag-impl.h" // 180% 18/10
#    include "Core/Diagnostic/LastError.h" // 90% 9/10
#    include "Core/Misc/TargetPlatform.h" // 1210% 121/10
#    include "Core/Color/Color.h" // 440% 44/10
#    include "Core/Color/Color_fwd.h" // 900% 90/10
#    include "Core/Maths/ScalarVector_fwd.h" // 1390% 139/10
#    include "Core/Maths/PackingHelpers.h" // 1110% 111/10
#    include "Core/Maths/Packing_fwd.h" // 1110% 111/10
#    include "Core/Maths/MathHelpers.h" // 1160% 116/10
#    include "Core/Maths/PackedVectors.h" // 700% 70/10
#    include "Core/Maths/ScalarVector.h" // 1230% 123/10
#    include "Core/Maths/ScalarVectorHelpers.h" // 1100% 110/10
#    include "Core/Misc/Endianness.h" // 1120% 112/10
#    include "Core/Container/BitSet.h" // 140% 14/10
#    include "Core/Thread/ReadWriteLock.h" // 390% 39/10
#    include "Core/Diagnostic/CurrentProcess.h" // 100% 10/10
#    include "Core/Time/Timepoint.h" // 140% 14/10
#    include "Core/Maths/Units.h" // 270% 27/10
#    include "Core/Container/Vector.h" // 1460% 146/10
#    include "Core/Allocator/InSituAllocator.h" // 1460% 146/10
#    include "Core/IO/FileSystem.h" // 120% 12/10
#    include "Core/IO/FS/FileSystemProperties.h" // 760% 76/10
#    include "Core/IO/FS/Basename.h" // 690% 69/10
#    include "Core/IO/FS/BasenameNoExt.h" // 700% 70/10
#    include "Core/IO/FS/FileSystemToken.h" // 740% 74/10
#    include "Core/Container/Token.h" // 1100% 110/10
#    include "Core/Container/HashSet.h" // 1100% 110/10
#    include "Core/Container/HashTable.h" // 1140% 114/10
#    include "Core/Container/Pair.h" // 1280% 128/10
#    include "Core/Container/Stack.h" // 1200% 120/10
#    include "Core/IO/FS/FileSystemToken_fwd.h" // 750% 75/10
#    include "Core/IO/FS/Extname.h" // 700% 70/10
#    include "Core/IO/FS/Dirname.h" // 700% 70/10
#    include "Core/IO/FS/Dirpath.h" // 690% 69/10
#    include "Core/IO/FS/Filename.h" // 680% 68/10
#    include "Core/IO/FS/MountingPoint.h" // 700% 70/10
#    include "Core/IO/VirtualFileSystem.h" // 180% 18/10
#    include "Core/IO/VirtualFileSystem_fwd.h" // 240% 24/10
#    include "Core/IO/FileSystem_fwd.h" // 390% 39/10
#    include "Core/IO/VFS/VirtualFileSystemPolicies.h" // 240% 24/10
#    include "Core/Meta/Function.h" // 320% 32/10
#    include "Core/IO/VFS/VirtualFileSystemTrie.h" // 190% 19/10
#    include "Core/Container/AssociativeVector.h" // 870% 87/10
#    include "Core/Memory/Compression.h" // 200% 20/10
#    include "Core/Memory/MemoryProvider.h" // 80% 8/10
#    include "Core/IO/StreamProvider.h" // 410% 41/10
#    include "Core/IO/FS/ConstNames.h" // 100% 10/10
#    include "Core/Time/Timestamp.h" // 390% 39/10
#    include "Core/Allocator/PoolAllocator-impl.h" // 670% 67/10
#    include "Core/Container/RawStorage.h" // 850% 85/10
#    include "Core/IO/VFS/VirtualFileSystemStream.h" // 110% 11/10
#    include "Core/Maths/ScalarBoundingBox.h" // 460% 46/10
#    include "Core/Maths/ScalarBoundingBox_fwd.h" // 870% 87/10
#    include "Core/Meta/Delegate.h" // 750% 75/10
#    include "Core/Meta/PointerWFlags.h" // 770% 77/10
#    include "Core/Meta/BitField.h" // 990% 99/10
#    include "Core/Maths/Collision.h" // 170% 17/10
#    include "Core/Maths/Plane.h" // 130% 13/10
#    include "Core/Maths/ScalarMatrix_fwd.h" // 820% 82/10
#    include "Core/Maths/ScalarMatrix.h" // 770% 77/10
#    include "Core/Maths/ScalarMatrixHelpers.h" // 100% 10/10
#    include "Core/Maths/Quaternion.h" // 140% 14/10
#    include "Core/Maths/QuaternionHelpers.h" // 120% 12/10
#    include "Core/Memory/WeakPtr.h" // 550% 55/10
#    include "Core/Misc/ServiceContainer.h" // 80% 8/10
#    include "Core/Container/FlatMap.h" // 90% 9/10
#    include "Core/Thread/Task/Task.h" // 110% 11/10
#    include "Core/Thread/Task/TaskManager.h" // 110% 11/10
#    include "Core/Thread/ThreadContext.h" // 140% 14/10
#    include "Core/Thread/ThreadPool.h" // 80% 8/10
#    include "Core/Time/DateTime.h" // 360% 36/10
#    include "Core.RTTI/RTTI.h" // 750% 75/10
#    include "Core.RTTI/MetaClass.h" // 310% 31/10
#    include "Core.RTTI/Typedefs.h" // 380% 38/10
#    include "Core.RTTI/MetaNamespace.h" // 320% 32/10
#    include "Core/Container/HashMap.h" // 510% 51/10
#    include "Core.RTTI/MetaObject.h" // 290% 29/10
#    include "Core.RTTI/MetaType.h" // 360% 36/10
#    include "Core.RTTI/MetaTypeVirtualTraits.h" // 360% 36/10
#    include "Core.RTTI/MetaProperty.h" // 230% 23/10
#    include "Core.RTTI/MetaPropertyAccessor.h" // 230% 23/10
#    include "Core.RTTI/Exceptions.h" // 230% 23/10
#    include "Core.RTTI/MetaAtom.h" // 340% 34/10
#    include "Core.RTTI/RTTI_fwd.h" // 730% 73/10
#    include "Core.RTTI/MetaObjectHelpers.h" // 730% 73/10
#    include "Core.RTTI/MetaAtomVisitor.h" // 340% 34/10
#    include "Core.RTTI/MetaTypeTraits.h" // 340% 34/10
#    include "Core/Container/Token_fwd.h" // 340% 34/10
#    include "Core.RTTI/MetaTypePromote.h" // 340% 34/10
#    include "Core.RTTI/MetaDatabase.h" // 80% 8/10
#    include "Core.RTTI/MetaFunction.h" // 100% 10/10
#    include "Core/Container/Tuple.h" // 160% 16/10
#    include "Core.RTTI/RTTI_Namespace.h" // 150% 15/10
#    include "Core.RTTI/MetaTransaction.h" // 80% 8/10
#    include "Core.RTTI/RTTI_extern.h" // 90% 9/10
#    include "Core.Serialize/Serialize.h" // 310% 31/10
#    include "Core.Serialize/Exceptions.h" // 230% 23/10
#    include "Core/Memory/MemoryStream.h" // 220% 22/10
#    include "Core.Serialize/Lexer/Location.h" // 240% 24/10
#    include "Core/Container/StringHashMap.h" // 100% 10/10
#    include "Core.Serialize/Lexer/LookAheadReader.h" // 90% 9/10
#    include "Core.Serialize/Lexer/Match.h" // 120% 12/10
#    include "Core.Serialize/Lexer/Symbol.h" // 140% 14/10
#    include "Core.Serialize/Parser/ParseContext.h" // 80% 8/10
#    include "Core.Serialize/Parser/ParseExpression.h" // 80% 8/10
#    include "Core.Serialize/Parser/ParseItem.h" // 90% 9/10
#    include "Core.Serialize/Parser/ParseList.h" // 90% 9/10
#    include "core.serialize/XML/XML.h" // 100% 10/10
#    include "Core.Network/Network.h" // 200% 20/10
#    include "Core.Network/Socket/Address.h" // 120% 12/10
#    include "core.network/socket/SocketBuffered.h" // 90% 9/10
#    include "core.network/Socket/Socket.h" // 110% 11/10
#    include "core.network/Name.h" // 90% 9/10
#    include "Core.Lattice/Lattice.h" // 140% 14/10
#    include "Core.Graphics/Value.h" // 340% 34/10
#    include "Core.Graphics/Graphics.h" // 950% 95/10
#    include "core.graphics/Name.h" // 360% 36/10
#    include "Core.Lattice/GenericMesh.h" // 100% 10/10
#    include "Core.Lattice/GenericMesh_fwd.h" // 100% 10/10
#    include "core.graphics/Device/Geometry/VertexDeclaration.h" // 200% 20/10
#    include "Core.Graphics/ValueBlock.h" // 260% 26/10
#    include "Core.Graphics/Device/DeviceAPIDependantEntity.h" // 530% 53/10
#    include "Core.Graphics/Device/DeviceRevision.h" // 570% 57/10
#    include "Core.Graphics/Device/DeviceResource.h" // 540% 54/10
#    include "Core.Graphics/Device/DeviceResourceType.h" // 550% 55/10
#    include "core.graphics/Device/State/SamplerState.h" // 100% 10/10
#    include "Core.Graphics/Device/Geometry/IndexElementSize.h" // 80% 8/10
#    include "Core.Pixmap/Pixmap.h" // 120% 12/10
#    include "Core.Pixmap/PixelStorage.h" // 80% 8/10
#    include "Core.Pixmap/Pixmap_fwd.h" // 90% 9/10
#    include "Core.Graphics/Device/AbstractDeviceAPIEncapsulator.h" // 250% 25/10
#    include "Core.Graphics/Device/DeviceAPI.h" // 480% 48/10
#    include "Core.Graphics/Device/DeviceAPI_fwd.h" // 490% 49/10
#    include "Core.Graphics/Device/IDeviceAPIContext.h" // 480% 48/10
#    include "Core.Graphics/Device/IDeviceAPIDiagnostics.h" // 490% 49/10
#    include "Core.Graphics/Device/DeviceDiagnostics.h" // 510% 51/10
#    include "Core.Graphics/Device/IDeviceAPIEncapsulator.h" // 490% 49/10
#    include "Core/Maths/ScalarRectangle_fwd.h" // 510% 51/10
#    include "Core.Graphics/Device/PresentationParameters.h" // 300% 30/10
#    include "Core/Maths/ScalarRectangle.h" // 300% 30/10
#    include "Core.Graphics/Device/DeviceEncapsulator.h" // 390% 39/10
#    include "Core.Graphics/Device/DeviceStatus.h" // 400% 40/10
#    include "Core/Meta/Event.h" // 410% 41/10
#    include "Core.Graphics/Device/DeviceEncapsulatorException.h" // 160% 16/10
#    include "Core.Graphics/Device/DeviceResourceBuffer.h" // 290% 29/10
#    include "Core.Graphics/Device/Pool/DeviceResourceSharable.h" // 310% 31/10
#    include "Core.Graphics/Device/Pool/DeviceSharedEntityKey.h" // 310% 31/10
#    include "Core.Graphics/Device/Geometry/PrimitiveType.h" // 80% 8/10
#    include "Core.Graphics/Device/Shader/ShaderProgram.h" // 130% 13/10
#    include "Core.Graphics/Device/Shader/ShaderProfile.h" // 140% 14/10
#    include "core.graphics/Device/State/BlendState.h" // 80% 8/10
#    include "core.graphics/Device/State/DepthStencilState.h" // 80% 8/10
#    include "core.graphics/Device/State/RasterizerState.h" // 80% 8/10
#    include "Core.Graphics/Device/Texture/Texture2D.h" // 120% 12/10
#    include "Core.Graphics/Device/Texture/Texture.h" // 150% 15/10
#    include "Core/Memory/ComPtr.h" // 200% 20/10
#    include "Core.Graphics/DirectX11/DX11DeviceAPIEncapsulator.h" // 190% 19/10
#    include "Core.Graphics/DirectX11/DX11Includes.h" // 220% 22/10
#    include "Core.Graphics/DirectX11/DX11DeviceWrapper.h" // 190% 19/10
#    include "Core.Graphics/Device/Shader/ShaderCompiled.h" // 80% 8/10
#    include "Core.Graphics/Device/Shader/ConstantBufferLayout.h" // 110% 11/10
#    include "core.graphics/Device/Texture/SurfaceFormat.h" // 160% 16/10
#    include "core.graphics/window/BasicWindow.h" // 110% 11/10
#    include "Core.Graphics/Window/WindowMessage.h" // 120% 12/10
#    include "core.graphics/window/WindowMessageHandler.h" // 110% 11/10
#    include "Core.ContentPipeline/ContentPipeline.h" // 110% 11/10
#    include "Core.RTTI/RTTI_Macros.h" // 90% 9/10
#    include "Core.RTTI/RTTI_Macros-impl.h" // 80% 8/10
#    include "Core.Application/Application.h" // 230% 23/10
#    include "Core.Application/Input/GamepadButton.h" // 80% 8/10
#    include "Core.Application/Input/KeyboardKey.h" // 80% 8/10
#    include "Core.Application/Input/MouseButton.h" // 80% 8/10
#elif defined(BUILDCONFIG_Win32_Release) || defined(BUILDCONFIG_Win64_Release)
#    include "Core/Misc/Platform_Windows.h" // 2870% 287/10
#    include "Core/Core.h" // 2880% 288/10
#    include "Core/Meta/Aliases.h" // 2880% 288/10
#    include "Core/Meta/Alignment.h" // 2880% 288/10
#    include "Core/Meta/TypeTraits.h" // 2880% 288/10
#    include "Core/Meta/Assert.h" // 2880% 288/10
#    include "Core/Diagnostic/Exception.h" // 2880% 288/10
#    include "Core/Meta/BitCount.h" // 2880% 288/10
#    include "Core/Meta/Cast.h" // 2880% 288/10
#    include "Core/Meta/TypeHash.h" // 2880% 288/10
#    include "Core/Meta/Hash_fwd.h" // 2880% 288/10
#    include "Core/Meta/Delete.h" // 2880% 288/10
#    include "Core/Meta/Enum.h" // 2880% 288/10
#    include "Core/Meta/ForRange.h" // 2880% 288/10
#    include "Core/Meta/Iterator.h" // 2880% 288/10
#    include "Core/Meta/Warnings.h" // 2880% 288/10
#    include "Core/Meta/NumericLimits.h" // 2880% 288/10
#    include "Core/Meta/OneTimeInitialize.h" // 2880% 288/10
#    include "Core/Meta/StronglyTyped.h" // 2880% 288/10
#    include "Core/Meta/ThreadResource.h" // 2880% 288/10
#    include "Core/Allocator/Alloca.h" // 2200% 220/10
#    include "Core/Memory/MemoryView.h" // 2490% 249/10
#    include "Core/Memory/UniquePtr.h" // 2210% 221/10
#    include "Core/Memory/RefPtr.h" // 2240% 224/10
#    include "Core/Memory/MemoryDomain.h" // 2400% 240/10
#    include "Core/Memory/MemoryTracking.h" // 2190% 219/10
#    include "Core/IO/FormatHelpers.h" // 2190% 219/10
#    include "Core/IO/StringView.h" // 2450% 245/10
#    include "Core/Container/Hash.h" // 2480% 248/10
#    include "Core/Memory/HashFunctions.h" // 2520% 252/10
#    include "Core/Meta/Singleton.h" // 2230% 223/10
#    include "Core/Meta/AlignedStorage.h" // 2250% 225/10
#    include "Core/Allocator/Heap.h" // 2200% 220/10
#    include "Core/Allocator/Malloc.h" // 2210% 221/10
#    include "Core/Allocator/New.h" // 2180% 218/10
#    include "Core/Allocator/PoolAllocatorTag.h" // 2370% 237/10
#    include "Core/Allocator/SingletonPoolAllocator.h" // 120% 12/10
#    include "Core/Allocator/AllocatorBase.h" // 2170% 217/10
#    include "Core/Memory/SegregatedMemoryPool.h" // 720% 72/10
#    include "Core/Allocator/ThreadLocalAllocator.h" // 2170% 217/10
#    include "Core/Allocator/HeapAllocator.h" // 2170% 217/10
#    include "Core/Memory/MemoryPool.h" // 850% 85/10
#    include "Core/Container/IntrusiveList.h" // 960% 96/10
#    include "Core/Thread/AtomicSpinLock.h" // 910% 91/10
#    include "Core/Meta/AutoSingleton.h" // 740% 74/10
#    include "Core/IO/Format.h" // 1250% 125/10
#    include "Core/IO/String.h" // 1900% 190/10
#    include "Core/Allocator/Allocation.h" // 2170% 217/10
#    include "Core/Allocator/Mallocator.h" // 2170% 217/10
#    include "Core/Allocator/PoolAllocator.h" // 2180% 218/10
#    include "Core/Allocator/TrackingAllocator.h" // 2170% 217/10
#    include "Core/IO/Stream.h" // 1900% 190/10
#    include "Core/Memory/UniqueView.h" // 1920% 192/10
#    include "Core/Allocator/PoolAllocatorTag-impl.h" // 180% 18/10
#    include "Core/Diagnostic/LastError.h" // 90% 9/10
#    include "Core/Misc/TargetPlatform.h" // 1210% 121/10
#    include "Core/Color/Color.h" // 440% 44/10
#    include "Core/Color/Color_fwd.h" // 900% 90/10
#    include "Core/Maths/ScalarVector_fwd.h" // 1390% 139/10
#    include "Core/Maths/PackingHelpers.h" // 1110% 111/10
#    include "Core/Maths/Packing_fwd.h" // 1110% 111/10
#    include "Core/Maths/MathHelpers.h" // 1160% 116/10
#    include "Core/Maths/PackedVectors.h" // 700% 70/10
#    include "Core/Maths/ScalarVector.h" // 1230% 123/10
#    include "Core/Maths/ScalarVectorHelpers.h" // 1100% 110/10
#    include "Core/Misc/Endianness.h" // 1120% 112/10
#    include "Core/Container/BitSet.h" // 140% 14/10
#    include "Core/Diagnostic/Logger.h" // 610% 61/10
#    include "Core/Thread/ReadWriteLock.h" // 390% 39/10
#    include "Core/Diagnostic/CurrentProcess.h" // 100% 10/10
#    include "Core/Time/Timepoint.h" // 140% 14/10
#    include "Core/Maths/Units.h" // 270% 27/10
#    include "Core/Container/Vector.h" // 1460% 146/10
#    include "Core/Allocator/InSituAllocator.h" // 1460% 146/10
#    include "Core/IO/FileSystem.h" // 120% 12/10
#    include "Core/IO/FS/FileSystemProperties.h" // 760% 76/10
#    include "Core/IO/FS/Basename.h" // 690% 69/10
#    include "Core/IO/FS/BasenameNoExt.h" // 700% 70/10
#    include "Core/IO/FS/FileSystemToken.h" // 740% 74/10
#    include "Core/Container/Token.h" // 1100% 110/10
#    include "Core/Container/HashSet.h" // 1100% 110/10
#    include "Core/Container/HashTable.h" // 1140% 114/10
#    include "Core/Container/Pair.h" // 1280% 128/10
#    include "Core/Container/Stack.h" // 1200% 120/10
#    include "Core/IO/FS/FileSystemToken_fwd.h" // 750% 75/10
#    include "Core/IO/FS/Extname.h" // 700% 70/10
#    include "Core/IO/FS/Dirname.h" // 700% 70/10
#    include "Core/IO/FS/Dirpath.h" // 690% 69/10
#    include "Core/IO/FS/Filename.h" // 680% 68/10
#    include "Core/IO/FS/MountingPoint.h" // 700% 70/10
#    include "Core/IO/VirtualFileSystem.h" // 180% 18/10
#    include "Core/IO/VirtualFileSystem_fwd.h" // 240% 24/10
#    include "Core/IO/FileSystem_fwd.h" // 390% 39/10
#    include "Core/IO/VFS/VirtualFileSystemPolicies.h" // 240% 24/10
#    include "Core/Meta/Function.h" // 320% 32/10
#    include "Core/IO/VFS/VirtualFileSystemTrie.h" // 190% 19/10
#    include "Core/Container/AssociativeVector.h" // 870% 87/10
#    include "Core/Memory/Compression.h" // 200% 20/10
#    include "Core/Memory/MemoryProvider.h" // 80% 8/10
#    include "Core/IO/StreamProvider.h" // 410% 41/10
#    include "Core/IO/FS/ConstNames.h" // 100% 10/10
#    include "Core/Time/Timestamp.h" // 390% 39/10
#    include "Core/Allocator/PoolAllocator-impl.h" // 670% 67/10
#    include "Core/Container/RawStorage.h" // 850% 85/10
#    include "Core/IO/VFS/VirtualFileSystemStream.h" // 110% 11/10
#    include "Core/Maths/ScalarBoundingBox.h" // 460% 46/10
#    include "Core/Maths/ScalarBoundingBox_fwd.h" // 860% 86/10
#    include "Core/Meta/Delegate.h" // 750% 75/10
#    include "Core/Meta/PointerWFlags.h" // 770% 77/10
#    include "Core/Meta/BitField.h" // 990% 99/10
#    include "Core/Maths/Collision.h" // 160% 16/10
#    include "Core/Maths/Plane.h" // 120% 12/10
#    include "Core/Maths/ScalarMatrix_fwd.h" // 820% 82/10
#    include "Core/Maths/ScalarMatrix.h" // 770% 77/10
#    include "Core/Maths/ScalarMatrixHelpers.h" // 90% 9/10
#    include "Core/Maths/Quaternion.h" // 130% 13/10
#    include "Core/Maths/QuaternionHelpers.h" // 110% 11/10
#    include "Core/Memory/WeakPtr.h" // 550% 55/10
#    include "Core/Misc/ServiceContainer.h" // 80% 8/10
#    include "Core/Container/FlatMap.h" // 90% 9/10
#    include "Core/Thread/Task/Task.h" // 110% 11/10
#    include "Core/Thread/Task/TaskManager.h" // 110% 11/10
#    include "Core/Thread/ThreadContext.h" // 140% 14/10
#    include "Core/Thread/ThreadPool.h" // 80% 8/10
#    include "Core/Time/DateTime.h" // 360% 36/10
#    include "Core.RTTI/RTTI.h" // 750% 75/10
#    include "Core.RTTI/MetaClass.h" // 310% 31/10
#    include "Core.RTTI/Typedefs.h" // 380% 38/10
#    include "Core.RTTI/MetaNamespace.h" // 320% 32/10
#    include "Core/Container/HashMap.h" // 510% 51/10
#    include "Core.RTTI/MetaObject.h" // 290% 29/10
#    include "Core.RTTI/MetaType.h" // 360% 36/10
#    include "Core.RTTI/MetaTypeVirtualTraits.h" // 360% 36/10
#    include "Core.RTTI/MetaProperty.h" // 230% 23/10
#    include "Core.RTTI/MetaPropertyAccessor.h" // 230% 23/10
#    include "Core.RTTI/Exceptions.h" // 230% 23/10
#    include "Core.RTTI/MetaAtom.h" // 340% 34/10
#    include "Core.RTTI/RTTI_fwd.h" // 730% 73/10
#    include "Core.RTTI/MetaObjectHelpers.h" // 730% 73/10
#    include "Core.RTTI/MetaAtomVisitor.h" // 340% 34/10
#    include "Core.RTTI/MetaTypeTraits.h" // 340% 34/10
#    include "Core/Container/Token_fwd.h" // 340% 34/10
#    include "Core.RTTI/MetaTypePromote.h" // 340% 34/10
#    include "Core.RTTI/MetaDatabase.h" // 80% 8/10
#    include "Core.RTTI/MetaFunction.h" // 100% 10/10
#    include "Core/Container/Tuple.h" // 160% 16/10
#    include "Core.RTTI/RTTI_Namespace.h" // 150% 15/10
#    include "Core.RTTI/MetaTransaction.h" // 80% 8/10
#    include "Core.RTTI/RTTI_extern.h" // 90% 9/10
#    include "Core.Serialize/Serialize.h" // 310% 31/10
#    include "Core.Serialize/Exceptions.h" // 230% 23/10
#    include "Core/Memory/MemoryStream.h" // 220% 22/10
#    include "Core.Serialize/Lexer/Location.h" // 240% 24/10
#    include "Core/Container/StringHashMap.h" // 100% 10/10
#    include "Core.Serialize/Lexer/LookAheadReader.h" // 90% 9/10
#    include "Core.Serialize/Lexer/Match.h" // 120% 12/10
#    include "Core.Serialize/Lexer/Symbol.h" // 140% 14/10
#    include "Core.Serialize/Parser/ParseContext.h" // 80% 8/10
#    include "Core.Serialize/Parser/ParseExpression.h" // 80% 8/10
#    include "Core.Serialize/Parser/ParseItem.h" // 90% 9/10
#    include "Core.Serialize/Parser/ParseList.h" // 90% 9/10
#    include "core.serialize/XML/XML.h" // 100% 10/10
#    include "Core.Network/Network.h" // 200% 20/10
#    include "Core.Network/Socket/Address.h" // 120% 12/10
#    include "core.network/socket/SocketBuffered.h" // 90% 9/10
#    include "core.network/Socket/Socket.h" // 110% 11/10
#    include "core.network/Name.h" // 90% 9/10
#    include "Core.Lattice/Lattice.h" // 140% 14/10
#    include "Core.Graphics/Value.h" // 340% 34/10
#    include "Core.Graphics/Graphics.h" // 950% 95/10
#    include "core.graphics/Name.h" // 360% 36/10
#    include "Core.Lattice/GenericMesh.h" // 100% 10/10
#    include "Core.Lattice/GenericMesh_fwd.h" // 100% 10/10
#    include "core.graphics/Device/Geometry/VertexDeclaration.h" // 200% 20/10
#    include "Core.Graphics/ValueBlock.h" // 260% 26/10
#    include "Core.Graphics/Device/DeviceAPIDependantEntity.h" // 530% 53/10
#    include "Core.Graphics/Device/DeviceRevision.h" // 570% 57/10
#    include "Core.Graphics/Device/DeviceResource.h" // 540% 54/10
#    include "Core.Graphics/Device/DeviceResourceType.h" // 550% 55/10
#    include "core.graphics/Device/State/SamplerState.h" // 100% 10/10
#    include "Core.Graphics/Device/Geometry/IndexElementSize.h" // 80% 8/10
#    include "Core.Pixmap/Pixmap.h" // 120% 12/10
#    include "Core.Pixmap/PixelStorage.h" // 80% 8/10
#    include "Core.Pixmap/Pixmap_fwd.h" // 90% 9/10
#    include "Core.Graphics/Device/AbstractDeviceAPIEncapsulator.h" // 250% 25/10
#    include "Core.Graphics/Device/DeviceAPI.h" // 480% 48/10
#    include "Core.Graphics/Device/DeviceAPI_fwd.h" // 490% 49/10
#    include "Core.Graphics/Device/IDeviceAPIContext.h" // 480% 48/10
#    include "Core.Graphics/Device/IDeviceAPIDiagnostics.h" // 490% 49/10
#    include "Core.Graphics/Device/DeviceDiagnostics.h" // 510% 51/10
#    include "Core.Graphics/Device/IDeviceAPIEncapsulator.h" // 490% 49/10
#    include "Core/Maths/ScalarRectangle_fwd.h" // 510% 51/10
#    include "Core.Graphics/Device/PresentationParameters.h" // 300% 30/10
#    include "Core/Maths/ScalarRectangle.h" // 300% 30/10
#    include "Core.Graphics/Device/DeviceEncapsulator.h" // 390% 39/10
#    include "Core.Graphics/Device/DeviceStatus.h" // 400% 40/10
#    include "Core/Meta/Event.h" // 410% 41/10
#    include "Core.Graphics/Device/DeviceEncapsulatorException.h" // 160% 16/10
#    include "Core.Graphics/Device/DeviceResourceBuffer.h" // 290% 29/10
#    include "Core.Graphics/Device/Pool/DeviceResourceSharable.h" // 310% 31/10
#    include "Core.Graphics/Device/Pool/DeviceSharedEntityKey.h" // 310% 31/10
#    include "Core.Graphics/Device/Geometry/PrimitiveType.h" // 80% 8/10
#    include "Core.Graphics/Device/Shader/ShaderProgram.h" // 130% 13/10
#    include "Core.Graphics/Device/Shader/ShaderProfile.h" // 140% 14/10
#    include "core.graphics/Device/State/BlendState.h" // 80% 8/10
#    include "core.graphics/Device/State/DepthStencilState.h" // 80% 8/10
#    include "core.graphics/Device/State/RasterizerState.h" // 80% 8/10
#    include "Core.Graphics/Device/Texture/Texture2D.h" // 120% 12/10
#    include "Core.Graphics/Device/Texture/Texture.h" // 150% 15/10
#    include "Core/Memory/ComPtr.h" // 200% 20/10
#    include "Core.Graphics/DirectX11/DX11DeviceAPIEncapsulator.h" // 190% 19/10
#    include "Core.Graphics/DirectX11/DX11Includes.h" // 220% 22/10
#    include "Core.Graphics/DirectX11/DX11DeviceWrapper.h" // 190% 19/10
#    include "Core.Graphics/Device/Shader/ShaderCompiled.h" // 80% 8/10
#    include "Core.Graphics/Device/Shader/ConstantBufferLayout.h" // 110% 11/10
#    include "core.graphics/Device/Texture/SurfaceFormat.h" // 160% 16/10
#    include "core.graphics/window/BasicWindow.h" // 110% 11/10
#    include "Core.Graphics/Window/WindowMessage.h" // 120% 12/10
#    include "core.graphics/window/WindowMessageHandler.h" // 110% 11/10
#    include "Core.ContentPipeline/ContentPipeline.h" // 110% 11/10
#    include "Core.RTTI/RTTI_Macros.h" // 90% 9/10
#    include "Core.RTTI/RTTI_Macros-impl.h" // 80% 8/10
#    include "Core.Application/Application.h" // 230% 23/10
#    include "Core.Application/Input/GamepadButton.h" // 80% 8/10
#    include "Core.Application/Input/KeyboardKey.h" // 80% 8/10
#    include "Core.Application/Input/MouseButton.h" // 80% 8/10
#elif defined(BUILDCONFIG_Win32_Profiling) || defined(BUILDCONFIG_Win64_Profiling)
#    include "Core/Misc/Platform_Windows.h" // 2870% 287/10
#    include "Core/Core.h" // 2880% 288/10
#    include "Core/Meta/Aliases.h" // 2880% 288/10
#    include "Core/Meta/Alignment.h" // 2880% 288/10
#    include "Core/Meta/TypeTraits.h" // 2880% 288/10
#    include "Core/Meta/Assert.h" // 2880% 288/10
#    include "Core/Diagnostic/Exception.h" // 2880% 288/10
#    include "Core/Meta/BitCount.h" // 2880% 288/10
#    include "Core/Meta/Cast.h" // 2880% 288/10
#    include "Core/Meta/TypeHash.h" // 2880% 288/10
#    include "Core/Meta/Hash_fwd.h" // 2880% 288/10
#    include "Core/Meta/Delete.h" // 2880% 288/10
#    include "Core/Meta/Enum.h" // 2880% 288/10
#    include "Core/Meta/ForRange.h" // 2880% 288/10
#    include "Core/Meta/Iterator.h" // 2880% 288/10
#    include "Core/Meta/Warnings.h" // 2880% 288/10
#    include "Core/Meta/NumericLimits.h" // 2880% 288/10
#    include "Core/Meta/OneTimeInitialize.h" // 2880% 288/10
#    include "Core/Meta/StronglyTyped.h" // 2880% 288/10
#    include "Core/Meta/ThreadResource.h" // 2880% 288/10
#    include "Core/Allocator/Alloca.h" // 2190% 219/10
#    include "Core/Memory/MemoryView.h" // 2480% 248/10
#    include "Core/Memory/UniquePtr.h" // 2200% 220/10
#    include "Core/Memory/RefPtr.h" // 2230% 223/10
#    include "Core/Memory/MemoryDomain.h" // 2390% 239/10
#    include "Core/Memory/MemoryTracking.h" // 2180% 218/10
#    include "Core/IO/FormatHelpers.h" // 2180% 218/10
#    include "Core/IO/StringView.h" // 2440% 244/10
#    include "Core/Container/Hash.h" // 2470% 247/10
#    include "Core/Memory/HashFunctions.h" // 2510% 251/10
#    include "Core/Meta/Singleton.h" // 2220% 222/10
#    include "Core/Meta/AlignedStorage.h" // 2240% 224/10
#    include "Core/Allocator/Heap.h" // 2190% 219/10
#    include "Core/Allocator/Malloc.h" // 2200% 220/10
#    include "Core/Allocator/New.h" // 2170% 217/10
#    include "Core/Allocator/PoolAllocatorTag.h" // 2360% 236/10
#    include "Core/Allocator/SingletonPoolAllocator.h" // 120% 12/10
#    include "Core/Allocator/AllocatorBase.h" // 2160% 216/10
#    include "Core/Memory/SegregatedMemoryPool.h" // 720% 72/10
#    include "Core/Allocator/ThreadLocalAllocator.h" // 2160% 216/10
#    include "Core/Allocator/HeapAllocator.h" // 2160% 216/10
#    include "Core/Memory/MemoryPool.h" // 850% 85/10
#    include "Core/Container/IntrusiveList.h" // 960% 96/10
#    include "Core/Thread/AtomicSpinLock.h" // 900% 90/10
#    include "Core/Meta/AutoSingleton.h" // 740% 74/10
#    include "Core/IO/Format.h" // 1240% 124/10
#    include "Core/IO/String.h" // 1890% 189/10
#    include "Core/Allocator/Allocation.h" // 2160% 216/10
#    include "Core/Allocator/Mallocator.h" // 2160% 216/10
#    include "Core/Allocator/PoolAllocator.h" // 2170% 217/10
#    include "Core/Allocator/TrackingAllocator.h" // 2160% 216/10
#    include "Core/IO/Stream.h" // 1890% 189/10
#    include "Core/Memory/UniqueView.h" // 1910% 191/10
#    include "Core/Allocator/PoolAllocatorTag-impl.h" // 180% 18/10
#    include "Core/Diagnostic/LastError.h" // 90% 9/10
#    include "Core/Misc/TargetPlatform.h" // 1200% 120/10
#    include "Core/Color/Color.h" // 440% 44/10
#    include "Core/Color/Color_fwd.h" // 900% 90/10
#    include "Core/Maths/ScalarVector_fwd.h" // 1390% 139/10
#    include "Core/Maths/PackingHelpers.h" // 1110% 111/10
#    include "Core/Maths/Packing_fwd.h" // 1110% 111/10
#    include "Core/Maths/MathHelpers.h" // 1160% 116/10
#    include "Core/Maths/PackedVectors.h" // 700% 70/10
#    include "Core/Maths/ScalarVector.h" // 1230% 123/10
#    include "Core/Maths/ScalarVectorHelpers.h" // 1100% 110/10
#    include "Core/Misc/Endianness.h" // 1120% 112/10
#    include "Core/Container/BitSet.h" // 140% 14/10
#    include "Core/Diagnostic/Logger.h" // 600% 60/10
#    include "Core/Thread/ReadWriteLock.h" // 390% 39/10
#    include "Core/Diagnostic/CurrentProcess.h" // 90% 9/10
#    include "Core/Time/Timepoint.h" // 130% 13/10
#    include "Core/Maths/Units.h" // 260% 26/10
#    include "Core/Container/Vector.h" // 1460% 146/10
#    include "Core/Allocator/InSituAllocator.h" // 1460% 146/10
#    include "Core/IO/FileSystem.h" // 120% 12/10
#    include "Core/IO/FS/FileSystemProperties.h" // 760% 76/10
#    include "Core/IO/FS/Basename.h" // 690% 69/10
#    include "Core/IO/FS/BasenameNoExt.h" // 700% 70/10
#    include "Core/IO/FS/FileSystemToken.h" // 740% 74/10
#    include "Core/Container/Token.h" // 1100% 110/10
#    include "Core/Container/HashSet.h" // 1100% 110/10
#    include "Core/Container/HashTable.h" // 1140% 114/10
#    include "Core/Container/Pair.h" // 1280% 128/10
#    include "Core/Container/Stack.h" // 1200% 120/10
#    include "Core/IO/FS/FileSystemToken_fwd.h" // 750% 75/10
#    include "Core/IO/FS/Extname.h" // 700% 70/10
#    include "Core/IO/FS/Dirname.h" // 700% 70/10
#    include "Core/IO/FS/Dirpath.h" // 690% 69/10
#    include "Core/IO/FS/Filename.h" // 680% 68/10
#    include "Core/IO/FS/MountingPoint.h" // 700% 70/10
#    include "Core/IO/VirtualFileSystem.h" // 180% 18/10
#    include "Core/IO/VirtualFileSystem_fwd.h" // 240% 24/10
#    include "Core/IO/FileSystem_fwd.h" // 390% 39/10
#    include "Core/IO/VFS/VirtualFileSystemPolicies.h" // 240% 24/10
#    include "Core/Meta/Function.h" // 320% 32/10
#    include "Core/IO/VFS/VirtualFileSystemTrie.h" // 190% 19/10
#    include "Core/Container/AssociativeVector.h" // 870% 87/10
#    include "Core/Memory/Compression.h" // 200% 20/10
#    include "Core/Memory/MemoryProvider.h" // 80% 8/10
#    include "Core/IO/StreamProvider.h" // 410% 41/10
#    include "Core/IO/FS/ConstNames.h" // 100% 10/10
#    include "Core/Time/Timestamp.h" // 390% 39/10
#    include "Core/Allocator/PoolAllocator-impl.h" // 670% 67/10
#    include "Core/Container/RawStorage.h" // 850% 85/10
#    include "Core/IO/VFS/VirtualFileSystemStream.h" // 110% 11/10
#    include "Core/Maths/ScalarBoundingBox.h" // 460% 46/10
#    include "Core/Maths/ScalarBoundingBox_fwd.h" // 860% 86/10
#    include "Core/Meta/Delegate.h" // 750% 75/10
#    include "Core/Meta/PointerWFlags.h" // 770% 77/10
#    include "Core/Meta/BitField.h" // 990% 99/10
#    include "Core/Maths/Collision.h" // 160% 16/10
#    include "Core/Maths/Plane.h" // 120% 12/10
#    include "Core/Maths/ScalarMatrix_fwd.h" // 820% 82/10
#    include "Core/Maths/ScalarMatrix.h" // 770% 77/10
#    include "Core/Maths/ScalarMatrixHelpers.h" // 90% 9/10
#    include "Core/Maths/Quaternion.h" // 130% 13/10
#    include "Core/Maths/QuaternionHelpers.h" // 110% 11/10
#    include "Core/Memory/WeakPtr.h" // 550% 55/10
#    include "Core/Misc/ServiceContainer.h" // 80% 8/10
#    include "Core/Container/FlatMap.h" // 90% 9/10
#    include "Core/Thread/Task/Task.h" // 110% 11/10
#    include "Core/Thread/Task/TaskManager.h" // 110% 11/10
#    include "Core/Thread/ThreadContext.h" // 140% 14/10
#    include "Core/Thread/ThreadPool.h" // 80% 8/10
#    include "Core/Time/DateTime.h" // 360% 36/10
#    include "Core.RTTI/RTTI.h" // 750% 75/10
#    include "Core.RTTI/MetaClass.h" // 310% 31/10
#    include "Core.RTTI/Typedefs.h" // 380% 38/10
#    include "Core.RTTI/MetaNamespace.h" // 320% 32/10
#    include "Core/Container/HashMap.h" // 510% 51/10
#    include "Core.RTTI/MetaObject.h" // 290% 29/10
#    include "Core.RTTI/MetaType.h" // 360% 36/10
#    include "Core.RTTI/MetaTypeVirtualTraits.h" // 360% 36/10
#    include "Core.RTTI/MetaProperty.h" // 230% 23/10
#    include "Core.RTTI/MetaPropertyAccessor.h" // 230% 23/10
#    include "Core.RTTI/Exceptions.h" // 230% 23/10
#    include "Core.RTTI/MetaAtom.h" // 340% 34/10
#    include "Core.RTTI/RTTI_fwd.h" // 730% 73/10
#    include "Core.RTTI/MetaObjectHelpers.h" // 730% 73/10
#    include "Core.RTTI/MetaAtomVisitor.h" // 340% 34/10
#    include "Core.RTTI/MetaTypeTraits.h" // 340% 34/10
#    include "Core/Container/Token_fwd.h" // 340% 34/10
#    include "Core.RTTI/MetaTypePromote.h" // 340% 34/10
#    include "Core.RTTI/MetaDatabase.h" // 80% 8/10
#    include "Core.RTTI/MetaFunction.h" // 100% 10/10
#    include "Core/Container/Tuple.h" // 160% 16/10
#    include "Core.RTTI/RTTI_Namespace.h" // 150% 15/10
#    include "Core.RTTI/MetaTransaction.h" // 80% 8/10
#    include "Core.RTTI/RTTI_extern.h" // 90% 9/10
#    include "Core.Serialize/Serialize.h" // 310% 31/10
#    include "Core.Serialize/Exceptions.h" // 230% 23/10
#    include "Core/Memory/MemoryStream.h" // 220% 22/10
#    include "Core.Serialize/Lexer/Location.h" // 240% 24/10
#    include "Core/Container/StringHashMap.h" // 100% 10/10
#    include "Core.Serialize/Lexer/LookAheadReader.h" // 90% 9/10
#    include "Core.Serialize/Lexer/Match.h" // 120% 12/10
#    include "Core.Serialize/Lexer/Symbol.h" // 140% 14/10
#    include "Core.Serialize/Parser/ParseContext.h" // 80% 8/10
#    include "Core.Serialize/Parser/ParseExpression.h" // 80% 8/10
#    include "Core.Serialize/Parser/ParseItem.h" // 90% 9/10
#    include "Core.Serialize/Parser/ParseList.h" // 90% 9/10
#    include "core.serialize/XML/XML.h" // 100% 10/10
#    include "Core.Network/Network.h" // 200% 20/10
#    include "Core.Network/Socket/Address.h" // 120% 12/10
#    include "core.network/socket/SocketBuffered.h" // 90% 9/10
#    include "core.network/Socket/Socket.h" // 110% 11/10
#    include "core.network/Name.h" // 90% 9/10
#    include "Core.Lattice/Lattice.h" // 140% 14/10
#    include "Core.Graphics/Value.h" // 340% 34/10
#    include "Core.Graphics/Graphics.h" // 950% 95/10
#    include "core.graphics/Name.h" // 360% 36/10
#    include "Core.Lattice/GenericMesh.h" // 100% 10/10
#    include "Core.Lattice/GenericMesh_fwd.h" // 100% 10/10
#    include "core.graphics/Device/Geometry/VertexDeclaration.h" // 200% 20/10
#    include "Core.Graphics/ValueBlock.h" // 260% 26/10
#    include "Core.Graphics/Device/DeviceAPIDependantEntity.h" // 530% 53/10
#    include "Core.Graphics/Device/DeviceRevision.h" // 570% 57/10
#    include "Core.Graphics/Device/DeviceResource.h" // 540% 54/10
#    include "Core.Graphics/Device/DeviceResourceType.h" // 550% 55/10
#    include "core.graphics/Device/State/SamplerState.h" // 100% 10/10
#    include "Core.Graphics/Device/Geometry/IndexElementSize.h" // 80% 8/10
#    include "Core.Pixmap/Pixmap.h" // 120% 12/10
#    include "Core.Pixmap/PixelStorage.h" // 80% 8/10
#    include "Core.Pixmap/Pixmap_fwd.h" // 90% 9/10
#    include "Core.Graphics/Device/AbstractDeviceAPIEncapsulator.h" // 250% 25/10
#    include "Core.Graphics/Device/DeviceAPI.h" // 480% 48/10
#    include "Core.Graphics/Device/DeviceAPI_fwd.h" // 490% 49/10
#    include "Core.Graphics/Device/IDeviceAPIContext.h" // 480% 48/10
#    include "Core.Graphics/Device/IDeviceAPIDiagnostics.h" // 490% 49/10
#    include "Core.Graphics/Device/DeviceDiagnostics.h" // 510% 51/10
#    include "Core.Graphics/Device/IDeviceAPIEncapsulator.h" // 490% 49/10
#    include "Core/Maths/ScalarRectangle_fwd.h" // 510% 51/10
#    include "Core.Graphics/Device/PresentationParameters.h" // 300% 30/10
#    include "Core/Maths/ScalarRectangle.h" // 300% 30/10
#    include "Core.Graphics/Device/DeviceEncapsulator.h" // 390% 39/10
#    include "Core.Graphics/Device/DeviceStatus.h" // 400% 40/10
#    include "Core/Meta/Event.h" // 410% 41/10
#    include "Core.Graphics/Device/DeviceEncapsulatorException.h" // 160% 16/10
#    include "Core.Graphics/Device/DeviceResourceBuffer.h" // 290% 29/10
#    include "Core.Graphics/Device/Pool/DeviceResourceSharable.h" // 310% 31/10
#    include "Core.Graphics/Device/Pool/DeviceSharedEntityKey.h" // 310% 31/10
#    include "Core.Graphics/Device/Geometry/PrimitiveType.h" // 80% 8/10
#    include "Core.Graphics/Device/Shader/ShaderProgram.h" // 130% 13/10
#    include "Core.Graphics/Device/Shader/ShaderProfile.h" // 140% 14/10
#    include "core.graphics/Device/State/BlendState.h" // 80% 8/10
#    include "core.graphics/Device/State/DepthStencilState.h" // 80% 8/10
#    include "core.graphics/Device/State/RasterizerState.h" // 80% 8/10
#    include "Core.Graphics/Device/Texture/Texture2D.h" // 120% 12/10
#    include "Core.Graphics/Device/Texture/Texture.h" // 150% 15/10
#    include "Core/Memory/ComPtr.h" // 200% 20/10
#    include "Core.Graphics/DirectX11/DX11DeviceAPIEncapsulator.h" // 190% 19/10
#    include "Core.Graphics/DirectX11/DX11Includes.h" // 220% 22/10
#    include "Core.Graphics/DirectX11/DX11DeviceWrapper.h" // 190% 19/10
#    include "Core.Graphics/Device/Shader/ShaderCompiled.h" // 80% 8/10
#    include "Core.Graphics/Device/Shader/ConstantBufferLayout.h" // 110% 11/10
#    include "core.graphics/Device/Texture/SurfaceFormat.h" // 160% 16/10
#    include "core.graphics/window/BasicWindow.h" // 110% 11/10
#    include "Core.Graphics/Window/WindowMessage.h" // 120% 12/10
#    include "core.graphics/window/WindowMessageHandler.h" // 110% 11/10
#    include "Core.ContentPipeline/ContentPipeline.h" // 110% 11/10
#    include "Core.RTTI/RTTI_Macros.h" // 90% 9/10
#    include "Core.RTTI/RTTI_Macros-impl.h" // 80% 8/10
#    include "Core.Application/Application.h" // 230% 23/10
#    include "Core.Application/Input/GamepadButton.h" // 80% 8/10
#    include "Core.Application/Input/KeyboardKey.h" // 80% 8/10
#    include "Core.Application/Input/MouseButton.h" // 80% 8/10
#elif defined(BUILDCONFIG_Win32_Final) || defined(BUILDCONFIG_Win64_Final)
#    include "Core/Misc/Platform_Windows.h" // 2870% 287/10
#    include "Core/Core.h" // 2880% 288/10
#    include "Core/Meta/Aliases.h" // 2880% 288/10
#    include "Core/Meta/Alignment.h" // 2880% 288/10
#    include "Core/Meta/TypeTraits.h" // 2880% 288/10
#    include "Core/Meta/Assert.h" // 2880% 288/10
#    include "Core/Diagnostic/Exception.h" // 2880% 288/10
#    include "Core/Meta/BitCount.h" // 2880% 288/10
#    include "Core/Meta/Cast.h" // 2880% 288/10
#    include "Core/Meta/TypeHash.h" // 2880% 288/10
#    include "Core/Meta/Hash_fwd.h" // 2880% 288/10
#    include "Core/Meta/Delete.h" // 2880% 288/10
#    include "Core/Meta/Enum.h" // 2880% 288/10
#    include "Core/Meta/ForRange.h" // 2880% 288/10
#    include "Core/Meta/Iterator.h" // 2880% 288/10
#    include "Core/Meta/Warnings.h" // 2880% 288/10
#    include "Core/Meta/NumericLimits.h" // 2880% 288/10
#    include "Core/Meta/OneTimeInitialize.h" // 2880% 288/10
#    include "Core/Meta/StronglyTyped.h" // 2880% 288/10
#    include "Core/Meta/ThreadResource.h" // 2880% 288/10
#    include "Core/Allocator/Alloca.h" // 2150% 215/10
#    include "Core/Memory/MemoryView.h" // 2460% 246/10
#    include "Core/Memory/UniquePtr.h" // 2170% 217/10
#    include "Core/Memory/RefPtr.h" // 2200% 220/10
#    include "Core/Memory/MemoryDomain.h" // 2380% 238/10
#    include "Core/Memory/MemoryTracking.h" // 2150% 215/10
#    include "Core/IO/FormatHelpers.h" // 2150% 215/10
#    include "Core/IO/StringView.h" // 2420% 242/10
#    include "Core/Container/Hash.h" // 2450% 245/10
#    include "Core/Memory/HashFunctions.h" // 2490% 249/10
#    include "Core/Meta/Singleton.h" // 2190% 219/10
#    include "Core/Memory//" // 2210% 221/10
#    include "Core/Allocator/Heap.h" // 2160% 216/10
#    include "Core/Allocator/Malloc.h" // 2160% 216/10
#    include "Core/Allocator/New.h" // 2130% 213/10
#    include "Core/Allocator/PoolAllocatorTag.h" // 2350% 235/10
#    include "Core/Allocator/SingletonPoolAllocator.h" // 120% 12/10
#    include "Core/Allocator/AllocatorBase.h" // 2130% 213/10
#    include "Core/Memory/SegregatedMemoryPool.h" // 720% 72/10
#    include "Core/Allocator/ThreadLocalAllocator.h" // 2130% 213/10
#    include "Core/Allocator/HeapAllocator.h" // 2130% 213/10
#    include "Core/Memory/MemoryPool.h" // 850% 85/10
#    include "Core/Container/IntrusiveList.h" // 960% 96/10
#    include "Core/Thread/AtomicSpinLock.h" // 900% 90/10
#    include "Core/Meta/AutoSingleton.h" // 740% 74/10
#    include "Core/Allocator/PoolAllocatorTag-impl.h" // 180% 18/10
#    include "Core/Allocator/PoolAllocator.h" // 2140% 214/10
#    include "Core/Diagnostic/LastError.h" // 90% 9/10
#    include "Core/IO/String.h" // 1810% 181/10
#    include "Core/Allocator/Allocation.h" // 2120% 212/10
#    include "Core/Allocator/Mallocator.h" // 2120% 212/10
#    include "Core/Allocator/TrackingAllocator.h" // 2120% 212/10
#    include "Core/IO/Stream.h" // 1810% 181/10
#    include "Core/Memory/UniqueView.h" // 1830% 183/10
#    include "Core/Misc/TargetPlatform.h" // 1190% 119/10
#    include "Core/Color/Color.h" // 440% 44/10
#    include "Core/Color/Color_fwd.h" // 890% 89/10
#    include "Core/Maths/ScalarVector_fwd.h" // 1380% 138/10
#    include "Core/Maths/PackingHelpers.h" // 1100% 110/10
#    include "Core/Maths/Packing_fwd.h" // 1100% 110/10
#    include "Core/Maths/MathHelpers.h" // 1150% 115/10
#    include "Core/Maths/PackedVectors.h" // 700% 70/10
#    include "Core/Maths/ScalarVector.h" // 1220% 122/10
#    include "Core/Maths/ScalarVectorHelpers.h" // 1090% 109/10
#    include "Core/Misc/Endianness.h" // 1110% 111/10
#    include "Core/Container/BitSet.h" // 140% 14/10
#    include "Core/Diagnostic/Logger.h" // 590% 59/10
#    include "Core/IO/Format.h" // 950% 95/10
#    include "Core/Thread/ReadWriteLock.h" // 390% 39/10
#    include "Core/Diagnostic/CurrentProcess.h" // 90% 9/10
#    include "Core/Time/Timepoint.h" // 130% 13/10
#    include "Core/Maths/Units.h" // 260% 26/10
#    include "Core/Container/Vector.h" // 1450% 145/10
#    include "Core/Allocator/InSituAllocator.h" // 1450% 145/10
#    include "Core/IO/FileSystem.h" // 120% 12/10
#    include "Core/IO/FS/FileSystemProperties.h" // 760% 76/10
#    include "Core/IO/FS/Basename.h" // 690% 69/10
#    include "Core/IO/FS/BasenameNoExt.h" // 700% 70/10
#    include "Core/IO/FS/FileSystemToken.h" // 740% 74/10
#    include "Core/Container/Token.h" // 1100% 110/10
#    include "Core/Container/HashSet.h" // 1100% 110/10
#    include "Core/Container/HashTable.h" // 1140% 114/10
#    include "Core/Container/Pair.h" // 1280% 128/10
#    include "Core/Container/Stack.h" // 1200% 120/10
#    include "Core/IO/FS/FileSystemToken_fwd.h" // 750% 75/10
#    include "Core/IO/FS/Extname.h" // 700% 70/10
#    include "Core/IO/FS/Dirname.h" // 700% 70/10
#    include "Core/IO/FS/Dirpath.h" // 690% 69/10
#    include "Core/IO/FS/Filename.h" // 680% 68/10
#    include "Core/IO/FS/MountingPoint.h" // 700% 70/10
#    include "Core/IO/VirtualFileSystem.h" // 180% 18/10
#    include "Core/IO/VirtualFileSystem_fwd.h" // 240% 24/10
#    include "Core/IO/FileSystem_fwd.h" // 390% 39/10
#    include "Core/IO/VFS/VirtualFileSystemPolicies.h" // 240% 24/10
#    include "Core/Meta/Function.h" // 320% 32/10
#    include "Core/IO/VFS/VirtualFileSystemTrie.h" // 190% 19/10
#    include "Core/Container/AssociativeVector.h" // 870% 87/10
#    include "Core/Memory/Compression.h" // 200% 20/10
#    include "Core/Memory/MemoryProvider.h" // 80% 8/10
#    include "Core/IO/StreamProvider.h" // 410% 41/10
#    include "Core/IO/FS/ConstNames.h" // 100% 10/10
#    include "Core/Time/Timestamp.h" // 390% 39/10
#    include "Core/Allocator/PoolAllocator-impl.h" // 670% 67/10
#    include "Core/Container/RawStorage.h" // 850% 85/10
#    include "Core/IO/VFS/VirtualFileSystemStream.h" // 110% 11/10
#    include "Core/Maths/ScalarBoundingBox.h" // 450% 45/10
#    include "Core/Maths/ScalarBoundingBox_fwd.h" // 850% 85/10
#    include "Core/Meta/Delegate.h" // 750% 75/10
#    include "Core/Meta/PointerWFlags.h" // 770% 77/10
#    include "Core/Meta/BitField.h" // 990% 99/10
#    include "Core/Maths/Collision.h" // 160% 16/10
#    include "Core/Maths/Plane.h" // 120% 12/10
#    include "Core/Maths/ScalarMatrix_fwd.h" // 820% 82/10
#    include "Core/Maths/ScalarMatrix.h" // 770% 77/10
#    include "Core/Maths/ScalarMatrixHelpers.h" // 90% 9/10
#    include "Core/Maths/Quaternion.h" // 130% 13/10
#    include "Core/Maths/QuaternionHelpers.h" // 110% 11/10
#    include "Core/Memory/WeakPtr.h" // 550% 55/10
#    include "Core/Misc/ServiceContainer.h" // 80% 8/10
#    include "Core/Container/FlatMap.h" // 90% 9/10
#    include "Core/Thread/Task/Task.h" // 110% 11/10
#    include "Core/Thread/Task/TaskManager.h" // 110% 11/10
#    include "Core/Thread/ThreadContext.h" // 140% 14/10
#    include "Core/Thread/ThreadPool.h" // 80% 8/10
#    include "Core/Time/DateTime.h" // 360% 36/10
#    include "Core.RTTI/RTTI.h" // 750% 75/10
#    include "Core.RTTI/MetaClass.h" // 310% 31/10
#    include "Core.RTTI/Typedefs.h" // 380% 38/10
#    include "Core.RTTI/MetaNamespace.h" // 320% 32/10
#    include "Core/Container/HashMap.h" // 510% 51/10
#    include "Core.RTTI/MetaObject.h" // 290% 29/10
#    include "Core.RTTI/MetaType.h" // 360% 36/10
#    include "Core.RTTI/MetaTypeVirtualTraits.h" // 360% 36/10
#    include "Core.RTTI/MetaProperty.h" // 230% 23/10
#    include "Core.RTTI/MetaPropertyAccessor.h" // 230% 23/10
#    include "Core.RTTI/Exceptions.h" // 230% 23/10
#    include "Core.RTTI/MetaAtom.h" // 340% 34/10
#    include "Core.RTTI/RTTI_fwd.h" // 730% 73/10
#    include "Core.RTTI/MetaObjectHelpers.h" // 730% 73/10
#    include "Core.RTTI/MetaAtomVisitor.h" // 340% 34/10
#    include "Core.RTTI/MetaTypeTraits.h" // 340% 34/10
#    include "Core/Container/Token_fwd.h" // 340% 34/10
#    include "Core.RTTI/MetaTypePromote.h" // 340% 34/10
#    include "Core.RTTI/MetaDatabase.h" // 80% 8/10
#    include "Core.RTTI/MetaFunction.h" // 100% 10/10
#    include "Core/Container/Tuple.h" // 160% 16/10
#    include "Core.RTTI/RTTI_Namespace.h" // 150% 15/10
#    include "Core.RTTI/MetaTransaction.h" // 80% 8/10
#    include "Core.RTTI/RTTI_extern.h" // 90% 9/10
#    include "Core.Serialize/Serialize.h" // 310% 31/10
#    include "Core.Serialize/Exceptions.h" // 230% 23/10
#    include "Core/Memory/MemoryStream.h" // 220% 22/10
#    include "Core.Serialize/Lexer/Location.h" // 240% 24/10
#    include "Core/Container/StringHashMap.h" // 100% 10/10
#    include "Core.Serialize/Lexer/LookAheadReader.h" // 90% 9/10
#    include "Core.Serialize/Lexer/Match.h" // 120% 12/10
#    include "Core.Serialize/Lexer/Symbol.h" // 140% 14/10
#    include "Core.Serialize/Parser/ParseContext.h" // 80% 8/10
#    include "Core.Serialize/Parser/ParseExpression.h" // 80% 8/10
#    include "Core.Serialize/Parser/ParseItem.h" // 90% 9/10
#    include "Core.Serialize/Parser/ParseList.h" // 90% 9/10
#    include "core.serialize/XML/XML.h" // 100% 10/10
#    include "Core.Network/Network.h" // 200% 20/10
#    include "Core.Network/Socket/Address.h" // 120% 12/10
#    include "core.network/socket/SocketBuffered.h" // 90% 9/10
#    include "core.network/Socket/Socket.h" // 110% 11/10
#    include "core.network/Name.h" // 90% 9/10
#    include "Core.Lattice/Lattice.h" // 140% 14/10
#    include "Core.Graphics/Value.h" // 340% 34/10
#    include "Core.Graphics/Graphics.h" // 950% 95/10
#    include "core.graphics/Name.h" // 360% 36/10
#    include "Core.Lattice/GenericMesh.h" // 100% 10/10
#    include "Core.Lattice/GenericMesh_fwd.h" // 100% 10/10
#    include "core.graphics/Device/Geometry/VertexDeclaration.h" // 200% 20/10
#    include "Core.Graphics/ValueBlock.h" // 260% 26/10
#    include "Core.Graphics/Device/DeviceAPIDependantEntity.h" // 530% 53/10
#    include "Core.Graphics/Device/DeviceRevision.h" // 570% 57/10
#    include "Core.Graphics/Device/DeviceResource.h" // 540% 54/10
#    include "Core.Graphics/Device/DeviceResourceType.h" // 550% 55/10
#    include "core.graphics/Device/State/SamplerState.h" // 100% 10/10
#    include "Core.Graphics/Device/Geometry/IndexElementSize.h" // 80% 8/10
#    include "Core.Pixmap/Pixmap.h" // 120% 12/10
#    include "Core.Pixmap/PixelStorage.h" // 80% 8/10
#    include "Core.Pixmap/Pixmap_fwd.h" // 90% 9/10
#    include "Core.Graphics/Device/AbstractDeviceAPIEncapsulator.h" // 240% 24/10
#    include "Core.Graphics/Device/DeviceAPI.h" // 470% 47/10
#    include "Core.Graphics/Device/DeviceAPI_fwd.h" // 480% 48/10
#    include "Core.Graphics/Device/IDeviceAPIContext.h" // 470% 47/10
#    include "Core.Graphics/Device/IDeviceAPIDiagnostics.h" // 480% 48/10
#    include "Core.Graphics/Device/DeviceDiagnostics.h" // 510% 51/10
#    include "Core.Graphics/Device/IDeviceAPIEncapsulator.h" // 480% 48/10
#    include "Core/Maths/ScalarRectangle_fwd.h" // 500% 50/10
#    include "Core.Graphics/Device/PresentationParameters.h" // 290% 29/10
#    include "Core/Maths/ScalarRectangle.h" // 290% 29/10
#    include "Core.Graphics/Device/DeviceEncapsulator.h" // 390% 39/10
#    include "Core.Graphics/Device/DeviceStatus.h" // 400% 40/10
#    include "Core/Meta/Event.h" // 410% 41/10
#    include "Core.Graphics/Device/DeviceEncapsulatorException.h" // 160% 16/10
#    include "Core.Graphics/Device/DeviceResourceBuffer.h" // 290% 29/10
#    include "Core.Graphics/Device/Pool/DeviceResourceSharable.h" // 310% 31/10
#    include "Core.Graphics/Device/Pool/DeviceSharedEntityKey.h" // 310% 31/10
#    include "Core.Graphics/Device/Geometry/PrimitiveType.h" // 80% 8/10
#    include "Core.Graphics/Device/Shader/ShaderProgram.h" // 130% 13/10
#    include "Core.Graphics/Device/Shader/ShaderProfile.h" // 140% 14/10
#    include "core.graphics/Device/State/BlendState.h" // 80% 8/10
#    include "core.graphics/Device/State/DepthStencilState.h" // 80% 8/10
#    include "core.graphics/Device/State/RasterizerState.h" // 80% 8/10
#    include "Core.Graphics/Device/Texture/Texture2D.h" // 120% 12/10
#    include "Core.Graphics/Device/Texture/Texture.h" // 150% 15/10
#    include "Core/Memory/ComPtr.h" // 200% 20/10
#    include "Core.Graphics/DirectX11/DX11DeviceAPIEncapsulator.h" // 190% 19/10
#    include "Core.Graphics/DirectX11/DX11Includes.h" // 220% 22/10
#    include "Core.Graphics/DirectX11/DX11DeviceWrapper.h" // 190% 19/10
#    include "Core.Graphics/Device/Shader/ShaderCompiled.h" // 80% 8/10
#    include "Core.Graphics/Device/Shader/ConstantBufferLayout.h" // 110% 11/10
#    include "core.graphics/Device/Texture/SurfaceFormat.h" // 160% 16/10
#    include "core.graphics/window/BasicWindow.h" // 110% 11/10
#    include "Core.Graphics/Window/WindowMessage.h" // 120% 12/10
#    include "core.graphics/window/WindowMessageHandler.h" // 110% 11/10
#    include "Core.ContentPipeline/ContentPipeline.h" // 110% 11/10
#    include "Core.RTTI/RTTI_Macros.h" // 90% 9/10
#    include "Core.RTTI/RTTI_Macros-impl.h" // 80% 8/10
#    include "Core.Application/Application.h" // 230% 23/10
#    include "Core.Application/Input/GamepadButton.h" // 80% 8/10
#    include "Core.Application/Input/KeyboardKey.h" // 80% 8/10
#    include "Core.Application/Input/MouseButton.h" // 80% 8/10
#else
#     error "unknown build config"
#endif
