/*
// Generated by PCHRefactor.rb v1.0 for target <Core.ContentGenerator>
//------------------------------------------------------------------------------
// Date : 2017-09-20 01:25:42 UTC
*/

// Processed dependencies for Core.ContentGenerator-Win32-Debug : 54 std, 44 sdk, 228 prj, 11 src
// Processed dependencies for Core.ContentGenerator-Win32-FastDebug : 54 std, 44 sdk, 228 prj, 11 src
// Processed dependencies for Core.ContentGenerator-Win32-Release : 54 std, 44 sdk, 227 prj, 11 src
// Processed dependencies for Core.ContentGenerator-Win32-Profiling : 54 std, 44 sdk, 227 prj, 11 src
// Processed dependencies for Core.ContentGenerator-Win32-Final : 54 std, 44 sdk, 227 prj, 11 src
// Processed dependencies for Core.ContentGenerator-Win64-Debug : 54 std, 43 sdk, 228 prj, 11 src
// Processed dependencies for Core.ContentGenerator-Win64-FastDebug : 54 std, 43 sdk, 228 prj, 11 src
// Processed dependencies for Core.ContentGenerator-Win64-Release : 54 std, 43 sdk, 227 prj, 11 src
// Processed dependencies for Core.ContentGenerator-Win64-Profiling : 54 std, 43 sdk, 227 prj, 11 src
// Processed dependencies for Core.ContentGenerator-Win64-Final : 54 std, 43 sdk, 227 prj, 11 src

/*
// Standard headers
//------------------------------------------------------------------------------
*/
#include <algorithm>
#include <cstdint>
#include <cstdlib>
#include <limits>
#include <cfloat>
#include <climits>
#include <cmath>
#include <cwchar>
#include <cstddef>
#include <initializer_list>
#include <new>
#include <exception>
#include <type_traits>
#include <utility>
#include <iosfwd>
#include <cstdio>
#include <cstring>
#include <atomic>
#include <memory>
#include <typeinfo>
#include <functional>
#include <tuple>
#include <stdexcept>
#include <iomanip>
#include <istream>
#include <ostream>
#include <ios>
#include <streambuf>
#include <system_error>
#include <cerrno>
#include <ctime>
#include <iterator>
#include <mutex>
#include <chrono>
#include <ratio>
#include <thread>
#include <cctype>
#include <cwctype>
#include <locale>
#include <string>
#include <iostream>
#include <sstream>
#include <shared_mutex>
#include <condition_variable>
#include <unordered_map>
#include <list>
#include <vector>
#include <regex>
#include <queue>
#include <deque>
#include <fstream>
#include <allocators>
#include <bitset>
#include <unordered_set>

/*
// SDK headers
//------------------------------------------------------------------------------
*/
#if 0 // dummy
#elif defined(BUILDCONFIG_Win32_Debug) || defined(BUILDCONFIG_Win32_FastDebug) || defined(BUILDCONFIG_Win32_Release) || defined(BUILDCONFIG_Win32_Profiling) || defined(BUILDCONFIG_Win32_Final)
#    include "excpt.h"
#    include "vcruntime.h"
#    include "sal.h"
#    include "concurrencysal.h"
#    include "vadefs.h"
#    include "stdarg.h"
#    include "vcruntime_string.h"
#    include "yvals.h"
#    include "xkeycheck.h"
#    include "crtdefs.h"
#    include "use_ansi.h"
#    include "stdint.h"
#    include "limits.h"
#    include "ymath.h"
#    include "xtgmath.h"
#    include "vcruntime_new.h"
#    include "vcruntime_new_debug.h"
#    include "xatomic0.h"
#    include "intrin0.h"
#    include "xatomic.h"
#    include "vcruntime_typeinfo.h"
#    include "vcruntime_exception.h"
#    include "eh.h"
#    include "intrin.h"
#    include "setjmp.h"
#    include "immintrin.h"
#    include "wmmintrin.h"
#    include "nmmintrin.h"
#    include "smmintrin.h"
#    include "tmmintrin.h"
#    include "pmmintrin.h"
#    include "emmintrin.h"
#    include "xmmintrin.h"
#    include "mmintrin.h"
#    include "zmmintrin.h"
#    include "ammintrin.h"
#    include "mm3dnow.h"
#    include "xlocinfo.h"
#    include "xcall_once.h"
#    include "xstring_insert.h"
#    include "comdef.h"
#    include "comutil.h"
#    include "comip.h"
#    include "comdefsp.h"
#elif defined(BUILDCONFIG_Win64_Debug) || defined(BUILDCONFIG_Win64_FastDebug) || defined(BUILDCONFIG_Win64_Release) || defined(BUILDCONFIG_Win64_Profiling) || defined(BUILDCONFIG_Win64_Final)
#    include "excpt.h"
#    include "vcruntime.h"
#    include "sal.h"
#    include "concurrencysal.h"
#    include "vadefs.h"
#    include "stdarg.h"
#    include "vcruntime_string.h"
#    include "yvals.h"
#    include "xkeycheck.h"
#    include "crtdefs.h"
#    include "use_ansi.h"
#    include "stdint.h"
#    include "limits.h"
#    include "ymath.h"
#    include "xtgmath.h"
#    include "vcruntime_new.h"
#    include "vcruntime_new_debug.h"
#    include "xatomic0.h"
#    include "intrin0.h"
#    include "xatomic.h"
#    include "vcruntime_typeinfo.h"
#    include "vcruntime_exception.h"
#    include "eh.h"
#    include "intrin.h"
#    include "setjmp.h"
#    include "immintrin.h"
#    include "wmmintrin.h"
#    include "nmmintrin.h"
#    include "smmintrin.h"
#    include "tmmintrin.h"
#    include "pmmintrin.h"
#    include "emmintrin.h"
#    include "xmmintrin.h"
#    include "mmintrin.h"
#    include "zmmintrin.h"
#    include "ammintrin.h"
#    include "xlocinfo.h"
#    include "xcall_once.h"
#    include "xstring_insert.h"
#    include "comdef.h"
#    include "comutil.h"
#    include "comip.h"
#    include "comdefsp.h"
#else
#     error "unknown build config"
#endif

/*
// Project headers
//------------------------------------------------------------------------------
*/
#if 0 // dummy
#elif defined(BUILDCONFIG_Win32_Debug) || defined(BUILDCONFIG_Win32_FastDebug) || defined(BUILDCONFIG_Win64_Debug) || defined(BUILDCONFIG_Win64_FastDebug)
#    include "Core/Misc/Platform_Windows.h" // 2654% 292/11
#    include "Core/Core.h" // 2663% 293/11
#    include "Core/Meta/Aliases.h" // 2663% 293/11
#    include "Core/Meta/Alignment.h" // 2663% 293/11
#    include "Core/Meta/TypeTraits.h" // 2663% 293/11
#    include "Core/Meta/Assert.h" // 2663% 293/11
#    include "Core/Diagnostic/Exception.h" // 2663% 293/11
#    include "Core/Meta/BitCount.h" // 2663% 293/11
#    include "Core/Meta/Cast.h" // 2663% 293/11
#    include "Core/Meta/TypeHash.h" // 2663% 293/11
#    include "Core/Meta/Hash_fwd.h" // 2663% 293/11
#    include "Core/Meta/Delete.h" // 2663% 293/11
#    include "Core/Meta/Enum.h" // 2663% 293/11
#    include "Core/Meta/ForRange.h" // 2663% 293/11
#    include "Core/Meta/Iterator.h" // 2663% 293/11
#    include "Core/Meta/Warnings.h" // 2663% 293/11
#    include "Core/Meta/NumericLimits.h" // 2663% 293/11
#    include "Core/Meta/OneTimeInitialize.h" // 2663% 293/11
#    include "Core/Meta/StronglyTyped.h" // 2663% 293/11
#    include "Core/Meta/ThreadResource.h" // 2663% 293/11
#    include "Core/Allocator/Alloca.h" // 1990% 219/11
#    include "Core/Memory/MemoryView.h" // 2309% 254/11
#    include "Core/Memory/UniquePtr.h" // 2090% 230/11
#    include "Core/Memory/RefPtr.h" // 2118% 233/11
#    include "Core/Memory/MemoryDomain.h" // 2218% 244/11
#    include "Core/Memory/MemoryTracking.h" // 1990% 219/11
#    include "Core/Meta/Singleton.h" // 2072% 228/11
#    include "Core/Meta/AlignedStorage.h" // 2090% 230/11
#    include "Core/Misc/TargetPlatform.h" // 1145% 126/11
#    include "Core/IO/FS/Policies.h" // 1381% 152/11
#    include "Core/IO/StringView.h" // 2218% 244/11
#    include "Core/Container/Hash.h" // 2290% 252/11
#    include "Core/Memory/HashFunctions.h" // 2327% 256/11
#    include "Core/Allocator/Heap.h" // 1990% 219/11
#    include "Core/Allocator/Malloc.h" // 2000% 220/11
#    include "Core/Diagnostic/Callstack.h" // 72% 8/11
#    include "Core/Allocator/PoolAllocatorTag.h" // 1645% 181/11
#    include "Core/Allocator/SingletonPoolAllocator.h" // 109% 12/11
#    include "Core/Allocator/AllocatorBase.h" // 1963% 216/11
#    include "Core/Memory/SegregatedMemoryPool.h" // 609% 67/11
#    include "Core/Allocator/ThreadLocalAllocator.h" // 1963% 216/11
#    include "Core/Allocator/HeapAllocator.h" // 1963% 216/11
#    include "Core/Memory/MemoryPool.h" // 727% 80/11
#    include "Core/Container/IntrusiveList.h" // 881% 97/11
#    include "Core/Thread/AtomicSpinLock.h" // 790% 87/11
#    include "Core/Meta/AutoSingleton.h" // 627% 69/11
#    include "Core/IO/Format.h" // 1145% 126/11
#    include "Core/IO/String.h" // 1736% 191/11
#    include "Core/IO/String_fwd.h" // 1736% 191/11
#    include "Core/Allocator/Allocation.h" // 1963% 216/11
#    include "Core/Allocator/Mallocator.h" // 1963% 216/11
#    include "Core/Allocator/TrackingAllocator.h" // 1963% 216/11
#    include "Core/IO/Stream.h" // 1745% 192/11
#    include "Core/Memory/UniqueView.h" // 1763% 194/11
#    include "Core/Diagnostic/Logger.h" // 1054% 116/11
#    include "Core/Allocator/PoolAllocatorTag-impl.h" // 163% 18/11
#    include "Core/Allocator/PoolAllocator.h" // 981% 108/11
#    include "Core/Color/Color.h" // 400% 44/11
#    include "Core/Color/Color_fwd.h" // 818% 90/11
#    include "Core/Maths/ScalarVector_fwd.h" // 1272% 140/11
#    include "Core/Maths/PackingHelpers.h" // 1009% 111/11
#    include "Core/Maths/Packing_fwd.h" // 1009% 111/11
#    include "Core/Maths/MathHelpers.h" // 1063% 117/11
#    include "Core/Maths/PackedVectors.h" // 636% 70/11
#    include "Core/Maths/ScalarVector.h" // 1118% 123/11
#    include "Core/Maths/ScalarVectorHelpers.h" // 1000% 110/11
#    include "Core/Misc/Endianness.h" // 1018% 112/11
#    include "Core/Container/BitSet.h" // 127% 14/11
#    include "Core/Container/Token.h" // 1009% 111/11
#    include "Core/Diagnostic/LastError.h" // 81% 9/11
#    include "core/misc/DLLWrapper.h" // 72% 8/11
#    include "Core/Meta/PointerWFlags.h" // 772% 85/11
#    include "Core/Meta/BitField.h" // 972% 107/11
#    include "Core/IO/FormatHelpers.h" // 172% 19/11
#    include "Core/ThreaD/ReadWriteLock.h" // 354% 39/11
#    include "Core/Diagnostic/CurrentProcess.h" // 90% 10/11
#    include "Core/Time/Timepoint.h" // 154% 17/11
#    include "Core/Maths/Units.h" // 272% 30/11
#    include "Core/Container/Vector.h" // 1336% 147/11
#    include "Core/Allocator/InSituAllocator.h" // 1336% 147/11
#    include "Core/IO/FileSystem.h" // 109% 12/11
#    include "Core/IO/FS/FileSystemProperties.h" // 690% 76/11
#    include "Core/IO/FS/Basename.h" // 627% 69/11
#    include "Core/IO/FS/BasenameNoExt.h" // 636% 70/11
#    include "Core/IO/FS/FileSystemToken.h" // 672% 74/11
#    include "Core/IO/FS/FileSystemToken_fwd.h" // 681% 75/11
#    include "Core/Container/Token_fwd.h" // 681% 75/11
#    include "Core/IO/FS/Extname.h" // 636% 70/11
#    include "Core/IO/FS/Dirname.h" // 636% 70/11
#    include "Core/IO/FS/Dirpath.h" // 627% 69/11
#    include "Core/IO/FS/Filename.h" // 618% 68/11
#    include "Core/IO/FS/MountingPoint.h" // 636% 70/11
#    include "Core/IO/VirtualFileSystem.h" // 163% 18/11
#    include "Core/IO/VirtualFileSystem_fwd.h" // 218% 24/11
#    include "Core/IO/FileSystem_fwd.h" // 354% 39/11
#    include "Core/Meta/Function.h" // 309% 34/11
#    include "Core/IO/VFS/VirtualFileSystemTrie.h" // 172% 19/11
#    include "Core/Container/AssociativeVector.h" // 790% 87/11
#    include "Core/Container/Pair.h" // 981% 108/11
#    include "Core/Memory/Compression.h" // 181% 20/11
#    include "Core/Memory/MemoryProvider.h" // 72% 8/11
#    include "Core/IO/StreamProvider.h" // 381% 42/11
#    include "Core/IO/BufferedStreamProvider.h" // 72% 8/11
#    include "Core/IO/FS/ConstNames.h" // 90% 10/11
#    include "Core/Container/Stack.h" // 454% 50/11
#    include "Core/Time/Timestamp.h" // 354% 39/11
#    include "Core/Allocator/PoolAllocator-impl.h" // 563% 62/11
#    include "Core/Container/RawStorage.h" // 772% 85/11
#    include "Core/IO/VFS/VirtualFileSystemStream.h" // 100% 11/11
#    include "Core/Maths/ScalarBoundingBox.h" // 418% 46/11
#    include "Core/Maths/ScalarBoundingBox_fwd.h" // 790% 87/11
#    include "Core/Meta/Delegate.h" // 690% 76/11
#    include "Core/Maths/Collision.h" // 154% 17/11
#    include "Core/Maths/Plane.h" // 118% 13/11
#    include "Core/Maths/ScalarMatrix_fwd.h" // 745% 82/11
#    include "Core/Maths/ScalarMatrix.h" // 700% 77/11
#    include "Core/Maths/ScalarMatrixHelpers.h" // 90% 10/11
#    include "Core/Maths/Quaternion.h" // 127% 14/11
#    include "Core/Maths/QuaternionHelpers.h" // 109% 12/11
#    include "Core/Memory/WeakPtr.h" // 500% 55/11
#    include "Core/Misc/ServiceContainer.h" // 72% 8/11
#    include "Core/Container/FlatMap.h" // 81% 9/11
#    include "Core/Thread/Task/Task.h" // 109% 12/11
#    include "Core/Thread/Task/TaskManager.h" // 109% 12/11
#    include "Core/Thread/ThreadContext.h" // 127% 14/11
#    include "Core/Thread/ThreadPool.h" // 81% 9/11
#    include "Core/Time/DateTime.h" // 327% 36/11
#    include "Core.RTTI/RTTI.h" // 681% 75/11
#    include "Core.RTTI/MetaClass.h" // 281% 31/11
#    include "Core.RTTI/Typedefs.h" // 345% 38/11
#    include "Core.RTTI/MetaNamespace.h" // 290% 32/11
#    include "Core/Container/HashMap.h" // 463% 51/11
#    include "Core/Container/HashTable.h" // 472% 52/11
#    include "core.rtti/MetaObject.h" // 263% 29/11
#    include "Core.RTTI/MetaType.h" // 327% 36/11
#    include "Core.RTTI/MetaTypeVirtualTraits.h" // 327% 36/11
#    include "core.rtti/MetaProperty.h" // 209% 23/11
#    include "Core.RTTI/MetaPropertyAccessor.h" // 209% 23/11
#    include "Core.RTTI/Exceptions.h" // 209% 23/11
#    include "Core.RTTI/MetaAtom.h" // 309% 34/11
#    include "Core.RTTI/RTTI_fwd.h" // 663% 73/11
#    include "Core.RTTI/MetaObjectHelpers.h" // 663% 73/11
#    include "Core.RTTI/MetaAtomVisitor.h" // 309% 34/11
#    include "Core.RTTI/MetaTypeTraits.h" // 309% 34/11
#    include "Core.RTTI/MetaTypePromote.h" // 309% 34/11
#    include "core.rtti/MetaDatabase.h" // 72% 8/11
#    include "core.rtti/MetaFunction.h" // 90% 10/11
#    include "Core/Container/Tuple.h" // 145% 16/11
#    include "Core.RTTI/RTTI_Namespace.h" // 136% 15/11
#    include "core.rtti/MetaTransaction.h" // 72% 8/11
#    include "core.rtti/RTTI_extern.h" // 81% 9/11
#    include "Core.Serialize/Serialize.h" // 281% 31/11
#    include "Core.Serialize/Exceptions.h" // 209% 23/11
#    include "Core/Memory/MemoryStream.h" // 200% 22/11
#    include "Core.Serialize/Lexer/Location.h" // 218% 24/11
#    include "Core/Container/StringHashMap.h" // 90% 10/11
#    include "Core.Serialize/Lexer/LookAheadReader.h" // 81% 9/11
#    include "Core.Serialize/Lexer/Match.h" // 109% 12/11
#    include "Core.Serialize/Lexer/Symbol.h" // 127% 14/11
#    include "Core.Serialize/Parser/ParseContext.h" // 72% 8/11
#    include "Core.Serialize/Parser/ParseExpression.h" // 72% 8/11
#    include "Core.Serialize/Parser/ParseItem.h" // 81% 9/11
#    include "Core.Serialize/Parser/ParseList.h" // 81% 9/11
#    include "core.serialize/XML/XML.h" // 90% 10/11
#    include "Core.Network/Network.h" // 181% 20/11
#    include "Core.Network/Socket/Address.h" // 109% 12/11
#    include "core.network/socket/SocketBuffered.h" // 81% 9/11
#    include "core.network/Socket/Socket.h" // 100% 11/11
#    include "core.network/Name.h" // 81% 9/11
#    include "Core.Lattice/Lattice.h" // 127% 14/11
#    include "Core.Graphics/Value.h" // 309% 34/11
#    include "Core.Graphics/Graphics.h" // 863% 95/11
#    include "Core.Graphics/Name.h" // 327% 36/11
#    include "Core.Lattice/GenericMesh.h" // 90% 10/11
#    include "Core.Lattice/GenericMesh_fwd.h" // 90% 10/11
#    include "core.graphics/Device/Geometry/VertexDeclaration.h" // 181% 20/11
#    include "Core.Graphics/ValueBlock.h" // 236% 26/11
#    include "Core.Graphics/Device/DeviceAPIDependantEntity.h" // 481% 53/11
#    include "Core.Graphics/Device/DeviceRevision.h" // 518% 57/11
#    include "Core.Graphics/Device/DeviceResource.h" // 490% 54/11
#    include "Core.Graphics/Device/DeviceResourceType.h" // 500% 55/11
#    include "core.graphics/Device/State/SamplerState.h" // 90% 10/11
#    include "Core.Graphics/Device/Geometry/IndexElementSize.h" // 72% 8/11
#    include "Core.Pixmap/Pixmap.h" // 109% 12/11
#    include "Core.Pixmap/PixelStorage.h" // 72% 8/11
#    include "Core.Pixmap/Pixmap_fwd.h" // 81% 9/11
#    include "Core.Graphics/Device/AbstractDeviceAPIEncapsulator.h" // 227% 25/11
#    include "Core.Graphics/Device/DeviceAPI.h" // 436% 48/11
#    include "Core.Graphics/Device/DeviceAPI_fwd.h" // 445% 49/11
#    include "Core.Graphics/Device/IDeviceAPIContext.h" // 436% 48/11
#    include "Core.Graphics/Device/IDeviceAPIDiagnostics.h" // 445% 49/11
#    include "Core.Graphics/Device/DeviceDiagnostics.h" // 463% 51/11
#    include "Core.Graphics/Device/IDeviceAPIEncapsulator.h" // 445% 49/11
#    include "Core/Maths/ScalarRectangle_fwd.h" // 463% 51/11
#    include "Core.Graphics/Device/PresentationParameters.h" // 272% 30/11
#    include "Core/Maths/ScalarRectangle.h" // 272% 30/11
#    include "core.graphics/Device/DeviceEncapsulator.h" // 354% 39/11
#    include "Core.Graphics/Device/DeviceStatus.h" // 363% 40/11
#    include "Core/Meta/Event.h" // 372% 41/11
#    include "Core.Graphics/Device/DeviceEncapsulatorException.h" // 145% 16/11
#    include "Core.Graphics/Device/DeviceResourceBuffer.h" // 263% 29/11
#    include "Core.Graphics/Device/Pool/DeviceResourceSharable.h" // 281% 31/11
#    include "Core.Graphics/Device/Pool/DeviceSharedEntityKey.h" // 281% 31/11
#    include "Core.Graphics/Device/Geometry/PrimitiveType.h" // 72% 8/11
#    include "Core.Graphics/Device/Shader/ShaderProgram.h" // 118% 13/11
#    include "Core.Graphics/Device/Shader/ShaderProfile.h" // 127% 14/11
#    include "core.graphics/Device/State/BlendState.h" // 72% 8/11
#    include "core.graphics/Device/State/DepthStencilState.h" // 72% 8/11
#    include "core.graphics/Device/State/RasterizerState.h" // 72% 8/11
#    include "Core.Graphics/Device/Texture/Texture2D.h" // 109% 12/11
#    include "Core.Graphics/Device/Texture/Texture.h" // 136% 15/11
#    include "Core/Memory/ComPtr.h" // 181% 20/11
#    include "Core.Graphics/DirectX11/DX11DeviceAPIEncapsulator.h" // 172% 19/11
#    include "Core.Graphics/DirectX11/DX11Includes.h" // 200% 22/11
#    include "Core.Graphics/DirectX11/DX11DeviceWrapper.h" // 172% 19/11
#    include "Core.Graphics/Device/Shader/ShaderCompiled.h" // 72% 8/11
#    include "Core.Graphics/Device/Shader/ConstantBufferLayout.h" // 100% 11/11
#    include "core.graphics/Device/Texture/SurfaceFormat.h" // 145% 16/11
#    include "core.graphics/Window/BasicWindow.h" // 100% 11/11
#    include "core.graphics/window/WindowMessage.h" // 109% 12/11
#    include "Core.Graphics/Window/WindowMessageHandler.h" // 100% 11/11
#    include "Core.ContentPipeline/ContentPipeline.h" // 100% 11/11
#    include "Core.RTTI/RTTI_Macros.h" // 81% 9/11
#    include "Core.RTTI/RTTI_Macros-impl.h" // 72% 8/11
#    include "Core.Application/Application.h" // 218% 24/11
#    include "Core.Application/Input/GamepadButton.h" // 72% 8/11
#    include "Core.Application/Input/KeyboardKey.h" // 72% 8/11
#    include "Core.Application/Input/MouseButton.h" // 72% 8/11
#elif defined(BUILDCONFIG_Win32_Release) || defined(BUILDCONFIG_Win64_Release)
#    include "Core/Misc/Platform_Windows.h" // 2654% 292/11
#    include "Core/Core.h" // 2663% 293/11
#    include "Core/Meta/Aliases.h" // 2663% 293/11
#    include "Core/Meta/Alignment.h" // 2663% 293/11
#    include "Core/Meta/TypeTraits.h" // 2663% 293/11
#    include "Core/Meta/Assert.h" // 2663% 293/11
#    include "Core/Diagnostic/Exception.h" // 2663% 293/11
#    include "Core/Meta/BitCount.h" // 2663% 293/11
#    include "Core/Meta/Cast.h" // 2663% 293/11
#    include "Core/Meta/TypeHash.h" // 2663% 293/11
#    include "Core/Meta/Hash_fwd.h" // 2663% 293/11
#    include "Core/Meta/Delete.h" // 2663% 293/11
#    include "Core/Meta/Enum.h" // 2663% 293/11
#    include "Core/Meta/ForRange.h" // 2663% 293/11
#    include "Core/Meta/Iterator.h" // 2663% 293/11
#    include "Core/Meta/Warnings.h" // 2663% 293/11
#    include "Core/Meta/NumericLimits.h" // 2663% 293/11
#    include "Core/Meta/OneTimeInitialize.h" // 2663% 293/11
#    include "Core/Meta/StronglyTyped.h" // 2663% 293/11
#    include "Core/Meta/ThreadResource.h" // 2663% 293/11
#    include "Core/Allocator/Alloca.h" // 1990% 219/11
#    include "Core/Memory/MemoryView.h" // 2300% 253/11
#    include "Core/Memory/UniquePtr.h" // 2090% 230/11
#    include "Core/Memory/RefPtr.h" // 2118% 233/11
#    include "Core/Memory/MemoryDomain.h" // 2218% 244/11
#    include "Core/Memory/MemoryTracking.h" // 1990% 219/11
#    include "Core/Meta/Singleton.h" // 2072% 228/11
#    include "Core/Meta/AlignedStorage.h" // 2090% 230/11
#    include "Core/Misc/TargetPlatform.h" // 1145% 126/11
#    include "Core/IO/FS/Policies.h" // 1381% 152/11
#    include "Core/IO/StringView.h" // 2218% 244/11
#    include "Core/Container/Hash.h" // 2290% 252/11
#    include "Core/Memory/HashFunctions.h" // 2327% 256/11
#    include "Core/Allocator/Heap.h" // 1990% 219/11
#    include "Core/Allocator/Malloc.h" // 2000% 220/11
#    include "Core/Allocator/PoolAllocatorTag.h" // 1645% 181/11
#    include "Core/Allocator/SingletonPoolAllocator.h" // 109% 12/11
#    include "Core/Allocator/AllocatorBase.h" // 1963% 216/11
#    include "Core/Memory/SegregatedMemoryPool.h" // 609% 67/11
#    include "Core/Allocator/ThreadLocalAllocator.h" // 1963% 216/11
#    include "Core/Allocator/HeapAllocator.h" // 1963% 216/11
#    include "Core/Memory/MemoryPool.h" // 727% 80/11
#    include "Core/Container/IntrusiveList.h" // 881% 97/11
#    include "Core/Thread/AtomicSpinLock.h" // 790% 87/11
#    include "Core/Meta/AutoSingleton.h" // 627% 69/11
#    include "Core/IO/Format.h" // 1145% 126/11
#    include "Core/IO/String.h" // 1736% 191/11
#    include "Core/IO/String_fwd.h" // 1736% 191/11
#    include "Core/Allocator/Allocation.h" // 1963% 216/11
#    include "Core/Allocator/Mallocator.h" // 1963% 216/11
#    include "Core/Allocator/TrackingAllocator.h" // 1963% 216/11
#    include "Core/IO/Stream.h" // 1745% 192/11
#    include "Core/Memory/UniqueView.h" // 1763% 194/11
#    include "Core/Allocator/PoolAllocatorTag-impl.h" // 163% 18/11
#    include "Core/Allocator/PoolAllocator.h" // 981% 108/11
#    include "Core/Color/Color.h" // 400% 44/11
#    include "Core/Color/Color_fwd.h" // 818% 90/11
#    include "Core/Maths/ScalarVector_fwd.h" // 1272% 140/11
#    include "Core/Maths/PackingHelpers.h" // 1009% 111/11
#    include "Core/Maths/Packing_fwd.h" // 1009% 111/11
#    include "Core/Maths/MathHelpers.h" // 1063% 117/11
#    include "Core/Maths/PackedVectors.h" // 636% 70/11
#    include "Core/Maths/ScalarVector.h" // 1118% 123/11
#    include "Core/Maths/ScalarVectorHelpers.h" // 1000% 110/11
#    include "Core/Misc/Endianness.h" // 1018% 112/11
#    include "Core/Container/BitSet.h" // 127% 14/11
#    include "Core/Container/Token.h" // 1009% 111/11
#    include "Core/Diagnostic/LastError.h" // 81% 9/11
#    include "Core/Diagnostic/Logger.h" // 572% 63/11
#    include "core/misc/DLLWrapper.h" // 72% 8/11
#    include "Core/Meta/PointerWFlags.h" // 772% 85/11
#    include "Core/Meta/BitField.h" // 972% 107/11
#    include "Core/IO/FormatHelpers.h" // 172% 19/11
#    include "Core/ThreaD/ReadWriteLock.h" // 354% 39/11
#    include "Core/Diagnostic/CurrentProcess.h" // 90% 10/11
#    include "Core/Time/Timepoint.h" // 154% 17/11
#    include "Core/Maths/Units.h" // 272% 30/11
#    include "Core/Container/Vector.h" // 1336% 147/11
#    include "Core/Allocator/InSituAllocator.h" // 1336% 147/11
#    include "Core/IO/FileSystem.h" // 109% 12/11
#    include "Core/IO/FS/FileSystemProperties.h" // 690% 76/11
#    include "Core/IO/FS/Basename.h" // 627% 69/11
#    include "Core/IO/FS/BasenameNoExt.h" // 636% 70/11
#    include "Core/IO/FS/FileSystemToken.h" // 672% 74/11
#    include "Core/IO/FS/FileSystemToken_fwd.h" // 681% 75/11
#    include "Core/Container/Token_fwd.h" // 681% 75/11
#    include "Core/IO/FS/Extname.h" // 636% 70/11
#    include "Core/IO/FS/Dirname.h" // 636% 70/11
#    include "Core/IO/FS/Dirpath.h" // 627% 69/11
#    include "Core/IO/FS/Filename.h" // 618% 68/11
#    include "Core/IO/FS/MountingPoint.h" // 636% 70/11
#    include "Core/IO/VirtualFileSystem.h" // 163% 18/11
#    include "Core/IO/VirtualFileSystem_fwd.h" // 218% 24/11
#    include "Core/IO/FileSystem_fwd.h" // 354% 39/11
#    include "Core/Meta/Function.h" // 309% 34/11
#    include "Core/IO/VFS/VirtualFileSystemTrie.h" // 172% 19/11
#    include "Core/Container/AssociativeVector.h" // 790% 87/11
#    include "Core/Container/Pair.h" // 981% 108/11
#    include "Core/Memory/Compression.h" // 181% 20/11
#    include "Core/Memory/MemoryProvider.h" // 72% 8/11
#    include "Core/IO/StreamProvider.h" // 381% 42/11
#    include "Core/IO/BufferedStreamProvider.h" // 72% 8/11
#    include "Core/IO/FS/ConstNames.h" // 90% 10/11
#    include "Core/Container/Stack.h" // 454% 50/11
#    include "Core/Time/Timestamp.h" // 354% 39/11
#    include "Core/Allocator/PoolAllocator-impl.h" // 563% 62/11
#    include "Core/Container/RawStorage.h" // 772% 85/11
#    include "Core/IO/VFS/VirtualFileSystemStream.h" // 100% 11/11
#    include "Core/Maths/ScalarBoundingBox.h" // 418% 46/11
#    include "Core/Maths/ScalarBoundingBox_fwd.h" // 781% 86/11
#    include "Core/Meta/Delegate.h" // 690% 76/11
#    include "Core/Maths/Collision.h" // 145% 16/11
#    include "Core/Maths/Plane.h" // 109% 12/11
#    include "Core/Maths/ScalarMatrix_fwd.h" // 745% 82/11
#    include "Core/Maths/ScalarMatrix.h" // 700% 77/11
#    include "Core/Maths/ScalarMatrixHelpers.h" // 81% 9/11
#    include "Core/Maths/Quaternion.h" // 118% 13/11
#    include "Core/Maths/QuaternionHelpers.h" // 100% 11/11
#    include "Core/Memory/WeakPtr.h" // 500% 55/11
#    include "Core/Misc/ServiceContainer.h" // 72% 8/11
#    include "Core/Container/FlatMap.h" // 81% 9/11
#    include "Core/Thread/Task/Task.h" // 109% 12/11
#    include "Core/Thread/Task/TaskManager.h" // 109% 12/11
#    include "Core/Thread/ThreadContext.h" // 127% 14/11
#    include "Core/Thread/ThreadPool.h" // 81% 9/11
#    include "Core/Time/DateTime.h" // 327% 36/11
#    include "Core.RTTI/RTTI.h" // 681% 75/11
#    include "Core.RTTI/MetaClass.h" // 281% 31/11
#    include "Core.RTTI/Typedefs.h" // 345% 38/11
#    include "Core.RTTI/MetaNamespace.h" // 290% 32/11
#    include "Core/Container/HashMap.h" // 463% 51/11
#    include "Core/Container/HashTable.h" // 472% 52/11
#    include "core.rtti/MetaObject.h" // 263% 29/11
#    include "Core.RTTI/MetaType.h" // 327% 36/11
#    include "Core.RTTI/MetaTypeVirtualTraits.h" // 327% 36/11
#    include "core.rtti/MetaProperty.h" // 209% 23/11
#    include "Core.RTTI/MetaPropertyAccessor.h" // 209% 23/11
#    include "Core.RTTI/Exceptions.h" // 209% 23/11
#    include "Core.RTTI/MetaAtom.h" // 309% 34/11
#    include "Core.RTTI/RTTI_fwd.h" // 663% 73/11
#    include "Core.RTTI/MetaObjectHelpers.h" // 663% 73/11
#    include "Core.RTTI/MetaAtomVisitor.h" // 309% 34/11
#    include "Core.RTTI/MetaTypeTraits.h" // 309% 34/11
#    include "Core.RTTI/MetaTypePromote.h" // 309% 34/11
#    include "core.rtti/MetaDatabase.h" // 72% 8/11
#    include "core.rtti/MetaFunction.h" // 90% 10/11
#    include "Core/Container/Tuple.h" // 145% 16/11
#    include "Core.RTTI/RTTI_Namespace.h" // 136% 15/11
#    include "core.rtti/MetaTransaction.h" // 72% 8/11
#    include "core.rtti/RTTI_extern.h" // 81% 9/11
#    include "Core.Serialize/Serialize.h" // 281% 31/11
#    include "Core.Serialize/Exceptions.h" // 209% 23/11
#    include "Core/Memory/MemoryStream.h" // 200% 22/11
#    include "Core.Serialize/Lexer/Location.h" // 218% 24/11
#    include "Core/Container/StringHashMap.h" // 90% 10/11
#    include "Core.Serialize/Lexer/LookAheadReader.h" // 81% 9/11
#    include "Core.Serialize/Lexer/Match.h" // 109% 12/11
#    include "Core.Serialize/Lexer/Symbol.h" // 127% 14/11
#    include "Core.Serialize/Parser/ParseContext.h" // 72% 8/11
#    include "Core.Serialize/Parser/ParseExpression.h" // 72% 8/11
#    include "Core.Serialize/Parser/ParseItem.h" // 81% 9/11
#    include "Core.Serialize/Parser/ParseList.h" // 81% 9/11
#    include "core.serialize/XML/XML.h" // 90% 10/11
#    include "Core.Network/Network.h" // 181% 20/11
#    include "Core.Network/Socket/Address.h" // 109% 12/11
#    include "core.network/socket/SocketBuffered.h" // 81% 9/11
#    include "core.network/Socket/Socket.h" // 100% 11/11
#    include "core.network/Name.h" // 81% 9/11
#    include "Core.Lattice/Lattice.h" // 127% 14/11
#    include "Core.Graphics/Value.h" // 309% 34/11
#    include "Core.Graphics/Graphics.h" // 863% 95/11
#    include "Core.Graphics/Name.h" // 327% 36/11
#    include "Core.Lattice/GenericMesh.h" // 90% 10/11
#    include "Core.Lattice/GenericMesh_fwd.h" // 90% 10/11
#    include "core.graphics/Device/Geometry/VertexDeclaration.h" // 181% 20/11
#    include "Core.Graphics/ValueBlock.h" // 236% 26/11
#    include "Core.Graphics/Device/DeviceAPIDependantEntity.h" // 481% 53/11
#    include "Core.Graphics/Device/DeviceRevision.h" // 518% 57/11
#    include "Core.Graphics/Device/DeviceResource.h" // 490% 54/11
#    include "Core.Graphics/Device/DeviceResourceType.h" // 500% 55/11
#    include "core.graphics/Device/State/SamplerState.h" // 90% 10/11
#    include "Core.Graphics/Device/Geometry/IndexElementSize.h" // 72% 8/11
#    include "Core.Pixmap/Pixmap.h" // 109% 12/11
#    include "Core.Pixmap/PixelStorage.h" // 72% 8/11
#    include "Core.Pixmap/Pixmap_fwd.h" // 81% 9/11
#    include "Core.Graphics/Device/AbstractDeviceAPIEncapsulator.h" // 227% 25/11
#    include "Core.Graphics/Device/DeviceAPI.h" // 436% 48/11
#    include "Core.Graphics/Device/DeviceAPI_fwd.h" // 445% 49/11
#    include "Core.Graphics/Device/IDeviceAPIContext.h" // 436% 48/11
#    include "Core.Graphics/Device/IDeviceAPIDiagnostics.h" // 445% 49/11
#    include "Core.Graphics/Device/DeviceDiagnostics.h" // 463% 51/11
#    include "Core.Graphics/Device/IDeviceAPIEncapsulator.h" // 445% 49/11
#    include "Core/Maths/ScalarRectangle_fwd.h" // 463% 51/11
#    include "Core.Graphics/Device/PresentationParameters.h" // 272% 30/11
#    include "Core/Maths/ScalarRectangle.h" // 272% 30/11
#    include "core.graphics/Device/DeviceEncapsulator.h" // 354% 39/11
#    include "Core.Graphics/Device/DeviceStatus.h" // 363% 40/11
#    include "Core/Meta/Event.h" // 372% 41/11
#    include "Core.Graphics/Device/DeviceEncapsulatorException.h" // 145% 16/11
#    include "Core.Graphics/Device/DeviceResourceBuffer.h" // 263% 29/11
#    include "Core.Graphics/Device/Pool/DeviceResourceSharable.h" // 281% 31/11
#    include "Core.Graphics/Device/Pool/DeviceSharedEntityKey.h" // 281% 31/11
#    include "Core.Graphics/Device/Geometry/PrimitiveType.h" // 72% 8/11
#    include "Core.Graphics/Device/Shader/ShaderProgram.h" // 118% 13/11
#    include "Core.Graphics/Device/Shader/ShaderProfile.h" // 127% 14/11
#    include "core.graphics/Device/State/BlendState.h" // 72% 8/11
#    include "core.graphics/Device/State/DepthStencilState.h" // 72% 8/11
#    include "core.graphics/Device/State/RasterizerState.h" // 72% 8/11
#    include "Core.Graphics/Device/Texture/Texture2D.h" // 109% 12/11
#    include "Core.Graphics/Device/Texture/Texture.h" // 136% 15/11
#    include "Core/Memory/ComPtr.h" // 181% 20/11
#    include "Core.Graphics/DirectX11/DX11DeviceAPIEncapsulator.h" // 172% 19/11
#    include "Core.Graphics/DirectX11/DX11Includes.h" // 200% 22/11
#    include "Core.Graphics/DirectX11/DX11DeviceWrapper.h" // 172% 19/11
#    include "Core.Graphics/Device/Shader/ShaderCompiled.h" // 72% 8/11
#    include "Core.Graphics/Device/Shader/ConstantBufferLayout.h" // 100% 11/11
#    include "core.graphics/Device/Texture/SurfaceFormat.h" // 145% 16/11
#    include "core.graphics/Window/BasicWindow.h" // 100% 11/11
#    include "core.graphics/window/WindowMessage.h" // 109% 12/11
#    include "Core.Graphics/Window/WindowMessageHandler.h" // 100% 11/11
#    include "Core.ContentPipeline/ContentPipeline.h" // 100% 11/11
#    include "Core.RTTI/RTTI_Macros.h" // 81% 9/11
#    include "Core.RTTI/RTTI_Macros-impl.h" // 72% 8/11
#    include "Core.Application/Application.h" // 218% 24/11
#    include "Core.Application/Input/GamepadButton.h" // 72% 8/11
#    include "Core.Application/Input/KeyboardKey.h" // 72% 8/11
#    include "Core.Application/Input/MouseButton.h" // 72% 8/11
#elif defined(BUILDCONFIG_Win32_Profiling) || defined(BUILDCONFIG_Win64_Profiling)
#    include "Core/Misc/Platform_Windows.h" // 2654% 292/11
#    include "Core/Core.h" // 2663% 293/11
#    include "Core/Meta/Aliases.h" // 2663% 293/11
#    include "Core/Meta/Alignment.h" // 2663% 293/11
#    include "Core/Meta/TypeTraits.h" // 2663% 293/11
#    include "Core/Meta/Assert.h" // 2663% 293/11
#    include "Core/Diagnostic/Exception.h" // 2663% 293/11
#    include "Core/Meta/BitCount.h" // 2663% 293/11
#    include "Core/Meta/Cast.h" // 2663% 293/11
#    include "Core/Meta/TypeHash.h" // 2663% 293/11
#    include "Core/Meta/Hash_fwd.h" // 2663% 293/11
#    include "Core/Meta/Delete.h" // 2663% 293/11
#    include "Core/Meta/Enum.h" // 2663% 293/11
#    include "Core/Meta/ForRange.h" // 2663% 293/11
#    include "Core/Meta/Iterator.h" // 2663% 293/11
#    include "Core/Meta/Warnings.h" // 2663% 293/11
#    include "Core/Meta/NumericLimits.h" // 2663% 293/11
#    include "Core/Meta/OneTimeInitialize.h" // 2663% 293/11
#    include "Core/Meta/StronglyTyped.h" // 2663% 293/11
#    include "Core/Meta/ThreadResource.h" // 2663% 293/11
#    include "Core/Allocator/Alloca.h" // 1963% 216/11
#    include "Core/Memory/MemoryView.h" // 2281% 251/11
#    include "Core/Memory/UniquePtr.h" // 2072% 228/11
#    include "Core/Memory/RefPtr.h" // 2100% 231/11
#    include "Core/Memory/MemoryDomain.h" // 2200% 242/11
#    include "Core/Memory/MemoryTracking.h" // 1972% 217/11
#    include "Core/Meta/Singleton.h" // 2054% 226/11
#    include "Core/Meta/AlignedStorage.h" // 2072% 228/11
#    include "Core/Misc/TargetPlatform.h" // 1136% 125/11
#    include "Core/IO/FS/Policies.h" // 1372% 151/11
#    include "Core/IO/StringView.h" // 2190% 241/11
#    include "Core/Container/Hash.h" // 2263% 249/11
#    include "Core/Memory/HashFunctions.h" // 2300% 253/11
#    include "Core/Allocator/Heap.h" // 1972% 217/11
#    include "Core/Allocator/Malloc.h" // 1972% 217/11
#    include "Core/Allocator/PoolAllocatorTag.h" // 1645% 181/11
#    include "Core/Allocator/SingletonPoolAllocator.h" // 109% 12/11
#    include "Core/Allocator/AllocatorBase.h" // 1945% 214/11
#    include "Core/Memory/SegregatedMemoryPool.h" // 609% 67/11
#    include "Core/Allocator/ThreadLocalAllocator.h" // 1945% 214/11
#    include "Core/Allocator/HeapAllocator.h" // 1945% 214/11
#    include "Core/Memory/MemoryPool.h" // 727% 80/11
#    include "Core/Container/IntrusiveList.h" // 881% 97/11
#    include "Core/Thread/AtomicSpinLock.h" // 790% 87/11
#    include "Core/Meta/AutoSingleton.h" // 627% 69/11
#    include "Core/Allocator/PoolAllocatorTag-impl.h" // 163% 18/11
#    include "Core/Allocator/PoolAllocator.h" // 981% 108/11
#    include "Core/Color/Color.h" // 400% 44/11
#    include "Core/Color/Color_fwd.h" // 818% 90/11
#    include "Core/Maths/ScalarVector_fwd.h" // 1272% 140/11
#    include "Core/Maths/PackingHelpers.h" // 1009% 111/11
#    include "Core/Maths/Packing_fwd.h" // 1009% 111/11
#    include "Core/Maths/MathHelpers.h" // 1063% 117/11
#    include "Core/Maths/PackedVectors.h" // 636% 70/11
#    include "Core/Maths/ScalarVector.h" // 1118% 123/11
#    include "Core/Maths/ScalarVectorHelpers.h" // 1000% 110/11
#    include "Core/Misc/Endianness.h" // 1018% 112/11
#    include "Core/Container/BitSet.h" // 127% 14/11
#    include "Core/Memory/UniqueView.h" // 1718% 189/11
#    include "Core/Container/Token.h" // 1009% 111/11
#    include "Core/IO/String.h" // 1690% 186/11
#    include "Core/IO/String_fwd.h" // 1690% 186/11
#    include "Core/Allocator/Allocation.h" // 1936% 213/11
#    include "Core/Allocator/Mallocator.h" // 1936% 213/11
#    include "Core/Allocator/TrackingAllocator.h" // 1936% 213/11
#    include "Core/IO/Stream.h" // 1700% 187/11
#    include "Core/Diagnostic/LastError.h" // 81% 9/11
#    include "Core/Diagnostic/Logger.h" // 563% 62/11
#    include "Core/IO/Format.h" // 918% 101/11
#    include "core/misc/DLLWrapper.h" // 72% 8/11
#    include "Core/Meta/PointerWFlags.h" // 772% 85/11
#    include "Core/Meta/BitField.h" // 972% 107/11
#    include "Core/IO/FormatHelpers.h" // 154% 17/11
#    include "Core/ThreaD/ReadWriteLock.h" // 354% 39/11
#    include "Core/Diagnostic/CurrentProcess.h" // 90% 10/11
#    include "Core/Time/Timepoint.h" // 154% 17/11
#    include "Core/Maths/Units.h" // 272% 30/11
#    include "Core/Container/Vector.h" // 1327% 146/11
#    include "Core/Allocator/InSituAllocator.h" // 1327% 146/11
#    include "Core/IO/FileSystem.h" // 109% 12/11
#    include "Core/IO/FS/FileSystemProperties.h" // 690% 76/11
#    include "Core/IO/FS/Basename.h" // 627% 69/11
#    include "Core/IO/FS/BasenameNoExt.h" // 636% 70/11
#    include "Core/IO/FS/FileSystemToken.h" // 672% 74/11
#    include "Core/IO/FS/FileSystemToken_fwd.h" // 681% 75/11
#    include "Core/Container/Token_fwd.h" // 681% 75/11
#    include "Core/IO/FS/Extname.h" // 636% 70/11
#    include "Core/IO/FS/Dirname.h" // 636% 70/11
#    include "Core/IO/FS/Dirpath.h" // 627% 69/11
#    include "Core/IO/FS/Filename.h" // 618% 68/11
#    include "Core/IO/FS/MountingPoint.h" // 636% 70/11
#    include "Core/IO/VirtualFileSystem.h" // 163% 18/11
#    include "Core/IO/VirtualFileSystem_fwd.h" // 218% 24/11
#    include "Core/IO/FileSystem_fwd.h" // 354% 39/11
#    include "Core/Meta/Function.h" // 309% 34/11
#    include "Core/IO/VFS/VirtualFileSystemTrie.h" // 172% 19/11
#    include "Core/Container/AssociativeVector.h" // 790% 87/11
#    include "Core/Container/Pair.h" // 981% 108/11
#    include "Core/Memory/Compression.h" // 181% 20/11
#    include "Core/Memory/MemoryProvider.h" // 72% 8/11
#    include "Core/IO/StreamProvider.h" // 381% 42/11
#    include "Core/IO/BufferedStreamProvider.h" // 72% 8/11
#    include "Core/IO/FS/ConstNames.h" // 90% 10/11
#    include "Core/Container/Stack.h" // 454% 50/11
#    include "Core/Time/Timestamp.h" // 354% 39/11
#    include "Core/Allocator/PoolAllocator-impl.h" // 563% 62/11
#    include "Core/Container/RawStorage.h" // 772% 85/11
#    include "Core/IO/VFS/VirtualFileSystemStream.h" // 100% 11/11
#    include "Core/Maths/ScalarBoundingBox.h" // 418% 46/11
#    include "Core/Maths/ScalarBoundingBox_fwd.h" // 781% 86/11
#    include "Core/Meta/Delegate.h" // 690% 76/11
#    include "Core/Maths/Collision.h" // 145% 16/11
#    include "Core/Maths/Plane.h" // 109% 12/11
#    include "Core/Maths/ScalarMatrix_fwd.h" // 745% 82/11
#    include "Core/Maths/ScalarMatrix.h" // 700% 77/11
#    include "Core/Maths/ScalarMatrixHelpers.h" // 81% 9/11
#    include "Core/Maths/Quaternion.h" // 118% 13/11
#    include "Core/Maths/QuaternionHelpers.h" // 100% 11/11
#    include "Core/Memory/WeakPtr.h" // 500% 55/11
#    include "Core/Misc/ServiceContainer.h" // 72% 8/11
#    include "Core/Container/FlatMap.h" // 81% 9/11
#    include "Core/Thread/Task/Task.h" // 109% 12/11
#    include "Core/Thread/Task/TaskManager.h" // 109% 12/11
#    include "Core/Thread/ThreadContext.h" // 127% 14/11
#    include "Core/Thread/ThreadPool.h" // 81% 9/11
#    include "Core/Time/DateTime.h" // 327% 36/11
#    include "Core.RTTI/RTTI.h" // 681% 75/11
#    include "Core.RTTI/MetaClass.h" // 281% 31/11
#    include "Core.RTTI/Typedefs.h" // 345% 38/11
#    include "Core.RTTI/MetaNamespace.h" // 290% 32/11
#    include "Core/Container/HashMap.h" // 463% 51/11
#    include "Core/Container/HashTable.h" // 472% 52/11
#    include "core.rtti/MetaObject.h" // 263% 29/11
#    include "Core.RTTI/MetaType.h" // 327% 36/11
#    include "Core.RTTI/MetaTypeVirtualTraits.h" // 327% 36/11
#    include "core.rtti/MetaProperty.h" // 209% 23/11
#    include "Core.RTTI/MetaPropertyAccessor.h" // 209% 23/11
#    include "Core.RTTI/Exceptions.h" // 209% 23/11
#    include "Core.RTTI/MetaAtom.h" // 309% 34/11
#    include "Core.RTTI/RTTI_fwd.h" // 663% 73/11
#    include "Core.RTTI/MetaObjectHelpers.h" // 663% 73/11
#    include "Core.RTTI/MetaAtomVisitor.h" // 309% 34/11
#    include "Core.RTTI/MetaTypeTraits.h" // 309% 34/11
#    include "Core.RTTI/MetaTypePromote.h" // 309% 34/11
#    include "core.rtti/MetaDatabase.h" // 72% 8/11
#    include "core.rtti/MetaFunction.h" // 90% 10/11
#    include "Core/Container/Tuple.h" // 145% 16/11
#    include "Core.RTTI/RTTI_Namespace.h" // 136% 15/11
#    include "core.rtti/MetaTransaction.h" // 72% 8/11
#    include "core.rtti/RTTI_extern.h" // 81% 9/11
#    include "Core.Serialize/Serialize.h" // 281% 31/11
#    include "Core.Serialize/Exceptions.h" // 209% 23/11
#    include "Core/Memory/MemoryStream.h" // 200% 22/11
#    include "Core.Serialize/Lexer/Location.h" // 218% 24/11
#    include "Core/Container/StringHashMap.h" // 90% 10/11
#    include "Core.Serialize/Lexer/LookAheadReader.h" // 81% 9/11
#    include "Core.Serialize/Lexer/Match.h" // 109% 12/11
#    include "Core.Serialize/Lexer/Symbol.h" // 127% 14/11
#    include "Core.Serialize/Parser/ParseContext.h" // 72% 8/11
#    include "Core.Serialize/Parser/ParseExpression.h" // 72% 8/11
#    include "Core.Serialize/Parser/ParseItem.h" // 81% 9/11
#    include "Core.Serialize/Parser/ParseList.h" // 81% 9/11
#    include "core.serialize/XML/XML.h" // 90% 10/11
#    include "Core.Network/Network.h" // 181% 20/11
#    include "Core.Network/Socket/Address.h" // 109% 12/11
#    include "core.network/socket/SocketBuffered.h" // 81% 9/11
#    include "core.network/Socket/Socket.h" // 100% 11/11
#    include "core.network/Name.h" // 81% 9/11
#    include "Core.Lattice/Lattice.h" // 127% 14/11
#    include "Core.Graphics/Value.h" // 309% 34/11
#    include "Core.Graphics/Graphics.h" // 863% 95/11
#    include "Core.Graphics/Name.h" // 327% 36/11
#    include "Core.Lattice/GenericMesh.h" // 90% 10/11
#    include "Core.Lattice/GenericMesh_fwd.h" // 90% 10/11
#    include "core.graphics/Device/Geometry/VertexDeclaration.h" // 181% 20/11
#    include "Core.Graphics/ValueBlock.h" // 236% 26/11
#    include "Core.Graphics/Device/DeviceAPIDependantEntity.h" // 481% 53/11
#    include "Core.Graphics/Device/DeviceRevision.h" // 518% 57/11
#    include "Core.Graphics/Device/DeviceResource.h" // 490% 54/11
#    include "Core.Graphics/Device/DeviceResourceType.h" // 500% 55/11
#    include "core.graphics/Device/State/SamplerState.h" // 90% 10/11
#    include "Core.Graphics/Device/Geometry/IndexElementSize.h" // 72% 8/11
#    include "Core.Pixmap/Pixmap.h" // 109% 12/11
#    include "Core.Pixmap/PixelStorage.h" // 72% 8/11
#    include "Core.Pixmap/Pixmap_fwd.h" // 81% 9/11
#    include "Core.Graphics/Device/AbstractDeviceAPIEncapsulator.h" // 227% 25/11
#    include "Core.Graphics/Device/DeviceAPI.h" // 436% 48/11
#    include "Core.Graphics/Device/DeviceAPI_fwd.h" // 445% 49/11
#    include "Core.Graphics/Device/IDeviceAPIContext.h" // 436% 48/11
#    include "Core.Graphics/Device/IDeviceAPIDiagnostics.h" // 445% 49/11
#    include "Core.Graphics/Device/DeviceDiagnostics.h" // 463% 51/11
#    include "Core.Graphics/Device/IDeviceAPIEncapsulator.h" // 445% 49/11
#    include "Core/Maths/ScalarRectangle_fwd.h" // 463% 51/11
#    include "Core.Graphics/Device/PresentationParameters.h" // 272% 30/11
#    include "Core/Maths/ScalarRectangle.h" // 272% 30/11
#    include "core.graphics/Device/DeviceEncapsulator.h" // 354% 39/11
#    include "Core.Graphics/Device/DeviceStatus.h" // 363% 40/11
#    include "Core/Meta/Event.h" // 372% 41/11
#    include "Core.Graphics/Device/DeviceEncapsulatorException.h" // 145% 16/11
#    include "Core.Graphics/Device/DeviceResourceBuffer.h" // 263% 29/11
#    include "Core.Graphics/Device/Pool/DeviceResourceSharable.h" // 281% 31/11
#    include "Core.Graphics/Device/Pool/DeviceSharedEntityKey.h" // 281% 31/11
#    include "Core.Graphics/Device/Geometry/PrimitiveType.h" // 72% 8/11
#    include "Core.Graphics/Device/Shader/ShaderProgram.h" // 118% 13/11
#    include "Core.Graphics/Device/Shader/ShaderProfile.h" // 127% 14/11
#    include "core.graphics/Device/State/BlendState.h" // 72% 8/11
#    include "core.graphics/Device/State/DepthStencilState.h" // 72% 8/11
#    include "core.graphics/Device/State/RasterizerState.h" // 72% 8/11
#    include "Core.Graphics/Device/Texture/Texture2D.h" // 109% 12/11
#    include "Core.Graphics/Device/Texture/Texture.h" // 136% 15/11
#    include "Core/Memory/ComPtr.h" // 181% 20/11
#    include "Core.Graphics/DirectX11/DX11DeviceAPIEncapsulator.h" // 172% 19/11
#    include "Core.Graphics/DirectX11/DX11Includes.h" // 200% 22/11
#    include "Core.Graphics/DirectX11/DX11DeviceWrapper.h" // 172% 19/11
#    include "Core.Graphics/Device/Shader/ShaderCompiled.h" // 72% 8/11
#    include "Core.Graphics/Device/Shader/ConstantBufferLayout.h" // 100% 11/11
#    include "core.graphics/Device/Texture/SurfaceFormat.h" // 145% 16/11
#    include "core.graphics/Window/BasicWindow.h" // 100% 11/11
#    include "core.graphics/window/WindowMessage.h" // 109% 12/11
#    include "Core.Graphics/Window/WindowMessageHandler.h" // 100% 11/11
#    include "Core.ContentPipeline/ContentPipeline.h" // 100% 11/11
#    include "Core.RTTI/RTTI_Macros.h" // 81% 9/11
#    include "Core.RTTI/RTTI_Macros-impl.h" // 72% 8/11
#    include "Core.Application/Application.h" // 218% 24/11
#    include "Core.Application/Input/GamepadButton.h" // 72% 8/11
#    include "Core.Application/Input/KeyboardKey.h" // 72% 8/11
#    include "Core.Application/Input/MouseButton.h" // 72% 8/11
#elif defined(BUILDCONFIG_Win32_Final) || defined(BUILDCONFIG_Win64_Final)
#    include "Core/Misc/Platform_Windows.h" // 2654% 292/11
#    include "Core/Core.h" // 2663% 293/11
#    include "Core/Meta/Aliases.h" // 2663% 293/11
#    include "Core/Meta/Alignment.h" // 2663% 293/11
#    include "Core/Meta/TypeTraits.h" // 2663% 293/11
#    include "Core/Meta/Assert.h" // 2663% 293/11
#    include "Core/Diagnostic/Exception.h" // 2663% 293/11
#    include "Core/Meta/BitCount.h" // 2663% 293/11
#    include "Core/Meta/Cast.h" // 2663% 293/11
#    include "Core/Meta/TypeHash.h" // 2663% 293/11
#    include "Core/Meta/Hash_fwd.h" // 2663% 293/11
#    include "Core/Meta/Delete.h" // 2663% 293/11
#    include "Core/Meta/Enum.h" // 2663% 293/11
#    include "Core/Meta/ForRange.h" // 2663% 293/11
#    include "Core/Meta/Iterator.h" // 2663% 293/11
#    include "Core/Meta/Warnings.h" // 2663% 293/11
#    include "Core/Meta/NumericLimits.h" // 2663% 293/11
#    include "Core/Meta/OneTimeInitialize.h" // 2663% 293/11
#    include "Core/Meta/StronglyTyped.h" // 2663% 293/11
#    include "Core/Meta/ThreadResource.h" // 2663% 293/11
#    include "Core/Allocator/Alloca.h" // 1945% 214/11
#    include "Core/Memory/MemoryView.h" // 2272% 250/11
#    include "Core/Memory/UniquePtr.h" // 2054% 226/11
#    include "Core/Memory/RefPtr.h" // 2081% 229/11
#    include "Core/Memory/MemoryDomain.h" // 2190% 241/11
#    include "Core/Memory/MemoryTracking.h" // 1954% 215/11
#    include "Core/Meta/Singleton.h" // 2036% 224/11
#    include "Core/Meta/AlignedStorage.h" // 2054% 226/11
#    include "Core/Misc/TargetPlatform.h" // 1127% 124/11
#    include "Core/IO/FS/Policies.h" // 1363% 150/11
#    include "Core/IO/StringView.h" // 2181% 240/11
#    include "Core/Container/Hash.h" // 2254% 248/11
#    include "Core/Memory/HashFunctions.h" // 2290% 252/11
#    include "Core/Allocator/Heap.h" // 1954% 215/11
#    include "Core/Allocator/Malloc.h" // 1954% 215/11
#    include "Core/Allocator/PoolAllocatorTag.h" // 1645% 181/11
#    include "Core/Allocator/SingletonPoolAllocator.h" // 109% 12/11
#    include "Core/Allocator/AllocatorBase.h" // 1927% 212/11
#    include "Core/Memory/SegregatedMemoryPool.h" // 609% 67/11
#    include "Core/Allocator/ThreadLocalAllocator.h" // 1927% 212/11
#    include "Core/Allocator/HeapAllocator.h" // 1927% 212/11
#    include "Core/Memory/MemoryPool.h" // 727% 80/11
#    include "Core/Container/IntrusiveList.h" // 881% 97/11
#    include "Core/Thread/AtomicSpinLock.h" // 781% 86/11
#    include "Core/Meta/AutoSingleton.h" // 627% 69/11
#    include "Core/Allocator/PoolAllocatorTag-impl.h" // 163% 18/11
#    include "Core/Allocator/PoolAllocator.h" // 981% 108/11
#    include "Core/Color/Color.h" // 400% 44/11
#    include "Core/Color/Color_fwd.h" // 809% 89/11
#    include "Core/Maths/ScalarVector_fwd.h" // 1263% 139/11
#    include "Core/Maths/PackingHelpers.h" // 1000% 110/11
#    include "Core/Maths/Packing_fwd.h" // 1000% 110/11
#    include "Core/Maths/MathHelpers.h" // 1054% 116/11
#    include "Core/Maths/PackedVectors.h" // 636% 70/11
#    include "Core/Maths/ScalarVector.h" // 1109% 122/11
#    include "Core/Maths/ScalarVectorHelpers.h" // 990% 109/11
#    include "Core/Misc/Endianness.h" // 1009% 111/11
#    include "Core/Container/BitSet.h" // 127% 14/11
#    include "Core/Memory/UniqueView.h" // 1700% 187/11
#    include "Core/Container/Token.h" // 1009% 111/11
#    include "Core/IO/String.h" // 1672% 184/11
#    include "Core/IO/String_fwd.h" // 1672% 184/11
#    include "Core/Allocator/Allocation.h" // 1918% 211/11
#    include "Core/Allocator/Mallocator.h" // 1918% 211/11
#    include "Core/Allocator/TrackingAllocator.h" // 1918% 211/11
#    include "Core/IO/Stream.h" // 1681% 185/11
#    include "Core/Diagnostic/LastError.h" // 81% 9/11
#    include "Core/Diagnostic/Logger.h" // 554% 61/11
#    include "Core/IO/Format.h" // 890% 98/11
#    include "core/misc/DLLWrapper.h" // 72% 8/11
#    include "Core/Meta/PointerWFlags.h" // 772% 85/11
#    include "Core/Meta/BitField.h" // 972% 107/11
#    include "Core/IO/FormatHelpers.h" // 145% 16/11
#    include "Core/ThreaD/ReadWriteLock.h" // 354% 39/11
#    include "Core/Diagnostic/CurrentProcess.h" // 81% 9/11
#    include "Core/Time/Timepoint.h" // 145% 16/11
#    include "Core/Maths/Units.h" // 263% 29/11
#    include "Core/Container/Vector.h" // 1327% 146/11
#    include "Core/Allocator/InSituAllocator.h" // 1327% 146/11
#    include "Core/IO/FileSystem.h" // 109% 12/11
#    include "Core/IO/FS/FileSystemProperties.h" // 690% 76/11
#    include "Core/IO/FS/Basename.h" // 627% 69/11
#    include "Core/IO/FS/BasenameNoExt.h" // 636% 70/11
#    include "Core/IO/FS/FileSystemToken.h" // 672% 74/11
#    include "Core/IO/FS/FileSystemToken_fwd.h" // 681% 75/11
#    include "Core/Container/Token_fwd.h" // 681% 75/11
#    include "Core/IO/FS/Extname.h" // 636% 70/11
#    include "Core/IO/FS/Dirname.h" // 636% 70/11
#    include "Core/IO/FS/Dirpath.h" // 627% 69/11
#    include "Core/IO/FS/Filename.h" // 618% 68/11
#    include "Core/IO/FS/MountingPoint.h" // 636% 70/11
#    include "Core/IO/VirtualFileSystem.h" // 163% 18/11
#    include "Core/IO/VirtualFileSystem_fwd.h" // 218% 24/11
#    include "Core/IO/FileSystem_fwd.h" // 354% 39/11
#    include "Core/Meta/Function.h" // 309% 34/11
#    include "Core/IO/VFS/VirtualFileSystemTrie.h" // 172% 19/11
#    include "Core/Container/AssociativeVector.h" // 790% 87/11
#    include "Core/Container/Pair.h" // 981% 108/11
#    include "Core/Memory/Compression.h" // 181% 20/11
#    include "Core/Memory/MemoryProvider.h" // 72% 8/11
#    include "Core/IO/StreamProvider.h" // 381% 42/11
#    include "Core/IO/BufferedStreamProvider.h" // 72% 8/11
#    include "Core/IO/FS/ConstNames.h" // 90% 10/11
#    include "Core/Container/Stack.h" // 454% 50/11
#    include "Core/Time/Timestamp.h" // 354% 39/11
#    include "Core/Allocator/PoolAllocator-impl.h" // 563% 62/11
#    include "Core/Container/RawStorage.h" // 772% 85/11
#    include "Core/IO/VFS/VirtualFileSystemStream.h" // 100% 11/11
#    include "Core/Maths/ScalarBoundingBox.h" // 409% 45/11
#    include "Core/Maths/ScalarBoundingBox_fwd.h" // 772% 85/11
#    include "Core/Meta/Delegate.h" // 690% 76/11
#    include "Core/Maths/Collision.h" // 145% 16/11
#    include "Core/Maths/Plane.h" // 109% 12/11
#    include "Core/Maths/ScalarMatrix_fwd.h" // 745% 82/11
#    include "Core/Maths/ScalarMatrix.h" // 700% 77/11
#    include "Core/Maths/ScalarMatrixHelpers.h" // 81% 9/11
#    include "Core/Maths/Quaternion.h" // 118% 13/11
#    include "Core/Maths/QuaternionHelpers.h" // 100% 11/11
#    include "Core/Memory/WeakPtr.h" // 500% 55/11
#    include "Core/Misc/ServiceContainer.h" // 72% 8/11
#    include "Core/Container/FlatMap.h" // 81% 9/11
#    include "Core/Thread/Task/Task.h" // 109% 12/11
#    include "Core/Thread/Task/TaskManager.h" // 109% 12/11
#    include "Core/Thread/ThreadContext.h" // 127% 14/11
#    include "Core/Thread/ThreadPool.h" // 81% 9/11
#    include "Core/Time/DateTime.h" // 327% 36/11
#    include "Core.RTTI/RTTI.h" // 681% 75/11
#    include "Core.RTTI/MetaClass.h" // 281% 31/11
#    include "Core.RTTI/Typedefs.h" // 345% 38/11
#    include "Core.RTTI/MetaNamespace.h" // 290% 32/11
#    include "Core/Container/HashMap.h" // 463% 51/11
#    include "Core/Container/HashTable.h" // 472% 52/11
#    include "core.rtti/MetaObject.h" // 263% 29/11
#    include "Core.RTTI/MetaType.h" // 327% 36/11
#    include "Core.RTTI/MetaTypeVirtualTraits.h" // 327% 36/11
#    include "core.rtti/MetaProperty.h" // 209% 23/11
#    include "Core.RTTI/MetaPropertyAccessor.h" // 209% 23/11
#    include "Core.RTTI/Exceptions.h" // 209% 23/11
#    include "Core.RTTI/MetaAtom.h" // 309% 34/11
#    include "Core.RTTI/RTTI_fwd.h" // 663% 73/11
#    include "Core.RTTI/MetaObjectHelpers.h" // 663% 73/11
#    include "Core.RTTI/MetaAtomVisitor.h" // 309% 34/11
#    include "Core.RTTI/MetaTypeTraits.h" // 309% 34/11
#    include "Core.RTTI/MetaTypePromote.h" // 309% 34/11
#    include "core.rtti/MetaDatabase.h" // 72% 8/11
#    include "core.rtti/MetaFunction.h" // 90% 10/11
#    include "Core/Container/Tuple.h" // 145% 16/11
#    include "Core.RTTI/RTTI_Namespace.h" // 136% 15/11
#    include "core.rtti/MetaTransaction.h" // 72% 8/11
#    include "core.rtti/RTTI_extern.h" // 81% 9/11
#    include "Core.Serialize/Serialize.h" // 281% 31/11
#    include "Core.Serialize/Exceptions.h" // 209% 23/11
#    include "Core/Memory/MemoryStream.h" // 200% 22/11
#    include "Core.Serialize/Lexer/Location.h" // 218% 24/11
#    include "Core/Container/StringHashMap.h" // 90% 10/11
#    include "Core.Serialize/Lexer/LookAheadReader.h" // 81% 9/11
#    include "Core.Serialize/Lexer/Match.h" // 109% 12/11
#    include "Core.Serialize/Lexer/Symbol.h" // 127% 14/11
#    include "Core.Serialize/Parser/ParseContext.h" // 72% 8/11
#    include "Core.Serialize/Parser/ParseExpression.h" // 72% 8/11
#    include "Core.Serialize/Parser/ParseItem.h" // 81% 9/11
#    include "Core.Serialize/Parser/ParseList.h" // 81% 9/11
#    include "core.serialize/XML/XML.h" // 90% 10/11
#    include "Core.Network/Network.h" // 181% 20/11
#    include "Core.Network/Socket/Address.h" // 109% 12/11
#    include "core.network/socket/SocketBuffered.h" // 81% 9/11
#    include "core.network/Socket/Socket.h" // 100% 11/11
#    include "core.network/Name.h" // 81% 9/11
#    include "Core.Lattice/Lattice.h" // 127% 14/11
#    include "Core.Graphics/Value.h" // 309% 34/11
#    include "Core.Graphics/Graphics.h" // 863% 95/11
#    include "Core.Graphics/Name.h" // 327% 36/11
#    include "Core.Lattice/GenericMesh.h" // 90% 10/11
#    include "Core.Lattice/GenericMesh_fwd.h" // 90% 10/11
#    include "core.graphics/Device/Geometry/VertexDeclaration.h" // 181% 20/11
#    include "Core.Graphics/ValueBlock.h" // 236% 26/11
#    include "Core.Graphics/Device/DeviceAPIDependantEntity.h" // 481% 53/11
#    include "Core.Graphics/Device/DeviceRevision.h" // 518% 57/11
#    include "Core.Graphics/Device/DeviceResource.h" // 490% 54/11
#    include "Core.Graphics/Device/DeviceResourceType.h" // 500% 55/11
#    include "core.graphics/Device/State/SamplerState.h" // 90% 10/11
#    include "Core.Graphics/Device/Geometry/IndexElementSize.h" // 72% 8/11
#    include "Core.Pixmap/Pixmap.h" // 109% 12/11
#    include "Core.Pixmap/PixelStorage.h" // 72% 8/11
#    include "Core.Pixmap/Pixmap_fwd.h" // 81% 9/11
#    include "Core.Graphics/Device/AbstractDeviceAPIEncapsulator.h" // 218% 24/11
#    include "Core.Graphics/Device/DeviceAPI.h" // 427% 47/11
#    include "Core.Graphics/Device/DeviceAPI_fwd.h" // 436% 48/11
#    include "Core.Graphics/Device/IDeviceAPIContext.h" // 427% 47/11
#    include "Core.Graphics/Device/IDeviceAPIDiagnostics.h" // 436% 48/11
#    include "Core.Graphics/Device/DeviceDiagnostics.h" // 463% 51/11
#    include "Core.Graphics/Device/IDeviceAPIEncapsulator.h" // 436% 48/11
#    include "Core/Maths/ScalarRectangle_fwd.h" // 454% 50/11
#    include "Core.Graphics/Device/PresentationParameters.h" // 263% 29/11
#    include "Core/Maths/ScalarRectangle.h" // 263% 29/11
#    include "core.graphics/Device/DeviceEncapsulator.h" // 354% 39/11
#    include "Core.Graphics/Device/DeviceStatus.h" // 363% 40/11
#    include "Core/Meta/Event.h" // 372% 41/11
#    include "Core.Graphics/Device/DeviceEncapsulatorException.h" // 145% 16/11
#    include "Core.Graphics/Device/DeviceResourceBuffer.h" // 263% 29/11
#    include "Core.Graphics/Device/Pool/DeviceResourceSharable.h" // 281% 31/11
#    include "Core.Graphics/Device/Pool/DeviceSharedEntityKey.h" // 281% 31/11
#    include "Core.Graphics/Device/Geometry/PrimitiveType.h" // 72% 8/11
#    include "Core.Graphics/Device/Shader/ShaderProgram.h" // 118% 13/11
#    include "Core.Graphics/Device/Shader/ShaderProfile.h" // 127% 14/11
#    include "core.graphics/Device/State/BlendState.h" // 72% 8/11
#    include "core.graphics/Device/State/DepthStencilState.h" // 72% 8/11
#    include "core.graphics/Device/State/RasterizerState.h" // 72% 8/11
#    include "Core.Graphics/Device/Texture/Texture2D.h" // 109% 12/11
#    include "Core.Graphics/Device/Texture/Texture.h" // 136% 15/11
#    include "Core/Memory/ComPtr.h" // 181% 20/11
#    include "Core.Graphics/DirectX11/DX11DeviceAPIEncapsulator.h" // 172% 19/11
#    include "Core.Graphics/DirectX11/DX11Includes.h" // 200% 22/11
#    include "Core.Graphics/DirectX11/DX11DeviceWrapper.h" // 172% 19/11
#    include "Core.Graphics/Device/Shader/ShaderCompiled.h" // 72% 8/11
#    include "Core.Graphics/Device/Shader/ConstantBufferLayout.h" // 100% 11/11
#    include "core.graphics/Device/Texture/SurfaceFormat.h" // 145% 16/11
#    include "core.graphics/Window/BasicWindow.h" // 100% 11/11
#    include "core.graphics/window/WindowMessage.h" // 109% 12/11
#    include "Core.Graphics/Window/WindowMessageHandler.h" // 100% 11/11
#    include "Core.ContentPipeline/ContentPipeline.h" // 100% 11/11
#    include "Core.RTTI/RTTI_Macros.h" // 81% 9/11
#    include "Core.RTTI/RTTI_Macros-impl.h" // 72% 8/11
#    include "Core.Application/Application.h" // 218% 24/11
#    include "Core.Application/Input/GamepadButton.h" // 72% 8/11
#    include "Core.Application/Input/KeyboardKey.h" // 72% 8/11
#    include "Core.Application/Input/MouseButton.h" // 72% 8/11
#else
#     error "unknown build config"
#endif

