/*
// Generated by PCHRefactor.rb v1.1 for target <Runtime/VFS>
//------------------------------------------------------------------------------
// Date : 2018-09-05 21:22:04 UTC
*/

//                                           Target | STD | SDK | PRJ | SRC
// ------------------------------------------------------------------------
//                          Runtime/VFS-Win32-Debug |  42 |   1 |   0 |   5
//                      Runtime/VFS-Win32-FastDebug |  42 |   1 |   0 |   5
//                        Runtime/VFS-Win32-Release |  42 |   1 |   0 |   5
//                      Runtime/VFS-Win32-Profiling |  42 |   1 |   0 |   5
//                          Runtime/VFS-Win32-Final |  42 |   1 |   0 |   5
//                          Runtime/VFS-Win64-Debug |  42 |   1 |   0 |   5
//                      Runtime/VFS-Win64-FastDebug |  42 |   1 |   0 |   5
//                        Runtime/VFS-Win64-Release |  42 |   1 |   0 |   5
//                      Runtime/VFS-Win64-Profiling |  42 |   1 |   0 |   5
//                          Runtime/VFS-Win64-Final |  42 |   1 |   0 |   5

/*
// Standard headers
//------------------------------------------------------------------------------
*/
#include <algorithm>
#include <cstdint>
#include <cstdlib>
#include <limits>
#include <cfloat>
#include <climits>
#include <cmath>
#include <cwchar>
#include <cstddef>
#include <initializer_list>
#include <new>
#include <exception>
#include <type_traits>
#include <utility>
#include <iosfwd>
#include <cstdio>
#include <cstring>
#include <atomic>
#include <memory>
#include <typeinfo>
#include <functional>
#include <tuple>
#include <unordered_map>
#include <list>
#include <stdexcept>
#include <vector>
#include <iterator>
#include <istream>
#include <ostream>
#include <ios>
#include <streambuf>
#include <system_error>
#include <cerrno>
#include <mutex>
#include <chrono>
#include <ratio>
#include <thread>
#include <cctype>
#include <cwctype>
#include <locale>
#include <string>
#include <ctime>

/*
// SDK headers
//------------------------------------------------------------------------------
*/
#include <SDKDDKVer.h>

/*
// Project headers
//------------------------------------------------------------------------------
*/

