/*
// Generated by PCHRefactor.rb v1.1 for target <Runtime/VFS>
//------------------------------------------------------------------------------
// Date : 2019-12-24 02:36:22 UTC
*/

//                                           Target | STD | SDK | PRJ | SRC
// ------------------------------------------------------------------------
//                          Runtime/VFS-Win32-Debug |  43 |   0 |   0 |   6
//                      Runtime/VFS-Win32-FastDebug |  50 |   0 |  23 |   6
//                        Runtime/VFS-Win32-Release |  43 |   0 |   0 |   6
//                      Runtime/VFS-Win32-Profiling |  43 |   0 |   0 |   6
//                          Runtime/VFS-Win32-Final |  43 |   0 |   0 |   6
//                          Runtime/VFS-Win64-Debug |  43 |   0 |   0 |   6
//                      Runtime/VFS-Win64-FastDebug |  50 |   0 |  23 |   6
//                        Runtime/VFS-Win64-Release |  43 |   0 |   0 |   6
//                      Runtime/VFS-Win64-Profiling |  43 |   0 |   0 |   6
//                          Runtime/VFS-Win64-Final |  43 |   0 |   0 |   6

/*
// Standard headers
//------------------------------------------------------------------------------
*/
#if 0 // dummy
#elif defined(BUILD_Win32_Debug) || defined(BUILD_Win32_Release) || defined(BUILD_Win32_Profiling) || defined(BUILD_Win32_Final) || defined(BUILD_Win64_Debug) || defined(BUILD_Win64_Release) || defined(BUILD_Win64_Profiling) || defined(BUILD_Win64_Final)
#    include <algorithm>
#    include <cstdint>
#    include <cstdlib>
#    include <limits>
#    include <cfloat>
#    include <climits>
#    include <cwchar>
#    include <cstdio>
#    include <cstddef>
#    include <initializer_list>
#    include <new>
#    include <exception>
#    include <type_traits>
#    include <cstring>
#    include <utility>
#    include <atomic>
#    include <memory>
#    include <iosfwd>
#    include <typeinfo>
#    include <functional>
#    include <tuple>
#    include <unordered_map>
#    include <cmath>
#    include <list>
#    include <vector>
#    include <stdexcept>
#    include <iterator>
#    include <istream>
#    include <ostream>
#    include <ios>
#    include <streambuf>
#    include <system_error>
#    include <cerrno>
#    include <mutex>
#    include <chrono>
#    include <ratio>
#    include <thread>
#    include <locale>
#    include <ctime>
#    include <regex>
#    include <cctype>
#    include <string>
#    include <cwctype>
#elif defined(BUILD_Win32_FastDebug) || defined(BUILD_Win64_FastDebug)
#    include <algorithm>
#    include <cstdint>
#    include <cstdlib>
#    include <limits>
#    include <cfloat>
#    include <climits>
#    include <cwchar>
#    include <cstdio>
#    include <cstddef>
#    include <initializer_list>
#    include <new>
#    include <exception>
#    include <type_traits>
#    include <cstring>
#    include <utility>
#    include <atomic>
#    include <memory>
#    include <iosfwd>
#    include <typeinfo>
#    include <functional>
#    include <tuple>
#    include <unordered_map>
#    include <cmath>
#    include <list>
#    include <vector>
#    include <stdexcept>
#    include <iterator>
#    include <istream>
#    include <ostream>
#    include <ios>
#    include <streambuf>
#    include <system_error>
#    include <cerrno>
#    include <mutex>
#    include <chrono>
#    include <ratio>
#    include <thread>
#    include <locale>
#    include <ctime>
#    include <regex>
#    include <cctype>
#    include <string>
#    include <cwctype>
#    include <optional>
#    include <iostream>
#    include <clocale>
#    include <cassert>
#    include <condition_variable>
#    include <memory_resource>
#    include <cstdarg>
#else
#     error "unknown build config"
#endif

/*
// SDK headers
//------------------------------------------------------------------------------
*/

/*
// Project headers
//------------------------------------------------------------------------------
*/
#if 0 // dummy
#elif defined(BUILD_Win32_Debug) || defined(BUILD_Win32_Release) || defined(BUILD_Win32_Profiling) || defined(BUILD_Win32_Final) || defined(BUILD_Win64_Debug) || defined(BUILD_Win64_Release) || defined(BUILD_Win64_Profiling) || defined(BUILD_Win64_Final)
#elif defined(BUILD_Win32_FastDebug) || defined(BUILD_Win64_FastDebug)
#    include "Runtime/Core/Public/IO/String_fwd.h"
#    include "Runtime/Core/Public/Core.h"
#    include "Runtime/Core/Public/Memory/MemoryView.h"
#    include "Runtime/Core/Public/Allocator/Allocation.h"
#    include "Runtime/Core/Public/Memory/UniquePtr.h"
#    include "Runtime/Core/Public/Memory/RefPtr.h"
#    include "Runtime/Core/Public/Container/RawStorage_fwd.h"
#    include "Runtime/Core/Public/IO/StreamPolicies.h"
#    include "Runtime/Core/Public/IO/StreamProvider.h"
#    include "Runtime/Core/Public/IO/StringView.h"
#    include "Runtime/Core/Public/Misc/Function_fwd.h"
#    include "Runtime/Core/Public/Container/Vector.h"
#    include "Runtime/Core/Public/Meta/Singleton.h"
#    include "Runtime/Core/Public/Time/Timestamp.h"
#    include "Runtime/Core/Public/IO/String.h"
#    include "Runtime/Core/Public/Memory/UniqueView.h"
#    include "Runtime/Core/Public/Container/RawStorage.h"
#    include "Runtime/Core/Public/IO/Format.h"
#    include "Runtime/Core/Public/IO/StringBuilder.h"
#    include "Runtime/Core/Public/IO/TextWriter.h"
#    include "Runtime/Core/Public/Memory/MemoryProvider.h"
#    include "Runtime/Core/Public/Misc/Function.h"
#    include "Runtime/Core/Public/Diagnostic/Logger.h"
#else
#     error "unknown build config"
#endif

