//----------------------------------------------------------------------------
UNITS_BEGIN(Time)
UNITS_DECL(Time,        Microseconds,    1000,  void)
UNITS_DECL(Time,        Milliseconds,    1000,  Time::Microseconds)
UNITS_DECL(Time,        Seconds,         60,    Time::Milliseconds)
UNITS_DECL(Time,        Minutes,         60,    Time::Seconds)
UNITS_DECL(Time,        Hours,           24,    Time::Minutes)
UNITS_DECL(Time,        Days,            1,     Time::Hours)
UNITS_END()
//----------------------------------------------------------------------------
UNITS_BEGIN(Distance)
UNITS_DECL(Distance,    Millimeters,     10,    void)
UNITS_DECL(Distance,    Centimeters,     100,   Distance::Millimeters)
UNITS_DECL(Distance,    Meters,          1000,  Distance::Centimeters)
UNITS_DECL(Distance,    Kilometers,      1,     Distance::Meters)
UNITS_END()
//----------------------------------------------------------------------------
UNITS_BEGIN(Mass)
UNITS_DECL(Mass,        Picograms,       1000,  void)
UNITS_DECL(Mass,        Nanograms,       1000,  Mass::Picograms)
UNITS_DECL(Mass,        Micrograms,      1000,  Mass::Nanograms)
UNITS_DECL(Mass,        Milligrams,      1000,  Mass::Micrograms)
UNITS_DECL(Mass,        Grams,           1000,  Mass::Milligrams)
UNITS_DECL(Mass,        Kilograms,       1000,  Mass::Grams)
UNITS_DECL(Mass,        Tonnes,          1,     Mass::Kilograms)
UNITS_END()
//----------------------------------------------------------------------------
UNITS_BEGIN(Storage)
UNITS_DECL(Storage,     Bytes,           1024,  void)
UNITS_DECL(Storage,     Kilobytes,       1024,  Storage::Bytes)
UNITS_DECL(Storage,     Megabytes,       1024,  Storage::Kilobytes)
UNITS_DECL(Storage,     Gigabytes,       1024,  Storage::Megabytes)
UNITS_DECL(Storage,     Terabytes,       1024,  Storage::Gigabytes)
UNITS_DECL(Storage,     Petabytes,       1,     Storage::Terabytes)
UNITS_END()
//----------------------------------------------------------------------------
