//----------------------------------------------------------------------------
UNITS_BEGIN(Time)
UNITS_DECL(Time,        µs, Microseconds,   1000,   void)
UNITS_DECL(Time,        ms, Milliseconds,   1000,   Core::Units::Time::Microseconds)
UNITS_DECL(Time,         s, Seconds,        60,     Core::Units::Time::Milliseconds)
UNITS_DECL(Time,         m, Minutes,        60,     Core::Units::Time::Seconds)
UNITS_DECL(Time,         h, Hours,          24,     Core::Units::Time::Minutes)
UNITS_DECL(Time,         d, Days,           1,      Core::Units::Time::Hours)
UNITS_END()
//----------------------------------------------------------------------------
UNITS_BEGIN(Distance)
UNITS_DECL(Distance,    mm, Millimeters,    10,     void)
UNITS_DECL(Distance,    cm, Centimeters,    100,    Core::Units::Distance::Millimeters)
UNITS_DECL(Distance,     m, Meters,         1000,   Core::Units::Distance::Centimeters)
UNITS_DECL(Distance,    km, Kilometers,     1,      Core::Units::Distance::Meters)
UNITS_END()
//----------------------------------------------------------------------------
UNITS_BEGIN(Mass)
UNITS_DECL(Mass,        pg, Picograms,      1000,   void)
UNITS_DECL(Mass,        ng, Nanograms,      1000,   Core::Units::Mass::Picograms)
UNITS_DECL(Mass,        µg, Micrograms,     1000,   Core::Units::Mass::Nanograms)
UNITS_DECL(Mass,        mg, Milligrams,     1000,   Core::Units::Mass::Micrograms)
UNITS_DECL(Mass,         g, Grams,          1000,   Core::Units::Mass::Milligrams)
UNITS_DECL(Mass,        kg, Kilograms,      1000,   Core::Units::Mass::Grams)
UNITS_DECL(Mass,         t, Tonnes,         1,      Core::Units::Mass::Kilograms)
UNITS_END()
//----------------------------------------------------------------------------
UNITS_BEGIN(Storage)
UNITS_DECL(Storage,      b, Bytes,          1024,   void)
UNITS_DECL(Storage,     kb, Kilobytes,      1024,   Core::Units::Storage::Bytes)
UNITS_DECL(Storage,     mb, Megabytes,      1024,   Core::Units::Storage::Kilobytes)
UNITS_DECL(Storage,     gb, Gigabytes,      1024,   Core::Units::Storage::Megabytes)
UNITS_DECL(Storage,     tb, Terabytes,      1024,   Core::Units::Storage::Gigabytes)
UNITS_DECL(Storage,     pb, Petabytes,      1,      Core::Units::Storage::Terabytes)
UNITS_END()
//----------------------------------------------------------------------------
