name: Linux tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 1
        submodules: true
    
    - name: install GLFW 3
      run: sudo apt-get install libglfw3-dev

    - uses: actions/setup-go@v5
      with:
        go-version: '1.22.0'
        check-latest: true
        
    - name: build PPE
      run: go run PPE.go configure -v -Ide -Color -and build Programs/ShaderToy-Linux64-Devel
          
    - uses: actions/upload-artifact@v4
      with:
        name: ShaderToy-Linux64-Devel
        path: Output/Binaries
