name: Windows build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@master
      with:
        submodules: true
        
    - uses: actions/setup-go@v5
      with:
        go-version: '1.22.0'
        check-latest: true
        
    - name: build PPE
      run: >
        go run PPE.go configure -v -and build 
          Programs/ShaderToy-Win64-FastDebug
          
    - uses: actions/upload-artifact@v4
      with:
        name: UnitTest-Win64-Debug
        path: Output/Binaries
