name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Checkout submodules
      uses: srt32/git-actions@v0.0.3
      with:
        args: git submodule update --init --recursive
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.6'
    - name: build
      run: ruby ppe.rb --bff --fbuild --Unity -v
